### PR TITLE
chore: fixed a typo for internal, unused part of the file upload icon for status page

### PR DESCRIPTION
**Pull request by jmolnar-comparative**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes https://github.com/louislam/uptime-kuma/issues/4749

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by CommanderStorm** [comment]
I consider this as an uncontroversial bugfix
=> I would like this to be in 1.23.X instead

Could you rebase this to said branch via running 

```
npm run rebase-pr-to-1.23.X
```

**Comment by Zaid-maker** [comment]
That's a lot of changes??

**Comment by jmolnar-comparative** [comment]
I think somebody changed the target to 1.23.x; it was originally based on the main branch.

**Comment by jmolnar-comparative** [comment]
Needs to be rebased. Frank asked me to do that, but I've been too busy with my job

**Comment by jmolnar-comparative** [comment]
For context: my original PR was 1 commit, +/- 1 line

**Comment by CommanderStorm** [comment]
I guess then this is going into `v2.0`.

Think this can also be considered a "feature" as this strictly speaking adds functionality to the internal api and not to the user interface.

=> merging with junior maintainer approval.

**Comment by jmolnar-comparative** [comment]
@CommanderStorm I made a backport to 1.23.X here: https://github.com/louislam/uptime-kuma/pull/4757

**Pull request merged**
