### PR TITLE
Add notification provider - Push

### PR DESCRIPTION
**Pull request by arjunkomath**
# Description

Add support for new notification provider -> https://push.techulus.com

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

CleanShot 2022-01-21 at 18 46 32

### CODE REVIEW

**Comment by arjunkomath** [comment]
FYI, I tried to update all languages by running `update-language-files`, but there were tons of changes.
Please let me know how to handle translations.

**Review by Saibamen — APPROVED** [review]

**Comment by chakflying** [comment]
If you are just adding a few keys I think it's fine to do it by hand to `en.js`.

**Comment by arjunkomath** [comment]
@chakflying Its just one key and is already in `en`, I was wondering how to copy them to all the other languages?

CleanShot 2022-01-21 at 20 39 49
`

**Comment by Saibamen** [comment]
> @chakflying Its just one key and is already in `en`, I was wondering how to copy them to all the other languages?
> 
> CleanShot 2022-01-21 at 20 39 49 `

https://github.com/louislam/uptime-kuma/tree/master/src/languages#how-to-translate

Run `npm run update-language-files`

**Pull request merged**
