### PR TITLE
Fix: "Show Clickable Link" checkbox does not update until entire dashboard is saved 

### LINKED ISSUE #3794: "Show Clickable Link" checkbox does not update until entire dashboard is saved
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After checking the "Show Clickable Link" box in a monitor's setting dialog and closing the dialog, reopening the monitor's setting dialog shows the same box still unchecked giving the impression that the setting did not change. Only after saving aving the dashboard and returning to the monitor's setting dialog does the box stay checked.

### 👟 Reproduction steps

1. Press Edit Status Page
2. Press the settings cog on a monitor
3. Tick "Show Clickable Link" and close the dialog
4. Press settings cog of the same monitor again

### 👀 Expected behavior

The checkbox should stay checked to hint that it will be enabled after pressing save on the entire status page

### 😓 Actual Behavior

The checkbox remains unchecked and the setting seemingly didn't change

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox 117.0.1

### 🐋 Docker Version

Docker 24.0.6

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Rai-Sahil**
- [x] I have read and understand the pull request rules.

# Description

Fixes #3794 "Show Clickable Link" checkbox does not update until entire dashboard is saved 

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

All the tests are passed
Screenshot 2023-11-13 at 10 41 28 PM
 
Here's the fixed issue

https://github.com/louislam/uptime-kuma/assets/78111534/c0162567-2384-4a55-bfd2-0e5da40f4711

### CODE REVIEW

**Comment by chakflying** [comment]
Have you actually tried using the Status Pages? Can you explain how the way you "fixed" the issue makes any sense given how the feature works?

**Comment by Rai-Sahil** [comment]
> Have you actually tried using the Status Pages? Can you explain how the way you "fixed" the issue makes any sense given how the feature works?

I have tried using the status page. From what I thought from the Issue #3794 was that the whole point is to save the current state of checkbox in `isClickable` variable. Tho I did used local storage for it. So if you guys are using that same variable  at multiple places and everywhere you're using local storage to access the state of checkbox, only then it might give you trouble. Else it seems fine to me. You can try it out. I can give you the access to local repo.

**Comment by chakflying** [comment]
The setting is applied per-monitor, meaning that enabling "clickable click" should only affect that item.

**Comment by BxtGeek** [comment]
looks like issue is still there

**Pull request closed without merging**
