### PR TITLE
Display discords timestamps via `<:t:timestamp_unix:f>`

### LINKED ISSUE #543: [Suggestion] Change time of Discord notification
When we have the discord notification, the time is printed in string, but discord added the markdown timestamp
Use instead this :
<:t:timestampunix:f>

It will print it in the language of the user and UTC correctly :)

### PR DESCRIPTION
**Pull request by LifeIsAParadox**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #543 

## Type of change

Please delete any options that are not relevant.

- Other
use Discord timestamp format

https://discord.com/developers/docs/reference#message-formatting-formats

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)
grafik

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
About the functionality:
This kind of undermines the ability to set the timezone of the uptime server and instead hands that off to discord.
- The problem I see: is this transparent to the users or do we need to change this from `"Time"` to something like `"Time (client-locale)"`

- I have attached two comments which fix the formatting issues raised by `check-linters`
- Could you attach a before and after screenshot?
- Have you made sure that the code you wrote and the previos code is identical?  
From what I looked at, the time of the `heartbeatJSON` and the current time might be different. Could you use the timestamp all other notification providers use as well?
The variable you are replacing gets created here:
https://github.com/louislam/uptime-kuma/blob/f0c54be43f26993d024a98a401a03dc6badc05e0/server/model/monitor.js#L1288-L1290
As I read this code (and the lines previosly) `"time"` might be slightly different from the time of notification.
Could you use the same time-reference as well?

**Comment by louislam** [comment]
Should convert the time from `heartbeatJSON["time"]`, not `Date.now()`

**Comment by LifeIsAParadox** [comment]
> First of all:
> 
>     * please give the PR a descriptive title
> 
>     * please actually run the `Checklist` (not only checking the boxes) ^^
> 
> 
> About the functionality: This kind of undermines the ability to set the timezone of the uptime server and instead hands that off to discord.
> 
>     * The problem I see: is this transparent to the users or do we need to change this from `"Time"` to something like `"Time (client-locale)"` (I am not super happy with that as well)
> 
>     * I have attached two comments which fix the formatting issues raised by `check-linters`
> 
>     * Could you attach a before and after screenshot?
> 
>     * Have you made sure that the code you wrote and the previos code is identical?
>       From what I looked at, the time of the `heartbeatJSON` and the current time might be different. Could you use the timestamp all other notification providers use as well?
>       The variable you are replacing gets created here:
>       https://github.com/louislam/uptime-kuma/blob/f0c54be43f26993d024a98a401a03dc6badc05e0/server/model/monitor.js#L1288-L1290
>       
>       As I read this code (and the lines previosly) `"time"` might be slightly different from the time of notification.
>       Could you use the same time-reference as well?

For Discord, it makes more sense to use the built-in markdown timestamp because it automatically displays the correct time for the user. You can find more information about it [here](https://discord.com/developers/docs/reference#message-formatting-formats).
image

Sorry for the wrong format, I didn't use ESLint properly, but I've fixed it now.

**Comment by LifeIsAParadox** [comment]
> Should convert the time from `heartbeatJSON["time"]`, not `Date.now()`

changed Date.now() to heartbeatJSON["time"]

**Comment by louislam** [comment]
I think the time is incorrect

I input `<t:1697527649:f>` manually, it could show the correct local datetime.

image

**Comment by CommanderStorm** [comment]
@LifeIsAParadox can you explain this difference?

**Comment by CommanderStorm** [comment]
@LifeIsAParadox
Thanks for your work.
Given that louis has not gotten this to work correctly and there has not been any activity after that, I am going to close this PR.
If something changes (f.ex. if the reproduction of the feature starts working because Discord fixed a bug) we can reopen the PR. ^^

**Pull request closed without merging**
