### PR TITLE
WIP Feature/ingress monitoring

### LINKED ISSUE #882: Automation while deploying with kubernetes
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I would like to have a way with which i can create a pipeline or some other way to add monitoring probes. 

### ✔️ Solution

To make it more efficient, I am looking for a way to automate the creation of uptime for our different environments. The solution would be to inject JSON files with monitoring points imported to uptime kuma at time of creation.

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Richard87**
# Description

Fixes #882 

The Kuma Uptime needs to be restarted after any monitors have been added or removed.
To run it, execute `node extra/map-ingress.js`

Maps over ingresses and looks for the annotation `uptime-kuma.ingress.kubernetes.io/monitor`.
Configuration:

- `IMPORT_ALL_INGRESSES` Map all namespaces.
- `INGRESS_NAMESPACES=default,kube-public` look in specific namespaces.
- The pod needs a Role and RoleBindings to be allowed to look for ingeress in the specified namespaces (or all)

Optional:

- `KUBERNETES_MASTER` to specify kubernetes API server to talk with, when running in kubernetes it is unnessesary.
- `KUBERNETES_TOKEN_FILE` specify location of access token
- `KUBERNETES_TOKEN` the access token
- `OWNER_ID` defaults to 1

## Type of change
New feature (non-breaking change which adds functionality)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I ran ESLint and other linters for modified files
- [X] I have performed a self-review of my own code and test it
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)
```
Importing Database
Data Dir: ./data/
SQLite config:
database.js:121 Array(1) [Object]
database.js:122 Array(1) [Object]
SQLite Version: 3.36.0
Connecting to https://KUBE_MASTER to collect ingresses
found 10 ingresses!
Found 231 domains
Found 0 missing monitors
Found 11 outdated ingresses to be removed
Finished
```

### CODE REVIEW

**Comment by Richard87** [comment]
The required RBAC:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: IngressRole
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - networking.k8s.io/v1
    resources:
      - ingresses
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: IngressRole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: IngressRole
subjects:
  - kind: ServiceAccount
    namespace: uptime-kuma
    name: uptime-kuma
```

**Comment by qingfengfenga** [comment]
Building the image directly using this repository code cannot be started

https://github.com/Richard87/uptime-kuma/tree/feature/ingress

Am I missing something?

Build commands
```
docker build -f docker/dockerfile-alpine  -t uptime-kuma .
```

Build log
```
docker build -f docker/dockerfile-alpine  -t uptime-kuma:1.10.2-alpine-pr-940 .
Sending build context to Docker daemon  2.373MB
Step 1/15 : FROM louislam/uptime-kuma:base-alpine AS build
 ---> 86a18ad00384
Step 2/15 : WORKDIR /app
 ---> Using cache
 ---> 7cfd4f18827f
Step 3/15 : ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
 ---> Using cache
 ---> ae30d4a86d7f
Step 4/15 : COPY . .
 ---> 1a6c61288338
Step 5/15 : RUN npm ci --production &&     chmod +x /app/extra/entrypoint.sh
 ---> Running in 2233d46b61dd

> vue-demi@0.11.4 postinstall /app/node_modules/vue-qrcode/node_modules/vue-demi
> node ./scripts/postinstall.js


> core-js@2.6.12 postinstall /app/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> vue-demi@0.10.1 postinstall /app/node_modules/vue-demi
> node ./scripts/postinstall.js


> @louislam/sqlite3@6.0.0 install /app/node_modules/@louislam/sqlite3
> node-pre-gyp install --fallback-to-build

[@louislam/sqlite3] Success: "/app/node_modules/@louislam/sqlite3/lib/binding/napi-v6-linux-x64/node_sqlite3.node" is installed via remote

> @fortawesome/fontawesome-common-types@0.2.36 postinstall /app/node_modules/@fortawesome/fontawesome-common-types
> node attribution.js

Font Awesome Free 0.2.36 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/free-solid-svg-icons@5.15.4 postinstall /app/node_modules/@fortawesome/free-solid-svg-icons
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/free-regular-svg-icons@5.15.4 postinstall /app/node_modules/@fortawesome/free-regular-svg-icons
> node attribution.js

Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/fontawesome-svg-core@1.2.36 postinstall /app/node_modules/@fortawesome/fontawesome-svg-core
> node attribution.js

Font Awesome Free 1.2.36 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

added 430 packages in 44.189s
Removing intermediate container 2233d46b61dd
 ---> 974da601edf6
Step 6/15 : FROM louislam/uptime-kuma:base-alpine AS release
 ---> 86a18ad00384
Step 7/15 : WORKDIR /app
 ---> Using cache
 ---> 7cfd4f18827f
Step 8/15 : COPY --from=build /app /app
 ---> 42533fe801f8
Step 9/15 : EXPOSE 3001
 ---> Running in bc5d93268c40
Removing intermediate container bc5d93268c40
 ---> d9964a2ec151
Step 10/15 : VOLUME ["/app/data"]
 ---> Running in c9ba8180b296
Removing intermediate container c9ba8180b296
 ---> 2f706078027a
Step 11/15 : HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
 ---> Running in 6fa96666500c
Removing intermediate container 6fa96666500c
 ---> 3b014bec2ff2
Step 12/15 : ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
 ---> Running in 6c1e4ca2232d
Removing intermediate container 6c1e4ca2232d
 ---> 6836f5a61a4d
Step 13/15 : CMD ["node", "server/server.js"]
 ---> Running in 70fe52e9d1ab
Removing intermediate container 70fe52e9d1ab
 ---> fb55dfaa5b86
Step 14/15 : FROM release AS nightly
 ---> fb55dfaa5b86
Step 15/15 : RUN npm run mark-as-nightly
 ---> Running in a3990add326f

> uptime-kuma@1.10.2 mark-as-nightly /app
> node extra/mark-as-nightly.js

Old Version: 1.10.2
New Version: 1.10.2-nightly
Removing intermediate container a3990add326f
 ---> ae1621148b31
Successfully built ae1621148b31
Successfully tagged uptime-kuma:1.10.2-alpine-pr-940
```

Startup log
```
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.10.2-nightly
Creating express and socket.io instance
Server Type: HTTP
Error: Cannot find 'dist/index.html', did you install correctly?
```

**Comment by Richard87** [comment]
After starting the container and Uptime-kuma, you have to get a shell in the container, and execute `node extra/map-ingress.js` :)

**Comment by qingfengfenga** [comment]
Sorry, for this script `node extra/map-ingress.js`, whether set as a startup parameter or manually executed in the container, failed. Because I'm using alpine mirror? Or something else?

```
Data Dir: ./data/
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
(node:52) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:52) Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:52) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by Richard87** [comment]
Hi! 

Notice this error in the output: `Error: Request failed with status code 403`, you might have forgotten, or made a mistake in the RBAC configuration? 

the service account that uptime kuma uses must have access to read and list all ingresses you specify (via env variables or arguments)

**Comment by qingfengfenga** [comment]
This is my deployment process, using the RBAC file provided above

```
❯ cat RBAC.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma-test
  namespace: uptime-kuma-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: IngressRole
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: IngressRole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: IngressRole
subjects:
  - kind: ServiceAccount
    namespace: uptime-kuma-test
    name: uptime-kuma-test%   
```

```
❯ kubectl apply -f RBAC.yaml -n uptime-kuma-test
serviceaccount/uptime-kuma-test created
clusterrole.rbac.authorization.k8s.io/IngressRole created
clusterrolebinding.rbac.authorization.k8s.io/IngressRole created
❯ kubectl apply -f uptime-test.yaml   -n uptime-kuma-test
statefulset.apps/uptime created
service/uptime-service created
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/uptime-api-ingress created
❯ kubectl get ServiceAccount -n uptime-kuma-test
NAME               SECRETS   AGE
default            1         3d23h
uptime-kuma-test   1         75s
❯ kubectl get ClusterRole -n uptime-kuma-test | grep IngressRole
IngressRole                                                            2021-11-29T09:05:23Z
❯ kubectl get ClusterRoleBinding -n uptime-kuma-test | grep IngressRole
IngressRole                                            ClusterRole/IngressRole                                                            117s
❯ kubectl get pods -n uptime-kuma-test
NAME       READY   STATUS    RESTARTS   AGE
uptime-0   1/1     Running   0          113s
❯ kubectl logs -f uptime-0 -n uptime-kuma-test
Data Dir: ./data/
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
(node:1) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

**Comment by Richard87** [comment]
Did you specify that `statefulset.apps/uptime` uses the `uptime-kuma-test` serviceAccount?

Can you post `uptime-test.yaml` (or the yaml for `statefulset.apps/uptime`)?

**Comment by qingfengfenga** [comment]
This is my yaml file
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime
spec:
  replicas: 1
  serviceName: uptime-service
  selector:
    matchLabels:
      app: uptime
  template:
    metadata:
      labels:
        app: uptime
    spec:
      serviceAccount: uptime-kuma-test
      containers:
      - name: uptime
        command:
          - node
          - extra/map-ingress.js
        image: uptime-kuma:1.10.2-alpine-pr-940
        imagePullPolicy: IfNotPresent
        ports:
        - name: uptime
          containerPort: 3001
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1000Mi
#        envFrom:
#        - configMapRef:
#            name: uptime-config-map
        volumeMounts:
        - name: uptime-data
          mountPath: /app/data
#      imagePullSecrets:
#        - name: k8s-auth
  volumeClaimTemplates:
  - metadata:
      name: uptime-data
    spec:
      accessModes: ["ReadWriteOnce"]
      volumeMode: Filesystem
      resources:
        requests:
          storage: 2Gi
      storageClassName: nfs-nas
```

When I specified statefulset.apps/uptime to use uptime-kuma-test serviceAccount, the following error occurred

```
Data Dir: ./data/
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
(node:1) UnhandledPromiseRejectionWarning: Error: select * from `tag` where name = 'Ingress' limit 1 - SQLITE_ERROR: no such table: tag
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```


Can you send me your deployment file for reference?

**Comment by Richard87** [comment]
Yup, here is my Deployment:

```
(node:1) UnhandledPromiseRejectionWarning: Error: 
select * from `tag` where name = 'Ingress' limit 1 - SQLITE_ERROR: no such table: tag
```
This means that the database is not initialized... So you should start uptime-kuma first, before running this script, since I dont try to change or migrate the database :) 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: uptime-kuma
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  selector:
    matchLabels:
      component: uptime-kuma
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: uptime-kuma
    spec:
      serviceAccountName: uptime-kuma
      containers:
        - name: app
          image: richard87/uptime-kuma:ingress
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
            - name: IMPORT_ALL_INGRESSES
              value: "TRUE"
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /app/data
              name: storage
          livenessProbe:
            httpGet:
              path: /healthy
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthy
              port: 3001
              scheme: HTTP
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: uptime-kuma

```

**Comment by qingfengfenga** [comment]
Sorry, I used your yaml file to start uptime normally, and the Ingress information can be obtained normally by executing the script, but the data insertion failed.

I think I need to do more testing

Thank you very much for your work

```
root@uptime-kuma-5bb49f788b-2gl2w:/app# node extra/map-ingress.js
Data Dir: ./data/
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
(node:41) UnhandledPromiseRejectionWarning: Error: insert into `monitor` (`accepted_statuscodes_json`, `dns_resolve_server`, `dns_resolve_type`, `ignore_tls`, `interval`, `maxredirects`, `maxretries`, `method`, `name`, `retry_interval`, `type`, `upside_down`, `url`, `user_id`) values ('["200-299"]', '1.1.1.1', 'A', false, '60', 10, 0, 'GET', 'rancher.xxx.com', '60', 'http', false, 'https://rancher.xxx.com', 1) - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:41) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Richard87** [comment]
Hehe, definitly more documentation!

I insert the monitor as UserID 1 by default, but if that user doesnt exist/have been created yet, you would get that error :)

So make sure uptime-kuma is running, log in and complete the stup, then exec in to the running container to get a shell, and execute `node extra/map-ingress.js`, when it complets stop the container (by deleting the Pod, and let kubernetes start it back up again!)

This would work way better if tightly integrated in the code as a job or similar, but as it is, it requires a specific procedure to make it work :) 

Also, instead of using environment variables, it also supports command line arguments:
```
--kubernetes=https://kubernetes.default
--importAllIngresses=false
--ingressNamespaces
--monitorInterval=60
--kubernetesTokenFile=/run/secrets/kubernetes.io/serviceaccount/token
--kubernetesToken
--ownerId=1
```

**Comment by qingfengfenga** [comment]
I think it is possible to use the Sidecar mode and add an auxiliary container to complete these tasks, so that there is no need to restart the service every time.

I will do more attempts, thank you very much for providing these documentation

**Comment by Richard87** [comment]
Unfortunatly not, because we can't tell UptimeKuma to refresh the list of monitors, only a restart, or using the regular API will do that

**Pull request closed without merging**
