### PR TITLE
Max ESLint warnings 0

### PR DESCRIPTION
**Pull request by Saibamen**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

1. Add new script lint:prod with --max-warnings 0 option and use it in all GitHub Actions
    1. See article and comments from here: https://dev.to/thawkin3/eslint-warnings-are-an-anti-pattern-33np
    1. **TLDR & my point of view**: I can live with warnings during development, but all errors and warnings should be fixed before merging code into branch and no new version should be published before fixing warnings.
1. New ESLint rule: [template-curly-spacing](https://eslint.org/docs/latest/rules/template-curly-spacing)
    1. This will also fix `lint-fix:js` script for [prefer-template](https://eslint.org/docs/latest/rules/prefer-template) rule (not enabled)
1. Update workflows

Related: https://github.com/louislam/uptime-kuma/pull/4132

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Review by Zaid-maker — COMMENTED** [review]
v4 of checkout comes with Node.js 20 and npm 10 and we have issue with runs are failing and also we support multiple version of node.js.

and for the lint warning u fixed i already open a pr for it #4155 , actually it's a bug fix so i decided to do in it !

**Comment by Saibamen** [comment]
Version of NodeJS was not changed:

image

NodeJS 20 is used internally for checkout action

**Comment by Zaid-maker** [comment]
> [De](/louislam/uptime-kuma/actions/runs/7070641220/job/19247540901?pr=4158)

The tests passed because we install v9 of npm before installing dependencies, That's why Louis decided to use v9 of npm in runs.

image

**Comment by Zaid-maker** [comment]
> > [De](/louislam/uptime-kuma/actions/runs/7070641220/job/19247540901?pr=4158)
> 
> The tests passed because we install v9 of npm before installing dependencies, That's why Louis decided to use v9 of npm in runs.
> 
> image



> Version of NodeJS was not changed:
> 
> image
> 
> NodeJS 20 is used internally for checkout action
> 
> > we have issue with runs are failing
> 
> Where? All checks are green in this PR:
> 
> image

The tests passed because we install v9 of npm before installing dependencies, That's why Louis decided to use v9 of npm in runs.

image

**Comment by Zaid-maker** [comment]
But i appreciated your work on adding scripts for lint 😄

**Comment by Zaid-maker** [comment]
> I don't quite get it, isn't no issue? Because all test cases are passed.

Ok it's all on Louis what he plans but you have revert the lint warning because my pr got merged and fixed the lint warning 😄

**Comment by Zaid-maker** [comment]
> I don't quite get it, isn't no issue? Because all test cases are passed.

Ok but he has to revert the lint warning commit because it's already fixed

**Comment by Saibamen** [comment]
Fixed merge conflicts

**Pull request merged**
