### PR TITLE
change pause number color

### LINKED ISSUE #2731: Change paused number on /dashboard URL to a color
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Change paused number on /dashboard URL to a color that grabs the attention but not like red to show that it's offline.

Maybe an orange or similar.

Sometimes I pause a monitor to do maintenance but then I forget to resume it. This would help me see I have paused monitors. The grey color is very easy to gloss over.

### ✔️ Solution

Change paused number on /dashboard URL to a color

### ❓ Alternatives

N/A

### 📝 Additional Context

N/A

### PR DESCRIPTION
**Pull request by MohitBansal321**
Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #2731 

## Type of change
I make the new class for pause number  to change the color of it
and it is done according to the style pattern of the code
add class to app.scss
add variable of pause color to var.scss
add class to pause number of DashboardHome.vue

Please delete any options that are not relevant.

- User interface (UI)
- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by MohitBansal321** [comment]
@louislam please check and merge the updates

**Comment by Computroniks** [comment]
A screenshot of the change could be helpful to get and indication of what it looks like.

**Comment by MohitBansal321** [comment]
> A screenshot of the change could be helpful to get and indication of what it looks like.
backend server is not working from my side so i can't share any screen shot

**Comment by MohitBansal321** [comment]
> A screenshot of the change could be helpful to get and indication of what it looks like.

Screenshot 2023-02-14 000335

**Comment by Computroniks** [comment]
I would argue that unknown should be orange and paused should remain grey. Orange indicates some sort of issue that requires attention but is not urgent, or something that could become urgent if it is not seen to, a category that unknown seems to fit. Paused doesn't seem to fit this description and I think it is fairly common in web interfaces to have a paused / disabled feature greyed out.

**Comment by MohitBansal321** [comment]
> I would argue that unknown should be orange and paused should remain grey. Orange indicates some sort of issue that requires attention but is not urgent, or something that could become urgent if it is not seen to, a category that unknown seems to fit. Paused doesn't seem to fit this description and I think it is fairly common in web interfaces to have a paused / disabled feature greyed out.

Okay I will do changes for unknown as you mention

**Review by Computroniks — APPROVED** [review]

**Comment by chakflying** [comment]
Hmm then this isn't doing what the title says, and doesn't actually solve the original issue. 😂 IIRC Unknown only happens if the monitor has just started but doesn't have the first beat yet, which is also something normally users don't need to worry about.

**Comment by Computroniks** [comment]
Yeah, I am not sure a change is really needed here. It was more just if we wanted to have a different colour for each of the numbers, unknown should be the one that got changed not the paused monitors one, at least if the colour it was going to be changed to was orange.

**Comment by Justinzobel** [comment]
I'm not fussed on the specific colour. I just want to be able to more easily see ones that are paused.

**Comment by MohitBansal321** [comment]
Need any changes @Computroniks @Justinzobel

**Comment by Justinzobel** [comment]
This doesn't seem to change the pause colour at all, so it is irrelevant to me.

**Comment by MohitBansal321** [comment]
But @Computroniks need to change in unknown rather then pause so I will do in that way

**Comment by Computroniks** [comment]
> But @Computroniks need to change in unknown rather then pause so I will do in that way

I think making the paused number orange was a bit strange and that if anything was to be orange it should be the unknown number. A different colour could be more appropriate for paused monitors

**Comment by MohitBansal321** [comment]
> > But @Computroniks need to change in unknown rather then pause so I will do in that way
> 
> I think making the paused number orange was a bit strange and that if anything was to be orange it should be the unknown number. A different colour could be more appropriate for paused monitors

Let me know which color did you want I will update it

**Comment by MohitBansal321** [comment]
Now I think it is fine @Computroniks @Justinzobel

**Comment by MohitBansal321** [comment]
> It didn't solve the original issue 🤷‍♂️

Let me know your requirement for solving original issue

**Pull request closed without merging**
