### PR TITLE
Changed the color of delete button in dashboard from red to grey

### PR DESCRIPTION
**Pull request by iamabhshk**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description
Changed the color of the delete button in dashboard from red to grey as per the requirement. Just replaced class name from 'btn-danger' to 'btn-secondary' to achieve the changes.
@louislam 

## Type of change
- User interface (UI)
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] My changes generates no new warnings

## Screenshots

Screenshot 2024-01-03 at 12 14 36

### CODE REVIEW

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
As noted by nelson in https://github.com/louislam/uptime-kuma/issues/4290#issuecomment-1873938418 or by me in https://github.com/louislam/uptime-kuma/issues/4290#issuecomment-1874121477:
Changing this to be gray does not solve what we want to convey.
Please either
- hide it in an overflow menu
- or (prefered by me, idk about @chakflying / @louislam ) make this button into a secondary button in style only, not color.

Please also include a screenshot of the change you did.

**Comment by Zaid-maker** [comment]
What's the point of changing it to grey in the first place? Red means danger and it is correct color for delete

**Comment by Zandor300** [comment]
A suggestion:

`btn btn-normal text-danger`

Screenshot 2024-01-03 at 12 14 36

**Comment by Zaid-maker** [comment]
> A suggestion:
> 
> `btn btn-normal text-danger`
> 
> Screenshot 2024-01-03 at 12 14 36

yes this looks good

**Review by CommanderStorm — APPROVED** [review]

**Comment by iamabhshk** [comment]
Thanks for the opportunity team  :)

**Comment by ZachFabin** [comment]
@CommanderStorm Why did we remove the red?   "red to grey as per the requirement" - I must be missing something; what requirement?

Thanks for your time.

**Comment by CommanderStorm** [comment]
@ZachFabin Please see https://github.com/louislam/uptime-kuma/issues/4290 why we did the change.

**Pull request merged**
