### PR TITLE
Update zh-CN translations

### PR DESCRIPTION
**Pull request by deluxghost**
# Description

主要是统一用词和格式

## Type of change

- Translation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by deluxghost** [comment]
@louislam @AnnAngela I have already resolved. Mention me if you think any translation is wrong.

**Comment by louislam** [comment]
@AnnAngela @deluxghost Thank you so much!

**Comment by AnnAngela** [comment]
@louislam @deluxghost In https://github.com/louislam/uptime-kuma/blob/7bc8c447cd05449e7808b59c455b3b0d50b9d684/src/languages/zh-CN.js#L16 , the typo metioned in the review above hasn't been addressed.

**Comment by deluxghost** [comment]
@AnnAngela Thanks, since this PR is merged, I fixed it in #1350

**Pull request merged**
