### PR TITLE
fix(ci): Fix for the Actions failing on Windows Runner

### PR DESCRIPTION
**Pull request by Zaid-maker**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

~Adds a `--force` flag which fixes CI failing [source](https://stackoverflow.com/questions/39293636/npm-err-error-eperm-operation-not-permitted-rename)~

Seems like there is node-gyp issue due to drop of support of Node 14 which is preventing the CI to install global NPM version, ~removing the `npm i -g npm@9` fix the ci and seems OK~ Bumping to Node 16 fixes the issue

Tested the same method on my Repo CI it seems to run OK not the issue with NPM or Actions, i cannot figure out the issue.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by chakflying** [comment]
I wonder if there is a way to avoid having to touch the global npm version.

**Comment by Zaid-maker** [comment]
> I wonder if there is a way to avoid having to touch the global npm version.

I guess we have to remove the `npm i -g npm@9` step that's the only fix

**Comment by CommanderStorm** [comment]
> I wonder if there is a way to avoid having to touch the global npm version

npm versions dependent on the node version.
While this [may be changing with corepack](https://socket.dev/blog/node-community-debates-enabling-corepack-unbundling-npm), I see this somewhat unlikely. 

Do you have a clue why this was added?

- `npm@latest` -> `npm@9` in https://github.com/louislam/uptime-kuma/pull/3670
- Added in https://github.com/louislam/uptime-kuma/pull/3326

Having a look at the [node-gyp-releasees](https://github.com/nodejs/node-gyp/releases), they have dropped node 14.
Could bumping to node 16 solve this issue?

**Comment by Zaid-maker** [comment]
We could see by upgrading to Node 16 for testing if everything goes correct then we should adopt that

**Comment by Zaid-maker** [comment]
So this change can stay?

**Comment by CommanderStorm** [comment]
As you noted above both
- dropping `npm i -g npm@9` and
- bumping node to `v16` works for resolving this issue.

I would vote for changing the node version to >=v16.
The rationale is that we will have to do that anyway due to https://github.com/louislam/uptime-kuma/issues/4414
@chakflying @louislam any objections?

Another option would be bumping node to >=v18, which would allow for bugfixes like [`croner@8.0.0`](https://github.com/Hexagon/croner/releases/tag/8.0.0) for [AKDT timezones](https://www.timeanddate.de/zeitzonen/weltweit/akdt) not triggering.
I don't know how our decision in https://github.com/louislam/uptime-kuma/pull/3747 figures into this.

However, bumping to node >= v16 this requires more files to be changed:
- see https://github.com/louislam/uptime-kuma/pull/3747 and
- our [wiki needs to be slightly updated](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-non-docker)

**Comment by chakflying** [comment]
I have no objection to moving to >=16.

But also, it's a bit funny that a failing CI on Windows is the last straw on the camel's back for dropping 14.

**Comment by Zaid-maker** [comment]
Only bumping to Node 16 resolves this issue, the `npm i -g npm@9` still there.

And maybe we can keep open this and wait for 2.0.x release and give a instructions on release we drop 14, 16..etc and here's the guide on how to upgrade which i think make a significant improvement in Security and other aspects.

**Comment by louislam** [comment]
Um... Maybe I have to rethink to drop Node.js 14 and 16 in 2.0.0, because these weird issues I believe will eventually happen again and again.

I just feel Node.js' LTS versions are somehow too short. 18 is going to reach eol next year.

**Comment by Zaid-maker** [comment]
> I just feel Node.js' LTS versions are somehow too short. 18 is going to reach eol next year.

yes you are right 

image

**Comment by chakflying** [comment]
Can we have an interim fix by dropping `npm i -g npm@9` such that CIs can be passing again?

**Comment by Zaid-maker** [comment]
> Can we have an interim fix by dropping `npm i -g npm@9` such that CIs can be passing again?

Yes but on windows runner needs to be on node 16 other runners works fine.

**Comment by chakflying** [comment]
If this is the only way to get it working then we should adopt it, and merge to master ASAP. I don't think we should get use to CI checks failing on PRs and commits.

**Comment by Zaid-maker** [comment]
> If this is the only way to get it working then we should adopt it, and merge to master ASAP. I don't think we should get use to CI checks failing on PRs and commits.

Yup you are right.

**Comment by CommanderStorm** [comment]
> Maybe I have to rethink to drop Node.js 14 and 16 in 2.0.0

I think we should merge https://github.com/louislam/uptime-kuma/pull/3747/ instead.
I have updated said PR to make it mergable into master

**Comment by chakflying** [comment]
My perspective is that fixing the CI should have a higher priority than the discussion of dropping v14/16. But if #3747 is functionally equivalent except the documentation change, I'm willing to go with that instead.

**Pull request merged**
