### PR TITLE
FEAT: PUSHY Notifier

### PR DESCRIPTION
**Pull request by philippdormann**
adds support for [PUSHY](https://pushy.me) Notifier

### CODE REVIEW

**Comment by louislam** [comment]
Thanks, I know there are only two file changes at the end, but I think there are too many commits which will mess up my git log. I don't know to merge. 🙉

**Comment by philippdormann** [comment]
yeah 😄 I'm not sure either
I'll have a look later and will mark this PR as "ready for review" when the commits are cleaned up 😉

**Comment by Saibamen** [comment]
@louislam: Just click `Squash and merge`

https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request-on-github

**Comment by philippdormann** [comment]
cool, thanks @Saibamen 👍

**Comment by louislam** [comment]
> @louislam: Just click `Squash and merge`
> 
> https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request-on-github

Nice! @philippdormann It's OK. @Saibamen provided a solution for that.

**Comment by louislam** [comment]
image

Ar... Wait, still 74 commits, lol

**Comment by philippdormann** [comment]
yeah, that's fine. "Squash and merge" will combine them into 1

**Comment by Saibamen** [comment]
Just click on it :D

**Comment by louislam** [comment]
It worked! Thanks.

**Pull request merged**
