### PR TITLE
Feat  Add MySQL/MariaDB monitor #1817

### LINKED ISSUE #1817: Add support for monitoring MySQL/MariaDB databases
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

[PR1430 ](https://github.com/louislam/uptime-kuma/issues/1430) has just added the ability to monitor MS SQL Server DB's.

It would be good to also be able to monitor other popular DBs too - specifically MySQL/MariaDB which many people use.

### ✔️ Solution

Replicate the setup for MS SQL server, but with different connection methods and parameters to connect and test MySQL/MariaDB

### ❓ Alternatives

Currently doing a TCP Port test, but this only checks if the port is open, not whether a DB is actually available on that port and functioning.

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Computroniks**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

This PR adds support for monitoring MySQL and MariaDB servers in a similar way to the pre-existing monitors for SQL Server and PostgreSQL. The mysql2 package was choosen over mysql as it provides a promise wrapper and is reportedly faster than the original mysql package whilst still maintaining the same API. 

It also appears that SQL Server causes some confusion among users as they believe that it means any SQL database, not the Microsoft product SQL Server. To avoid this issue, the display value has been changed to Microsoft SQL Server. No backend changes have been made and it is still stored as sqlserver in the database. This is only a frontent change.

Fixes #1817 

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by petittitouan** [comment]
Tested successfully with :
- MySQL v8.0.30
- MariaDB v10.9.3-MariaDB-1:10.9.3+maria~ubu2204

Docker Desktop on Windows
Tests done with Uptime Kuma Docker pr-test
Official MySQL and MariaDB Docker Images

Containers started with : 
- MySQL : `docker run --name some-mysql -p 3306:3306 --rm -e MYSQL_ROOT_PASSWORD=strongPassword -e MYSQL_DATABASE=testDB -e MYSQL_USER=testUser -e MYSQL_PASSWORD=testPassword mysql`

- MariaDB : `docker run --name some-mariadb -p 3307:3306 --rm -e MYSQL_ROOT_PASSWORD=strongPassword -e MYSQL_DATABASE=testDB -e MYSQL_USER=testUser -e MYSQL_PASSWORD=testPassword mariadb`

Uptime Kuma connection string : 
- MySQL : `mysql://testUser:testPassword@host.docker.internal:3306/testDB`
- MariaDB : `mysql://testUser:testPassword@host.docker.internal:3307/testDB`

Uptime Kuma Query : `SELECT 1+1;`

**Comment by mhkarimi1383** [comment]
Why not just making it working with all SQL Based Servers?

**Comment by Computroniks** [comment]
Each database server requires a different node module to interact with. This means that an implementation must be made for all different types of SQL server as they all do things slightly differently.

**Comment by mhkarimi1383** [comment]
for that we could make some optional dependencies and adding a description about SQL Database Monitors
with that we have one Monitor type and no need to develop more for them
also adding separated packages for each SQL DB type can make uptime kuma big in size

**Comment by Computroniks** [comment]
> for that we could make some optional dependencies and adding a description about SQL Database Monitors with that we have one Monitor type and no need to develop more for them also adding separated packages for each SQL DB type can make uptime kuma big in size

We don't really have a choice in the matter. Each DB reqiures a different package. If we want to support the DB, we have to have the package. And each package implements a different interface which means each one needs to be developed seperatly.

In the grand scheme of things, given the number of DBs that we are likely to end up supporting (not that many), it will not really make a big difference to the size of the project. I did think about reorganizing the UI so that you had one selection for Databases and then another for which type, but that would have most likely been a breaking change due to changes in how the data would be stored resulting in the need for migrations.

**Comment by averycooke** [comment]
Has anyone soak tested this? 

From my testing, it appears that this is not closing connections, or at least not closing them promptly. 
Within 2 hours, I got "Too many connections" error. My monitoring account has a limited number of connections, ~120.

I've made local changes to close the connection after query, and have not had a problem for 5 hours, even after increasing ping to once every 20 seconds. 

I'll update if I find some other explanation, but explicitly closing the connection (like the postgres and mssql monitors) might be  more correct. I saw code examples from mysql2 that also do not explicitly close connections, but from what I'm observing that may just be a documentation mistake.

**Comment by petittitouan** [comment]
> Within 2 hours, I got "Too many connections" error. My monitoring account has a limited number of connections, ~120.

I just tested it for a few checks just to see if it was working

**Comment by louislam** [comment]
@averycooke Thanks for testing, I think `connection.end()` is needed.

**Comment by Computroniks** [comment]
@averycooke Thanks for testing. I will add a finally block that closes the connection a bit like is done with the PostgreSQL monitor. 

I might also go create an issue/pr over in the module repo to update the docs to make it slightly clearer.

**Comment by ggishant** [comment]
This is an awesome feature! Looking forward to using it. By when will this be release to production?

**Pull request merged**
