### PR TITLE
Discussion for translation work

### PR DESCRIPTION
**Pull request by AnnAngela**
While I was translating the website, I found some inadequacies:

1. In some times, the new UI components use strings directly rather than use translation function and lang file.
   - I think there should be a rule to force peoples to avoid using strings directly.
2. The `npm run update-language-files` will generate lang files for all languages, that will make 30+ files changed just like #1511.
   - I can indeed avoid modifying other lang files by copying lang file that I want to modify to notepad, but it's annoying.
   - I think using an external translation tool would be a better option.

Does anyone agree with me?

### CODE REVIEW

**Comment by gaby** [comment]
@AnnAngela Yeah, at this point it should be using one of those services that auto-translates to other languages instead of having 100+ PR's about minor language changes. 🤷‍♂️

**Comment by mathiskir** [comment]
I totally agree but are there good Tools for translation that are accurate?

**Comment by mathiskir** [comment]
What would you use for translation?

**Comment by louislam** [comment]
At least in my language, most auto translation tools are never accurate, especially for a single words that are having several meanings such as `running`. Google Translate actually translate into `(A man is running)`.

So translations must be done by human in my opinion. I would prefer displaying English words rather than misleading words.

**Comment by louislam** [comment]
But I agree we should have a better translation platform.

I checked vue-i18n website, they suggested [Localazy](https://localazy.com/). 

I have no experience with these tools, so if you have better alternatives, feel free to comment here.

**Comment by MarcHagen** [comment]
https://github.com/louislam/uptime-kuma/pull/597 is already a huge improvement and could be a nice step to the right direction.
But shortly after that one, a translation website would be so much nicer.

I dont know Localazy, but lokalise.com i know very well, and is used by bigger communities 
https://lokalise.com/blog/vue-i18n/

**Comment by MarcHagen** [comment]
Just maybe as an fyi, another opensource project has a interasting way in using languages and scripts how to manage them.
https://github.com/umami-software/umami

**Comment by AnnAngela** [comment]
There is another issue that we cannot keep comments for i18n file since the generator script (`npm run update-language-files`) will delete whole files and regenerate one without any comments left.

**Comment by nogweii** [comment]
[Weblate](https://weblate.org/en/) seems really good, and is free for libre projects (like itself: https://github.com/WeblateOrg/weblate)

**Comment by louislam** [comment]
> [Weblate](https://weblate.org/en/) seems really good, and is free for libre projects (like itself: https://github.com/WeblateOrg/weblate)

The UI looks promising and it is selfhosted-able! Will try this one later. Thanks.

**Comment by AnnAngela** [comment]
> > [Weblate](https://weblate.org/en/) seems really good, and is free for libre projects (like itself: https://github.com/WeblateOrg/weblate)
> 
> The UI looks promising and it is selfhosted-able! Will try this one later. Thanks.

Also it seems to be able to support [GitHub authentication](https://docs.weblate.org/en/latest/admin/auth.html?highlight=SSO#github-authentication), so maybe you can directly controll that which guy on GitHub can change the i18n

**Comment by AnnAngela** [comment]
Sorry for clicking close button for mistake

**Comment by louislam** [comment]
Just installed Weblate. You can login through GitHub only, as I haven't setup smtp for sending activation email.

https://weblate.kuma.pet 

Trying to connect this repo. However, it seems that it cannot read our *.js language files. 😥

If anyone want to be an admin on my Weblate and help to setup, let me here.

**Comment by AnnAngela** [comment]
It seems to use the [translate-toolkit formats](https://docs.weblate.org/en/latest/formats.html#translation-types-capabilities) which don't includes javascript file. Maybe we should try [JSON](https://docs.weblate.org/en/latest/formats.html#json) ?

**Comment by YehowahLiu** [comment]
> It seems to use the [translate-toolkit formats](https://docs.weblate.org/en/latest/formats.html#translation-types-capabilities) which don't includes javascript file. Maybe we should try [JSON](https://docs.weblate.org/en/latest/formats.html#json) or use script to generate js files from JSON?

`vue-i18n` supports JSON format and is easy to migrate (tested in [this branch](https://github.com/YehowahLiu/uptime-kuma/tree/weblate)), so just replace the js files with JSON is ok.

**Comment by YehowahLiu** [comment]
> If anyone want to be an admin on my Weblate and help to setup, let me here.

I can have a try. I am not experienced on setting up weblate, but its Document is clear enough.

**Comment by YehowahLiu** [comment]
> If anyone want to be an admin on my Weblate and help to setup, let me here.

@louislam  I can have a try. I am not experienced on setting up weblate, but its documents is clear enough. And I have prepared an [branch](https://github.com/YehowahLiu/uptime-kuma/tree/weblate) that have converted the language files to .json, which would be useful.

**Comment by louislam** [comment]
> > If anyone want to be an admin on my Weblate and help to setup, let me here.
> 
> @louislam I can have a try. I am not experienced on setting up weblate, but its documents is clear enough. And I have prepared an [branch](https://github.com/YehowahLiu/uptime-kuma/tree/weblate) that have converted the language files to .json, which would be useful.

Thanks! Feel free to open a new pr.

**Comment by louislam** [comment]
Close and focus on #2611

**Pull request closed without merging**
