### PR TITLE
Update bg-BG.js

### PR DESCRIPTION
**Pull request by MrEddX**
# Description

Updated Bulgarian Translation

## Type of change

- Translation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it

### CODE REVIEW

**Review by gaby — COMMENTED** [review]
According to Google the current translation is correct.

It should say "Start" not "Start Up".

**Comment by gaby** [comment]
👎🏻 The text should be "Start", not "Start Up".

**Comment by MrEddX** [comment]
Appreciate the remark. However, in Bulgarian language, these commands use the imperative mood, in order to inflect a direct request /command/, while Google Translate is not capable to detect the grammar nuances  in meaning. If this translation update comment is meant for the below snip, kindly re-concider this pull request.
 
uptime-kuma-start-stop-cloudflared

**Comment by Computroniks** [comment]
When I paste `Стартирай` into google translate I end up with `Get started`, however when I try it in https://lingvanex.com/translation/english-to-bulgarian I get `start`. Interestingly, when `to start` is input as the English in both I get `започне`. Having absolutely no knowledge of Bulgarian and knowing that online translators are never quite correct, I would be inclined to go with what @MrEddX says and accept this PR.

**Pull request merged**
