### PR TITLE
Statistics on the status page

### LINKED ISSUE #1480: Have probe information in status pages
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

It would be great to be able to have more information in public version by clicking on a probe as in the dashboard

The ideal would be to be able to configure whether or not you want to display the details of the group of probes, and why not also add recent events if you decide to do so, but it is not mandatory

### ✔️ Solution

An accordion that opens at the click of a probe on a public page

image

### ❓ Alternatives

Have at least basic information such as response time, average response time, uptime

### 📝 Additional Context

Like UptimeRobot :)

### PR DESCRIPTION
**Pull request by karelkryda**
# Description

Fixes #1480

This PR adds the ability to display the PingChart and SSL info directly on the status page.

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by SelfhostedPro** [comment]
Hey, what else needs to be done on this? I can take a look soon and see about pushing this further along.

**Comment by karelkryda** [comment]
> Hey, what else needs to be done on this? I can take a look soon and see about pushing this further along.
> 

Howdy, 
truth be told, I was out for over 3 months and that's why I didn't do anything at all on this PR.
To tell the truth, I would like to finish my previous PRs first, but I am still waiting and PRs are slowly becoming obsolete against the main branch.

Thanks for your understanding

**Comment by x3rt** [comment]
Is this PR still being worked on?

**Comment by CommanderStorm** [comment]
> Is this PR still being worked on?

I think at this point this is doubtfull.
Given how much of the statisitics relevant codebase was changed in the upcoming v2-release I am going to close this PR.
If somebody wants to pick this up: for concrete implementation discussion, please open another PR according to our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)

**Pull request closed without merging**
