### PR TITLE
chore:Telegram notification-provider using the `throwGeneralAxiosError` helper

### PR DESCRIPTION
**Pull request by CommanderStorm**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

During https://github.com/louislam/uptime-kuma/pull/3620#discussion_r1299877166 I noticed that this notification provider does not stick to the pattern all other notification-providers use.

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

## Screenshots (if any)

before:
image

after:
image

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]

**Comment by Saibamen** [comment]
Please merge into 1.23.x branch

**Comment by louislam** [comment]
Please note that v1 will receive bug fixes only at this moment. Improvements like this and new features are not guaranteed to be in 1.23.X.

> Update: The last minor version (1.23.x) means that there won't be any new features introduced in v1. However, bug fixes will still be provided. You can expect to see 1.23.1, 1.23.2 and so on.

https://github.com/louislam/uptime-kuma/releases/tag/1.23.0

**Comment by Saibamen** [comment]
This is a small code change - I see this as a bug fix, not new feature

**Comment by CommanderStorm** [comment]
This is refactoring, as this just unifiest the odd one out of all the notifcation provider to also use the same error hadling logic.

 => neither a bugfix, nor a feature

**Pull request merged**
