### PR TITLE
fix(notification-dingding): throw error when failed

### PR DESCRIPTION
**Pull request by AnnAngela**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

See <https://github.com/louislam/uptime-kuma/pull/3573#issuecomment-1678029861>

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

https://github.com/louislam/uptime-kuma/pull/3598#issuecomment-1899523530

### CODE REVIEW

**Comment by AnnAngela** [comment]
See #3573

**Comment by CommanderStorm** [comment]
Have you tested that this works as intended?
Could you attach a screenshot as above of the monitor failing? (https://github.com/louislam/uptime-kuma/pull/3573#issue-1848985337) ^^

**Comment by AnnAngela** [comment]
> Have you tested that this works as intended?
> Could you attach a screenshot as above of the monitor failing? (https://github.com/louislam/uptime-kuma/pull/3573#issue-1848985337) ^^

OK, I will try to get the screenshot next Monday. (I'm on vacation.)

**Comment by CommanderStorm** [comment]
@AnnAngela ping ^^

**Comment by AnnAngela** [comment]
@CommanderStorm Sorry for late response, I forgot it :(

E1

**Comment by CommanderStorm** [comment]
@louislam FYI: I put this into the 1.23.12 milestone as I think this meets our requirements (only bugfixes) for said release and can be merged without more indepth reveiew as the "proof of working" we need is there ^^

**Pull request merged**
