### PR TITLE
Fix(notification-aliyun-sms): throw error when sending SMS failed

### PR DESCRIPTION
**Pull request by polunzh**
Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Throw error when sending Aliyun SMS failed, snapshot below.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by CommanderStorm** [comment]
I don't quite know why you opened an empty PR (what would you like to discuss?)

Currently the `alium-sms` notification provider checks for success like this:
https://github.com/louislam/uptime-kuma/blob/72741ebb10b7fb851b169f8def85bdde453e6054/server/notification-providers/aliyun-sms.js#L73-L76

**Comment by polunzh** [comment]
> I don't quite know why you opened an empty PR (what would you like to discuss?)
> 
> Currently the `alium-sms` notification provider checks for success like this:
> 
> https://github.com/louislam/uptime-kuma/blob/72741ebb10b7fb851b169f8def85bdde453e6054/server/notification-providers/aliyun-sms.js#L73-L76

Sorry, I updated the PR.

Original bugs:
- The method `this.sendSms()` is an `async` function, so it must be called with `await`, or it will always be true:
https://github.com/louislam/uptime-kuma/blob/72741ebb10b7fb851b169f8def85bdde453e6054/server/notification-providers/aliyun-sms.js#L21
- The method should throw error if response message is not `OK` instead of return `false`.

**Comment by CommanderStorm** [comment]
The same problem (not awaiting the success-determiner) is also be present in these other poviders due to other devs copying code:
- `DingDing`
- `FlashDuty`
- `PagerDuty`
- `PagerTree`
- `Splunk`

Could you add a fix for these as well?

**Comment by louislam** [comment]
> The same problem (not awaiting the success-determiner) is also be present in these other poviders due to other devs copying code:
> 
>     * `DingDing`
> 
>     * `FlashDuty`
> 
>     * `PagerDuty`
> 
>     * `PagerTree`
> 
>     * `Splunk`
> 
> 
> Could you attach a fix for these as well?
> 
> If you do, could you add `Resolves #3458` to the description?

Maybe do this in new pull request(s). Some of them are regional only notifications, I can't test the other normal cases. Since notification is an important feature in Uptime Kuma, it is required to find someone who actually can test it (up/down/test ok/test fail). Maybe we can reach back the og authors to test them.

**Comment by CommanderStorm** [comment]
While I don't agree that these changes require extra tests, let's ask the OG authors if they can duplicate+test these fixes across the other providers:

- `DingDing`: @AnnAngela @dingdayu
- `FlashDuty`: @guguji5
- `PagerDuty`: @MarcHagen
- `PagerTree`: @armiiller
- `Splunk`: @Joseph-Irving

Currently these monitors don't report erros at all (they always succeed).
Could each of you please add:
- an await statement to the function which your provider does not await
- throwing errors instead of returning `false` to make them appear in the frontend

and document that these are fixed by attaching a screenshot as above of the monitor failing?

**Comment by AnnAngela** [comment]
> While I don't agree that these changes require extra tests, let's ask the OG authors if they can duplicate+test these fixes across the other providers:
> 
> - `DingDing`: @AnnAngela @dingdayu
> - `FlashDuty`: @guguji5
> - `PagerDuty`: @MarcHagen
> - `PagerTree`: @armiiller
> - `Splunk`: @Joseph-Irving
> 
> Currently these monitors don't report erros at all (they always succeed).
> Could each of you please add:
> - an await statement to the function which your provider does not await
> - throwing errors instead of returning `false` to make them appear in the frontend
> 
> and document that these are fixed by attaching a screenshot as above of the monitor failing?

I am not the author of Dingding (I only changed the timezone setting of output message), but if @dingdayu don't have time, I can take a look at thursday.

**Comment by polunzh** [comment]
> The same problem (not awaiting the success-determiner) is also be present in these other poviders due to other devs copying code:
> 
> * `DingDing`
> * `FlashDuty`
> * `PagerDuty`
> * `PagerTree`
> * `Splunk`
> 
> Could you attach a fix for these as well?
> 
> If you do, could you add `Resolves #3458` to the description?

Sorry, I can't promise to fix all of these notification issues, but I'll take a look over the weekend if it hasn't been fixed yet.

**Comment by guguji5** [comment]
@CommanderStorm Sorry to see this issue so late, is there any problem to fix the `FlashDuty` channel ? or fixed

**Comment by AnnAngela** [comment]
@CommanderStorm @louislam I have make a pr #3598

**Pull request merged**
