### PR TITLE
Feat: New Notification Type for AlertNow

### PR DESCRIPTION
**Pull request by daeho-ro**
# Description

This will add the new notification type, AlertNow.
Also, I sort the notifications to make it more readable.

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

screenshot

### CODE REVIEW

**Comment by Computroniks** [comment]
Could you change the title of the commit to a more descriptive title as these commits are not empty.

**Comment by daeho-ro** [comment]
> Could you change the title of the commit to a more descriptive title as these commits are not empty.

As you wish.

**Comment by louislam** [comment]
Thanks for the pr.

 Please do not re-order the imports, as it is hard to review.

**Review by Computroniks — APPROVED** [review]
The notification provider looks good and I have gone through to make sure that none of the imports were lost when they were put in alphabetical order

**Comment by daeho-ro** [comment]
If it is required to revert, I will do that for the imports. I have used the sort function on the vscode, so all the imports will be there but understand that the pr is now hard to merge.

**Comment by louislam** [comment]
Since @Computroniks cross-checked the changes, it is OK to keep.

Thank you all for the pr.

**Pull request merged**
