### PR TITLE
Custom status page

### PR DESCRIPTION
**Pull request by patrickhafner**
# Description

Customize button for

- custom CSS
- custom powered by footer (text only)

## Screenshots (if any)

Bildschirmfoto 2021-12-21 um 03 20 55
Bildschirmfoto 2021-12-21 um 03 34 11

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
Its good but it's better if it accept custom html code for example I want to put link in the text of the description

**Comment by patrickhafner** [comment]
> Its good but it's better if it accept custom html code for example I want to put link in the text of the description

Thanks for your feedback, footer field now supports HTML input. 

Merry Christmas! 🎄

**Comment by louislam** [comment]
I am re-structing the internal logic of status page, it should be after #863.

**Comment by mathiskir** [comment]
Would love to have this in uptime kuma!!

**Comment by louislam** [comment]
The powerBy text should not be changed, but I will add a option to show/hide the text later.

TODO
- [ ] [Database] Add new field in `status_page` table: `css`
- [ ] [Backend] Insert into table
- [ ] [Frontend] Move css field to sidebar

**Pull request merged**
