### PR TITLE
🐛 fix: boolean fields in kafka producer monitor

### LINKED ISSUE #3760: Monitor Kafka Producer Enable Kafka SSL disabled after checking box and saving
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

when adding a new monitor type for kafka producer, there is an option to enable kafka ssl,  when checking the box to enable kafka ssl when I click on save the check box is unchecked.

### 👟 Reproduction steps

add new monitor fill out following

friendly name
kafka brokers
kafka topic anme
kafka producer message
check enable kafka SSL
leave the Kafka SASL option to none

then save and the enable kafka SSL check box is unchecked

### 👀 Expected behavior

when checking the enable kafka ssl that the check box stays checked no matter what

### 😓 Actual Behavior

when checking the enable kafka ssl and saving the check box becomes unchecked after saving.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

docker

### 🌐 Browser

MS Edge 110.1587.41

### 🐋 Docker Version

k8s 1.27

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mhkarimi1383**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fix field types in database and converting it to boolean just like other boolean fields

newly added migrations should be okay since we where storing data in `0` and `1`

Fixes #3760

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
@louislam 
IDK if I had to add migrations in knex or old ones since it's a patch for an older bug and I don't know if it will get released before v2 release or not

**Comment by chakflying** [comment]
Please remove formatting changes unrelated to this PR in `monitor.js`.

**Comment by louislam** [comment]
Bug fix can be in 1.23.X.

But since this pr is touching 2.0.0's code, I am afraid that it cannot be simply rebased into the 1.23.X branch automatically.

If you want this bug fix in 1.23.X, feel free to create a new pr which is based on this branch: 
https://github.com/louislam/uptime-kuma/tree/1.23.X

**Comment by mhkarimi1383** [comment]
Closing this in flavor of #3949

**Pull request closed without merging**
