### PR TITLE
Feat: Save and restore chart period

### PR DESCRIPTION
**Pull request by chakflying**
# Description

Add simple function to save and restore the chart period option per monitor.

## Type of change

Please delete options that are not relevant.

- User Interface
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and test it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]

**Comment by louislam** [comment]
Since 24h or 1w period is a bit slow, it may affect the user experience when a user try to switch monitor pages.

**Comment by chakflying** [comment]
Good point. Do you think saving a max of 6 hours would be okay?

**Comment by chakflying** [comment]
Thinking about this, maybe we should add a processing stage for the longer time frames where it would group the responses in an interval and return the median / maxmin. The chart can't display that much detail anyway unless we implement zooming.

**Comment by louislam** [comment]
Yes, ultimately, it should resample all data. The idea is similar to #1458

> Do you think saving a max of 6 hours would be okay?

The performance is acceptable for 6 hours.

**Pull request merged**
