### PR TITLE
New Monitor for OracleDB

### PR DESCRIPTION
**Pull request by bitsky6**
add oracledb

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by bitsky6** [comment]
Added oracledb for monitoring.

**Comment by Computroniks** [comment]
I think you might have forgotten to commit a file, only 8 lines are changed and there is a reference to an undefined function, could you also fix the linting issues

**Comment by louislam** [comment]
You meant to add a new montior for oracle database right? Please change the title.

It seems that it is not ready yet. I changed to draft first. Please press `Ready for review` once it is ready.

**Comment by bitsky6** [comment]
I have made another as did it over VScode somehow couldnt edit here so closed it.
I have opened another pushed with VS code.
Sorry.

**Pull request closed without merging**
