### PR TITLE
Dockerfile based on ubuntu

### PR DESCRIPTION
**Pull request by Colgaton**
I created a quick and dirty ubuntu based docker file. It works fine on my system and might be helpful for people willing to try it.

### CODE REVIEW

**Comment by rezzorix** [comment]
May I ask why?
A container should be as small, simple and secure as possible. 
Alpine Linux provides all what is needed to run the app in a container and fulfills all mentioned in the first sentence.
Ubuntu uses more data and provides complexity that isn't required... so again... why?

**Comment by louislam** [comment]
Sorry, I think I don't want to maintain two dockerfile files in the future.🤣

**Comment by Colgaton** [comment]
> 
> 
> May I ask why?
> A container should be as small, simple and secure as possible.
> Alpine Linux provides all what is needed to run the app in a container and fulfills all mentioned in the first sentence.
> Ubuntu uses more data and provides complexity that isn't required... so again... why?

Both works, you might want to use what suits you better or you're used to. While ubuntu might be bigger, I don't believe it is less secure or adds complexity.

**Comment by rezzorix** [comment]
Ok, not sure if we should continue with this conversation, just wanted to make sure we are on the same page:

Ubuntu: ~43MB compressed on Docker hub
Alpine: ~3MB compressed on Docker hub

The distro in the container just has to meet the requirements to running the app you want to containerize.

So why would anyone go with 10x more data than actually needed?

Aside from the app itself - why would you run anything else in the container?
Is there a need do enter the container for anything other than checking the logs or making slight adjustments?
A log check or vi/vim/nano is everywhere the same...

And for every other bigger requirement: just run a separate container...

**Comment by louislam** [comment]
> Ok, not sure if we should continue with this conversation, just wanted to make sure we are on the same page:
> 
> Ubuntu: ~43MB compressed on Docker hub
> Alpine: ~3MB compressed on Docker hub
> 
> The distro in the container just has to meet the requirements to running the app you want to containerize.
> 
> So why would anyone go with 10x more data than actually needed?
> 
> Aside from the app itself - why would you run anything else in the container?
> Is there a need do enter the container for anything other than checking the logs or making slight adjustments?
> A log check or vi/vim/nano is everywhere the same...
> 
> And for every other bigger requirement: just run a separate container...

I think a lot of people is familiar with Ubuntu commands such as apt-get rather than alpine. It is good for those users if they want to add something along with Uptime Kuma.

But as a maintainer, I just lazy to maintain two dockerfile files, lol.

**Pull request closed without merging**
