### PR TITLE
Added the option for Monitoring OracleDB

### LINKED ISSUE #2493: Add Oracle as a new monitor
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Having Oracle as a new Specific Monitor Type so i can monitor also Oracle db servers.

### ✔️ Solution

Testing connection of Oracle database servers.

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bitsky6**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #2493

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by bitsky6** [comment]
I have added monitoring for OracleDB

**Comment by Computroniks** [comment]
Some of this code looks to have been copied from @simone80an from comment https://github.com/louislam/uptime-kuma/issues/2493#issuecomment-1434854227

Do you have their permission to create this PR?

**Comment by simone80an** [comment]
> Some of this code looks to have been copied from @simone80an from comment [#2493 (comment)](https://github.com/louislam/uptime-kuma/issues/2493#issuecomment-1434854227)
>
> Do you have their permission to create this PR?

Yes permission given to @bitsky6 for the pull request.

**Comment by bitsky6** [comment]
I wrote will push it. Indeed it is from him.

**Comment by Computroniks** [comment]
@bitsky6 Can you fix the linting issues

**Comment by bitsky6** [comment]
Thanks @simone80an

**Comment by Computroniks** [comment]
You will also need to commit package.json and package-lock.json

**Comment by bitsky6** [comment]
Thanks all looking good now.

**Comment by chakflying** [comment]
Ref #2646, IMO long placeholders should be avoided and instead use a `form-text` below like the other fields with a description.

**Comment by louislam** [comment]
I recently fixed some bugs of postgres, mongodb and mssql that could crash Uptime Kuma. Here are some test cases that should be aware of:
- Invalid connection string
- Not resolvable hostname
- Unreachable IP
- Reachable hostname and port, but it is a web server  (e.g. uptime.kuma.pet 443)
- Invalid auth
- Invalid SQL
- Empty SQL

**Comment by simone80an** [comment]
> 

Have done all tests listed and checked Uptime Kuma didn't crashed.

**Comment by louislam** [comment]
Wait, I just checked out and didn't find OracleDB in list and noticed that it is not even added in dropdown. Did you actually test it?

1. Do we need an extra program in order to use this monitor? 
 If yes, this pr will be more complicated:
     a. If the user is not installed the program, this monitor type should not be able to choose.
     b. For docker users, I feel it is eventually no way to use?
image


4. Is the connection string really like that? I don't know why but it looks weird.
image

Remarks for testing:
`docker run --rm -it -p 1521:1521 -e ORACLE_PWD=test123 gvenzl/oracle-xe:21-slim`

**Comment by louislam** [comment]
I also found that `npm install` error on Linux arm64/armv7.

Please refer to the project styles, native build on the fly is not allowed:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#project-styles

So if you want this pr to get merged, you need to:
1. Extra native `node-oracledb` builds for linux armv7/arm64. Alternatively you can find another oracledb node package. As long as `npm install` won't throw error.
2. Oracle Database Monitor is hidden for Docker users and also hidden for someone who don't have Oracle Instant Client.

**Comment by bitsky6** [comment]
I am running without a problem with docker for some time.
I have added some comments for the steps I am using and removed what was not needed for me from the original.

# First stage: build the Oracle Instant Client libraries
FROM ghcr.io/oracle/oraclelinux8-instantclient:21 AS base

# Second stage: build the main image
FROM node:16-buster-slim

# Set the target platform (useful for cross-compiling)
ARG TARGETPLATFORM=linux/amd64

# Set the working directory
WORKDIR /app

# Install necessary packages
RUN apt-get update && \
    apt-get --yes --no-install-recommends install libaio1 dumb-init nano net-tools&& \
    rm -rf /var/lib/apt/lists/*

# Copy Oracle Instant Client libraries from the base image
COPY --from=base /usr/lib/oracle /usr/lib/oracle
COPY --from=base /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf

# Update dynamic linker configuration
RUN ldconfig

# Set environment variables for Oracle client
ENV ORACLE_HOME=/usr/lib/oracle/21/client64
ENV LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib:/usr/local/lib
ENV TNS_ADMIN=$ORACLE_HOME/network/admin
ENV PATH=$PATH:$ORACLE_HOME/bin

# Install Node.js dependencies
COPY package.json package-lock.json ./
RUN npm ci --include=dev

# Copy the rest of the application files
COPY . .

# Build
RUN npm run build

# Expose port and volume
EXPOSE 3001
VOLUME ["/app/data"]

# Set the entrypoint
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "server/server.js"]

**Comment by louislam** [comment]
> After the @bitsky6 tests with Docker under Linux which i thanks so there are any chances to see this branch merged in the master? Thanks.

Unlikely, it is still broken the installation for non-Docker (armv7/arm64) users as I mentioned in the previous comment. And using a binary file from Oracle Linux on Debian based sounds too hacky in my opinion. 


Alternatively, I think maybe implementing an agent would be a better solution if the cpu arch issue is unable to solve.

`Uptime Kuma` <-> `Agent` <-> `Oracle DB`

`Agent` = An HTTP Server with an entrypoint that allows make a request with a connection string and a query
`Uptime Kuma` = Make a http request to the `Agent`

**Comment by simone80an** [comment]
Any news about that?
Unfortunately i haven't enough knowledge for the alternative proposed by @louislam (implementing an agent that will communicate between Uptime Kuma and Oracle DB.

**Comment by CommanderStorm** [comment]
I am going to close this issue as support for non-Docker (armv7/arm64) users without native dependencys is a hard requirement for monitors in uptime kuma.
If oracle changes their mind and offers a package which does not require this, we can reopen this issue.
We would like to have such a monitor, but are not willing to accept the current drawbacks this would incurr.

As it stands, I don't see how keeping this issue open and hoping that oracle changes their mind will get anywhere.

If somebody developes an agent, we can include this in the [unoffical/experimental section of our installaiton guide](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#unofficial--experimental).

**Comment by sitiom** [comment]
As of https://github.com/oracle/node-oracledb/releases/tag/v6.0.0:
> This version of node-oracledb is now a ‘Thin’ mode driver by default. The Thin mode is implemented purely in JavaScript and connects directly to Oracle Database. You can also enable a ‘Thick’ mode that will allow the optional use of Oracle client libraries with some additional functionality.

- https://github.com/louislam/uptime-kuma/pull/7156

**Pull request closed without merging**
