### PR TITLE
feat(server): add badge for overall status of status-page

### LINKED ISSUE #1616: Global Statuspage Badges
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

A global badge for each status page that briefly displays the "global" system status on that status page(e.g. All systems operational) to embed on an external website.

If this already exists, sorry, but I've only found badges for individual monitors so far.

### ✔️ Solution

No proposal

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sjoukedv**
# Description

Fixes #1616

Adds an API route `/api/status-page/:slug/badge` which shows the badge similar to the [overall status on the status page itself](https://github.com/louislam/uptime-kuma/blob/master/src/pages/StatusPage.vue#L198).

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

e.g. `/api/status-page/test/badge?label=<status-page>` returns the following:

- Up, 
- Down, 
- Degraded, 
- Maintenance, 

I wish badge-maker supported SVG as messages so that we can use the same font-awesome icon as the badge label

### CODE REVIEW

**Comment by chakflying** [comment]
I think you don't need to include the `yarn.lock` file.

**Comment by juzhiyuan** [comment]
The logic is clear to me 🙏

**Comment by sjoukedv** [comment]
> I think you don't need to include the `yarn.lock` file.

My bad that lockfile slipped in there.

**Comment by sjoukedv** [comment]
I removed the lockfile and added `yarn.lock` to `.gitignore` as you commited the npm lockfile in this repo

**Comment by sjoukedv** [comment]
@louislam can you review/merge this?

**Comment by louislam** [comment]
> @louislam can you review/merge this?

Thanks for the pr. Tested and it is working.

**Pull request merged**
