### PR TITLE
migrate timezones-list lib to @vvo/tzdb issue #4479

### LINKED ISSUE #4479: Migrate from `omsrivastava/timezones-list` to `vvo/tzdb`
### 📑 I have found these related issues/pull requests

none

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

[omsrivastava/timezones-list](https://github.com/omsrivastava/timezones-list), the library currently used by our front-end, is rarely updated and has [inaccuracies](https://github.com/omsrivastava/timezones-list/issues/14). 

[vvo/tzdb](https://github.com/vvo/tzdb) looks much better as it is automatically kept up-to-date with authoritative sources. 

Some migration work is needed since the data format is different.

### ✔️ Solution

Migrate from `omsrivastava/timezones-list` to `vvo/tzdb`

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by huzaifaazim0**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description
migrated timezones-list lib to @vvo/tzdb

Fixes #4479

## Type of change
non-breaking

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by chakflying** [comment]
I took a look at the `getTimezoneOffset()` function in the front-end, and and realized that we are currently using the native `Date` object to obtain the offset of a Timezone, whereas in the back-end we seem to be using `dayjs`. The original `timezones-list` is really just that, a list of timezones for the user to pick. I guess I'm not familiar enough with how these things work to know if it would cause issues.

The code change here looks simple enough, haven't the time to test it yet.

**Comment by huzaifaazim0** [comment]
Hello,
Yes you are correct, it's just a list.
Please test and let me know if other changes are needed.
Thanks.

**Review by chakflying — APPROVED** [review]
Tested working okay.

**Comment by huzaifaazim0** [comment]
Great, thanks
It was nice contributing to uptime-kuma
Looking forward to solving more issues

**Pull request merged**
