### PR TITLE
Better description for shrink database button

### PR DESCRIPTION
**Pull request by CommanderStorm**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

As discussed in https://github.com/louislam/uptime-kuma/issues/2470#issuecomment-1953725902

Previous description suggested that you need to recreate your database from scratch.
This PR is a rebase of PR https://github.com/louislam/uptime-kuma/pull/4508

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings

image

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]

**Comment by Saibamen** [comment]
@CommanderStorm @louislam: Why this wasn't merged into `1.23.X` branch and not goes into [1.23.14](https://github.com/louislam/uptime-kuma/releases/tag/1.23.14) release?

**Comment by CommanderStorm** [comment]
I moved this into v2.0 as changing the translations is something which weblate is a bit.. not robust with.

While translating with multiple branches might work, I'd rather not try weblate.
Merging conflicts is pretty painfull and not somethign that I can deal with. Only @louislam can fix these issues and I'd rather not waste his time with this.

Case in point, I broke weblate accidentally via this PR and how I handled merging 👀: https://github.com/louislam/uptime-kuma/pull/5072#issuecomment-2392591828

**Comment by Saibamen** [comment]
Maybe because we have really old Weblate?
Our version is `4.16.4`, but latest version is `5.7.2` https://github.com/WeblateOrg/weblate/releases

**Comment by louislam** [comment]
> Maybe because we have really old Weblate? Our version is `4.16.4`, but latest version is `5.7.2` https://github.com/WeblateOrg/weblate/releases FYI @louislam

Um.. I tried to upgrade to 4.18 last year and everything was broken. Maybe I shouldn't self-hosted this.

**Pull request merged**
