### PR TITLE
imp(docker): streamline the build and run process

### PR DESCRIPTION
**Pull request by gustavovalverde**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description
- Avoid using multiple Dockerfiles
- Include caching steps for `node_modules` to avoid rebuilding
- Avoid a non-idempotent result by running `npm build` inside the image
- Use the base image to build the healthcheck
- Just copy required files from the `build` stage to the `release` stage

This allows a simpler process to build and run just using docker and also creates a smaller resulting image:

```
docker build -f docker/dockerfile -t uptime-kuma:slim --target release --build-arg BASE_IMAGE=base2-slim .

docker run -it --rm -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma uptime-kuma:slim
```

Previously, running the `docker build` from the command line would create a non-working artifact, as the build process was expected to run before and outside the image, thus creating a non-idempotent artifact.

Fixes #(issue): N/A

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by gustavovalverde** [comment]
For your consideration @louislam.

I did not create a previous conversation as I had to do this for myself anyways.

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Honestly, those are are way too many changes for one PR.
If there is anything wrong, the chance of me missing it is basically 100%.

=> please separate the changes into managable chunks.
This can be reviewing a PR commit by commit or by separate PRs.

> Simplify `.dockerignore`

You made the `.dockerignore` into a `.dockerallow`.
I don't think that that this should be used for.
The previous versions was imo simple enough..
=> lets not overcomplicate things and please revert that part.

> Remove unused `rootless` stages

Not unused. Please revert that part.
Those are a new feature in v2. See #4500 for further details 😉

**Comment by louislam** [comment]
Thanks for the pr.

Unfortunately, it introduces some breaking changes and I am not going to explain or review it. As eventually, I prefer to keep my current approach. The current approach is just working fine and I don't want to risk it. 

And there are some reasons why I designed like this, but this pr also removed some of my design here.

According to our contribution guide, this pr fall into these situations:

>Before diving deep into coding, having a discussion first by creating an empty pull request for discussion is preferred.

> Breaking changes 

> Don't modify or delete existing logic without a valid reason.


Hope you understand.

**Comment by gustavovalverde** [comment]
@CommanderStorm 
> => please separate the changes into managable chunks.
I've remove other parts

> => lets not overcomplicate things without a reason and please revert that part.
I've reverted the `.dockerignore`

> Not unused. Please revert that part.
I've revert the rootless part

@louislam 
> Unfortunately, it introduces some breaking changes 
I've removed the breaking changes.

FYI: Having a single Dockerfile can improve other parts of the workflow, like publishing the images (you would only need to publish the resulting release). Also, I can also create other PRs with GitHub Actions to automate the building and publishing process of the Dockerfiles to Docker Hub. Even running E2E tests using docker.

**Comment by louislam** [comment]
Unfortunately, the last changes introduced more unexpected bugs. As I said before I am not going to explain or review it. I want to keep my current approach. 

I think my previous message was clear and I really don't want to waste your time, I am going to close this pr. Hope you understand.

> I can also create other PRs with GitHub Actions to automate the building and publishing process of the Dockerfiles to Docker Hub.

Also no. Similar PRs were rejected before. My PC is much faster and my network is much more stable, I prefer to build it locally.

**Comment by gustavovalverde** [comment]
I understand. I wanted to make some questions to better understand which kind of PRs would be accepted to improve the docker deployment, but I suppose that won't be explained.

By the way, about the rootless image, what I wanted to explain is that every image dependable on the release stage (as of now) is rootless, after this change: https://github.com/louislam/uptime-kuma/commit/d810a74d707325eaba714c4f52e2ff46733aeb65#diff-5094b94dfb7d158bda4b6e5e1112804dd632284f6318c8f99636ced3eadef994L30

Line 30 defines `USER node`, which makes `release`, `nightly` and `nightly-rootless` all rootless by default.

**Comment by louislam** [comment]
Thanks for the report, will check later. Related issue: #4052

**Pull request closed without merging**
