### PR TITLE
Implement template engine for message [On Hold for #760]

### PR DESCRIPTION
**Pull request by deefdragon**
Template engine implementation for #646.

The current method of implementation only shows the template options when it has been specifically enabled for that notification type. This is to allow testing of templates for each notification method individually. 

For all existing notifications, because the option is empty, it uses the "low detail" template, which is the current message received from most notifications. This is also the default value in the drop-down for newly created templates.
 
I realized while writing this that it might be best to pass the templates in via the front-end instead of just their name as that would allow them to easily be added to the translation files, _and_ make it easier to modify the templates available when based on the notification (adding specific templates for discord detail levels for example). The current templates are also only starting points, and I feel not the best matches to their namesakes, so I welcome input there.

The testing of a notification now passes in a test heartbeat and monitor, but it is not perfect. They should ideally loop through different values so that the user can test complex templates easily.

The generation of the template argument really should be pulled out to it's own function. Specifically to have the most common keys such as `name` and `health` to not require `monitor.name` and `monitor.health` etc. as well as to add data for the names used in #627 for compatibility. This would also move the "healthy/unhealthy" to a set location.

What the UI looks like adding the template, Added before the notification specific options.
TemplateForm

### CODE REVIEW

**Comment by deefdragon** [comment]
You mentioned that it would be impossible to write tests of the different notifications. Could you expand on why?
Are you referring to just e2e tests? I believe it will be easy enough to write unit tests for the notifications.

**Comment by louislam** [comment]
> You mentioned that it would be impossible to write tests of the different notifications. Could you expand on why? Are you referring to just e2e tests? I believe it will be easy enough to write unit tests for the notifications.

- You cannot verify them in message platforms automatically. 
- Some of them are paid services such as SMS
- Some of them always returns successful message even if it is using a invalid api key.
- Some of them are having word limit.

**Comment by deefdragon** [comment]
> So I strongly recommend that we should think and write a complete test first before implementing this function.

That is completely fair. I am working on writing some tests for the SMTP notification. I think that I am close to an example. If you think it works, Ill start on the other notifications. Ill throw another PR out with it shortly for examination.

**Comment by GalacticAust** [comment]
Hi All 

I know this is a old post but did we ever get to edit the body of the email? from the dashboard? 

If not how do we edit the layout of the email sent 

Thanks all

**Pull request closed without merging**
