### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**
# Description

Translations in alphabetical order, also updated in German

## Type of change

- Translation update
- Other

### CODE REVIEW

**Comment by Saibamen** [comment]
Please update German i18n in one PR and after merge, create seconds PR with alphabetical order

**Comment by Justman10000** [comment]
> Please update German i18n in one PR and after merge, create seconds PR with alphabetical order

Why? Who cares? GitHub not!

**Comment by Justman10000** [comment]
@louislam

**Comment by louislam** [comment]
I don't have time to check all modified files, as there are too many changes. I did reject a similar pr before.

It would be great if we have a discussion first next time.

Pull Requests rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

**Comment by Justman10000** [comment]
And I will certainly not give up this PR! It took too much time and effort for that!

**Comment by finnie2006** [comment]
> And I will certainly not give up this PR! It took too much time and effort for that!

Totally aggree with that

**Review by gaby — APPROVED** [review]
LGTM

**Comment by Justman10000** [comment]
> > You can go to _Files changed_... There is an overview of everything! Except for one commit, everything is just about the languages ​​anyway... And I don't think I'll open an issue just to talk about updating files...
> 
> We are looking at over 12,000 lines changed, it is impossible to manually make sure that there are no errors or omissions when you reordered all of the lines. I can't tell which German translations you have added and which ones you have just reordered which means that I have no way of checking them. Is it really neccessary to reorder all of the keys for the translations? It is going to cause merge conflict after merge conflict for any other open translation PRs. Thank you for all the work you put into this, but surely you can understand how hard it is for anyone to make sure that nothing is broken by merging this PR.
> 
> Also, could you make sure that the linting tests pass, currently it seems that a number of files are missing blank lines at the end.

It's easier than rearranging because, in hindsight, it's easier to see when something is added, changed, or removed in the source translation...

**Comment by louislam** [comment]
Another reason is I want `languageName` to be the first key.

```
export default {
    languageName: "Czech",
```

Moreover, this pull request can't even pass the auto test. It is hard to trust this pull request without read them line by line.

Close, as @Computroniks and I have explained the reasons. If you need to update the Germen file, feel free to create another pull request without reordering key and passing the auto test.

**Pull request closed without merging**
