### PR TITLE
Do not translate Huawei and Android

### PR DESCRIPTION
**Pull request by Saibamen**
Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Addendum to #2812 + remove iOS i18n leftovers

## Type of change

Please delete any options that are not relevant.

- Other

### CODE REVIEW

**Comment by chakflying** [comment]
Huawei is kind of a special case since it does have a Chinese name 😂

**Comment by Zaid-maker** [comment]
What this even mean?

**Comment by louislam** [comment]
> What this even mean?

It's just a name in Chinese with two words `華 (Hua)` and `為 (Wei)`, that's why I kept it in the language files.

**Comment by CommanderStorm** [comment]
@Saibamen Given that Louis has raised the point that this is translatable in Chinese, I think this PR can either be reduced to just iOS or closed.

**Comment by Saibamen** [comment]
https://github.com/louislam/uptime-kuma/pull/3480

**Pull request closed without merging**
