### PR TITLE
Added import options

### PR DESCRIPTION
**Pull request by Ponkhy**
I added import options as mentioned in #378.
There are three options you can choose "Keep both", "Skip existing" and "Overwrite".

"Keep both" is pretty much the "old" mode where everything was imported regardless of what already was in the database.
"Skip existing" will skip every monitor or notification with the same name.
"Overwrite" will delete everything in `heartbeat`, `monitor_notification`, `monitor_tls_info`, `notification`, `monitor` and then import the backup.

I also added a confirm popup because especially with the "Overwrite" mode a lot stuff can be damaged.

Updated UI: 
Settings
ConfirmImport

### CODE REVIEW

**Comment by chakflying** [comment]
IMO the word "Overwrite" sounds a bit vague, like maybe it would only update existing monitors. But I'm not sure what would be better either, maybe "Replace All" ?

**Comment by Ponkhy** [comment]
Yep though the same, that's why decided at the end to write a description under it.
But i'm also not sure what would be the best.

**Comment by Saibamen** [comment]
How to push commits to GitHub PRs for different person?

**Comment by Ponkhy** [comment]
I actually have never done it by myself, but have seen it ones, Sorry ^^°

**Comment by Ponkhy** [comment]
Or maybe it would work when you make a PR on my branch and i merge it.

**Comment by Ponkhy** [comment]
@Saibamen Thank you, looks really good!

**Comment by louislam** [comment]
> How to push commits to GitHub PRs for different person?
> 
> I want to add changes discussed here: #385
> image

It sounds better if the "Export" button align to the left?

**Comment by chakflying** [comment]
Also, the settings page is getting a bit cluttered a this point. Maybe not now, but definitely thinking about removing the monitor list and add subpages / sections in the settings page.

**Comment by Saibamen** [comment]
> > How to push commits to GitHub PRs for different person?
> > I want to add changes discussed here: #385
> 
> It sounds better if the "Export" button align to the left?

Just remove `d-flex` and `justify-content-center` classes from Export button

**Comment by Ponkhy** [comment]
Yea i agree with @chakflying!
If @louislam really want's it on the left side i can remove the two classes.
I think for now in the middle is better but if the settings page gets separated it might be better on the left.

**Comment by louislam** [comment]
> Yea i agree with @chakflying!
> If @louislam really want's it on the left side i can remove the two classes.
> I think for now in the middle is better but if the settings page gets separated it might be better on the left.

Yes, since other buttons in the page is aligned to the left, it could be more consistent.

**Comment by Ponkhy** [comment]
> Yes, since other buttons in the page is aligned to the left, it could be more consistent.

Done!

**Pull request merged**
