### PR TITLE
2.0.0 Checklist

### PR DESCRIPTION
**Pull request by louislam**
Not actually a pull request.

## Checklist

Edit: Suddenly realized that some features have not adopted to new aggregate tables yet.
- [ ] Migrate existing heartbeat data into aggregate tables  
- [x] Clear stats (#4324)
- [ ] History retention 
- [ ] Ping chart (#4264)
- [ ] ~Heartbeat table keeps 24-48 hours data only (excepted for important events, it will keep longer for the event list)~ (Can be deferred)

# 
- [ ] E2E Testing using Playwright
- [x] Test and fix Badges feature (#1119) (A big headache for me right now, because new table schemas breaks this feature a lots)
- [ ] Migration guide from v1 to v2 (Wiki)
  - [ ] New Docker tags 
  - [ ] Found out all breaking changes
    - [ ] Warns Debian/Raspbian Buster users
- [ ] Benchmark 
- [ ] Write the changelog
- [ ] Release 2.0.0-beta.0
- [ ] Release 2.0.0-beta.1
- [ ] ...
- [ ] Release 2.0.0

### CODE REVIEW

**Comment by chakflying** [comment]
I also plan to rewrite/expand the wiki using [the four functions of documentation system](https://documentation.divio.com/) to make it more approachable.

**Comment by CommanderStorm** [comment]
adding more fields (database, filesystem, amount of monitors) to the issue templates might also be helpful before releasing `2.0.0-beta.0`

**Comment by Zaid-maker** [comment]
Add `Publish to NPM` in the list aswell

**Comment by louislam** [comment]
> Add `Publish to NPM` in the list aswell

Postponed to another milestone, as adopting the aggregate tables are higher priority.

**Comment by Zaid-maker** [comment]
> > Add `Publish to NPM` in the list aswell
> 
> Postponed to another milestone, as adopting the aggregate tables are higher priority.

Ohhh ok👍

**Comment by mabed-fr** [comment]
Hello,

When will we be able to have a docker image of 2.0.0?

**Comment by CommanderStorm** [comment]
@mabed-fr once it is ready.
See checklist above: `Release 2.0.0-beta.0`

**Comment by louislam** [comment]
Focusing on other things in real life recently, but since 2.0.0 may have been held off for a bit too long, I am setting a date here.

I hope `2.0.0-beta.0` can be released in spring 2024, which doesn't include the e2e tests yet. During the beta test, I will try to work on implementing the e2e tests.

**Comment by CommanderStorm** [comment]
@chakflying @louislam 
I am going to close this issue as I have made this into a pin-able issue.
I feel our users/contributors have a hard time finding this PR => transfering the discussion there is better for transparency (and reduces the workload of issues which are invalid due to this miscommunication) ^^

**Comment by louislam** [comment]
Thanks, no problem. I will come back soon.

**Pull request closed without merging**
