### PR TITLE
added starting changes for status page

### LINKED ISSUE #2451: Certificate expiry on the status page
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to have the ability to choose if a entry on the status page should show the certificate expiry (if enabled on the dashboard add monitor settings) underneath it, for example, and highlight the monitor on light red when it's going to expire.

### ✔️ Solution

The certificate expiry is already on the dashboard. It should be easy to add it on the status page

### ❓ Alternatives

No alternatives I can think about.

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tarun7singh**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #2451 

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by SofieneOuerdiane** [comment]
Hello, thank you for this pull request ? how can I help finishing and merging it ?
Thanks

**Comment by louislam** [comment]
Is it ready to be reviewed? If yes, don't forget to press `Ready for review`.

**Comment by tarun7singh** [comment]
@louislam Its not ready to be reviewed yet, i stopped work on it from some time, will pick it up again this weekend.

**Comment by tarun7singh** [comment]
Closing this one to create a new one as this one got messed up.

**Pull request closed without merging**
