### PR TITLE
feat(extract-translations): add extract translations script

### PR DESCRIPTION
**Pull request by bertyhell**
Extracts the translations from the source code
and adds the missing translations to the language files

No changes have been made to the case of the translation keys. See Discussion: https://github.com/louislam/uptime-kuma/pull/568#issuecomment-936605632

Any translations that cannot be automatically added show up as warnings.
Any translations that are in the translation files but are not used also show up as a warning.
```
> node ~\uptime-kuma\extra\extract-translations.js
Extraction successful with warnings:
        Cannot extract non string values in $t((this.isAdd)
        Cannot extract non string values in $t(translationPrefix + "Response")
        Cannot extract non string values in $t(translationPrefix + "Ping")
        Cannot extract non string values in $t(type)
        Language file da-DK contains keys that are not used: ["Also apply to existing monitors"]
        Language file es-ES contains keys that are not used: ["Also apply to existing monitors"]
        Language file fr-FR contains keys that are not used: ["Also apply to existing monitors"]
        Language file ja contains keys that are not used: ["Also apply to existing monitors"]
        Language file ko-KR contains keys that are not used: ["Also apply to existing monitors"]
        Language file nl-NL contains keys that are not used: ["Also apply to existing monitors"]
        Language file pl contains keys that are not used: ["Also apply to existing monitors"]
        Language file ru-RU contains keys that are not used: ["Also apply to existing monitors"]
        Language file sr-latn contains keys that are not used: ["Also apply to existing monitors"]
        Language file sr contains keys that are not used: ["Also apply to existing monitors"]
        Language file sv-SE contains keys that are not used: ["Also apply to existing monitors"]
        Language file zh-CN contains keys that are not used: ["Also apply to existing monitors"]
        Language file zh-HK contains keys that are not used: ["Also apply to existing monitors"]
```

After running the script the translation file changes look like this:
image

image

I've not included the output of the script in this PR to keep is small and easy for @louislam to review. Once the script is accepted @louislam or me can run the script and commit the output in a separate PR.

We might even be able to run this script as a pre-commit hook in the future using [husky](https://typicode.github.io/husky/#/).

### CODE REVIEW

**Comment by Saibamen** [comment]
Please revert any changes related to `package-lock.json` to avoid merge conflicts

**Comment by Saibamen** [comment]
@louislam can you update tests to install NPM dependencies before testing?
`npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`

**Comment by bertyhell** [comment]
@Saibamen 
> Missing support for `i18n-t` tag

Fixed

**Comment by bertyhell** [comment]
@louislam Fixed the issue. Now extracted translations in other files will default to English if it's available:
image

**Comment by deluxghost** [comment]
can we integrate with third-party i18n platforms e.g. weblate?

benefits:

* translators get new string notification
* easier translation process (no need to create PR by human)
* translation badge or graph
* nice editor

**Comment by YehowahLiu** [comment]
Now using Weblate, the language files are in json format (src/lang/\*.json), so this script needs to be edited.

**Comment by CommanderStorm** [comment]
@bertyhell given that we are currently using Weblate for translations, is this PR still relevant? (Should it be closed?)

**Comment by bertyhell** [comment]
I suspect we late will handle any mismatches in translation keys between the various languages.

So I'll close this one.

**Pull request closed without merging**
