### PR TITLE
Upgrade Debian Buster -> Bullseye

### PR DESCRIPTION
**Pull request by Jamie-**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

As per the discussion in #372, the `node:14-bullseye-slim` container had issues with node, however this issue is not present in `node:16-bullseye-slim` (and this project has now moved on from node 14).

```
$ docker run --rm node:16-bullseye-slim -e "console.log('hello-world')"
hello-world
```

I have changed both the node and golang base containers to Debian Bullseye, built all containers with success and have a working Uptime Kuma environment.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by louislam** [comment]
Did you test it on Pi4? It is still not working for me.

```
root@louis-twister-pi:~# docker run --rm node:16-bullseye-slim -e "console.log('hello-world')"
Unable to find image 'node:16-bullseye-slim' locally
16-bullseye-slim: Pulling from library/node
f8686edc9eb6: Already exists
3e811ad57ceb: Already exists
c8338464b435: Pull complete
1d31a8b30df8: Pull complete
1fef06f6cf16: Pull complete
Digest: sha256:30ec224b4c35a768e038674444d0718494a7d8847c96ee73a8d3db795135b4c9
Status: Downloaded newer image for node:16-bullseye-slim
Node.js[1]: ../src/util.cc:190:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
root@louis-twister-pi:~#
```

**Comment by Jamie-** [comment]
Ah sorry I don't have a Pi4, apologies for missing that.

**Comment by Jamie-** [comment]
Although the upstream issue for that specific bug points to an outdated package on the Pi..

https://github.com/nodejs/docker-node/issues/1746#issuecomment-1181011165

**Comment by louislam** [comment]
It is so weird, no one seem to care this bug and haven't fixed for over a year, lol. 
Pi4 users don't use Node.js?

Anyway, since I want to support more platforms, I will keep using buster. Thanks.

**Pull request closed without merging**
