### PR TITLE
Update i18n.js

### LINKED ISSUE #4594: Hebrew Language - RTL insted LTR
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I use the system with the Hebrew language, and the system should be RTL but is still set to LTR, how can I change so that the system direction is RTL

### 📝 Error Message(s) or Log

_No response_

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

WIndows

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

### PR DESCRIPTION
**Pull request by msrl2000**
Added Hebrew to RTL Languages

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [X ] I have read and understand the pull request rules.

# Description

Fixes #4594

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Review by CommanderStorm — APPROVED** [review]
Thanks for the pull request

**Comment by CommanderStorm** [comment]
Note to self: next time first change the pr title, THEN merge🤦🏻‍♂️

**Comment by Zaid-maker** [comment]
> Note to self: next time first change the pr title, THEN merge🤦🏻‍♂️

I have a suggestion to stop this kind of PR's from happening.
We can setup Semantic PR Title to prevent this kind of titles, many big projects use this approach to make clean PR's

**Comment by CommanderStorm** [comment]
I don't know if such a comment scares away new contributors. (The checklist is already pretty long)
=> adding more friction via a comment is something I would like to avoid.

Having a CI-check though (idk, might be subjective/wrong) seems like something that would introduce less friction.

**Pull request merged**
