### PR TITLE
New feature: Monitor TLS ports

### LINKED ISSUE #1079: Add SSL Certificate checks for General TCP ports
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor

### 🔖 Feature description

Say you have an application running on a TCP port using an SSL Certificate that will expire eventually.
You want to have notifications for the certificate expiry (as is possible with HTTPS currently).

## Usecases
IMAP on Port 993
```sh
openssl s_client -connect imap.gmail.com:993
```
SMTP starttls checks on Port 25
```sh
openssl s_client -starttls smtp smtp.gmail.com:25
```

### ✔️ Solution

I propose Uptime Kuma adds (optional) SSL certificate monitoring for the `TCP Port` Monitor which might use similar functionality as described above.

### ❓ Alternatives

_No response_

### 📝 Additional Context

Trying to add expiry notifications for my mail server certificate.

### PR DESCRIPTION
**Pull request by mrubli**
# Description

This adds a new monitor type for TLS ports, similar to the "TCP Port" monitor but ensuring that a valid TLS connection can be established and checking for an expected keyword. This allows monitoring of services like IMAP or POP3.

I haven't spent much time on style or documentation but will gladly do that if there is interest in merging this feature.

My current code is on the [feature/tls-monitor-dev](https://github.com/mrubli/uptime-kuma/compare/feature/tls-monitor-dev) branch (needs rebasing): https://github.com/mrubli/uptime-kuma/commit/6d92a60a714abd1e421f82906e8800be04005d1b

I've deployed it on my own server and it works well so far for monitoring IMAP and POP3. A Docker image can be found here:
https://github.com/mrubli/uptime-kuma/pkgs/container/uptime-kuma

Fixes #1079.

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

### CODE REVIEW

**Comment by louislam** [comment]
For me, I always thought TLS = SSL = HTTPS for some reason. Maybe call it `TCP Port (TLS)`?

**Comment by shaneshort** [comment]
is there anything holding this feature up? it looks very useful

**Comment by hoerup** [comment]
I would very much like to see this feature get implemented. 

A question for @mrubli - would it be possible to have it work for both implicit TLS and explicit/STARTTLS types ?

**Comment by mrubli** [comment]
@louislam

> For me, I always thought TLS = SSL = HTTPS for some reason. Maybe call it `TCP Port (TLS)`?

I personally wouldn't call that equation accurate but renaming is easy and I don't mind. :-)

If the name is the only thing holding up this feature I'll spend some time rebasing it and cleaning it up where necessary.

@hoerup

> 1. would it be possible to have it work for both implicit TLS and explicit/STARTTLS types ?

STARTTLS is quite a different beast and apparently takes [some work](https://stackoverflow.com/questions/20679906/implementing-starttls-in-a-protocol-in-nodejs). I don't have time to implement that at this point but if someone wants to help integrating that would be welcome.

> 2. do you check for cert expiration as well

The way I understand the API an expired server certificate should make the connection test fail. You could easily verify that by pointing it at https://expired.badssl.com.

**Comment by hoerup** [comment]
> > 2. do you check for cert expiration as well
> 
> The way I understand the API an expired server certificate should make the connection test fail. You could easily verify that by pointing it at https://expired.badssl.com.

I might have been a bit unclear - what I meant was something like the certificate Expiry from https monitor, so we get warnings BEFORE the cert expires and everything breaks :)

**Comment by mrubli** [comment]
> I might have been a bit unclear - what I meant was something like the certificate Expiry from https monitor, so we get warnings BEFORE the cert expires and everything breaks :)

Ah yes, that sounds like a useful to have. I'll look into it if there's interest in merging this

**Comment by tobhv** [comment]
hi. yes, the certificate expiration is also something i am looking for. using openssl client on the commandline the info can be found like this:
echo | openssl s_client -connect <fqdn>:<port> 2>/dev/null | openssl x509 -noout -dates

and also a javascript reference that may help:
https://medium.com/@keithwan.programming/doing-ssl-certificate-expiry-alert-in-node-js-1714ef15621 

not sure though what is best in terms of splitting the work up (e.g. first release the feature without the expiration check) or combine but even without the expiration check there is value in this feature.

@louislam what are your thoughts ?

**Comment by parallelo3301** [comment]
This is exactly what I'm looking at right now and have to use custom script to check the validity with the `openssl` client. Is there anything to do I could help with to get this merged in the future?

**Comment by hoerup** [comment]
@mrubli any news on this one ?

**Comment by ErnieB44** [comment]
Can someone please explain if this is already merged in to a release? And if not, are there any plans to do this in the near future? Can't wait to bring this feature to use..

Thanks

**Comment by CommanderStorm** [comment]
> Can someone please explain if this is already merged in to a release?

No, the closest thing that exists is the https monitor. (you can configure the [HOST Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host))
This PR was closed due to being stale and without progress for quie a while.

> And if not, are there any plans to do this in the near future?

Depends what you mean by near future.
All milestones with the PRs we want to review in said releases is written here: https://github.com/louislam/uptime-kuma/milestones

Currently, the core team is quite heavily focused on bringing v2.0 on the road. (see https://github.com/louislam/uptime-kuma/pull/4171)
Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by ErnieB44** [comment]
> > Can someone please explain if this is already merged in to a release?
> 
> No, the closest thing that exists is the https monitor. (you can configure the [HOST Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)) This PR was closed due to being stale and without progress for quie a while.
> 
> > And if not, are there any plans to do this in the near future?
> 
> Depends what you mean by near future. All milestones with the PRs we want to review in said releases is written here: https://github.com/louislam/uptime-kuma/milestones
> 
> Currently, the core team is quite heavily focused on bringing v2.0 on the road. (see #4171) Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Hi @CommanderStorm , thanks for the quick repsonse.
It's a very nice to hear that the core team is working hard on v2. I've tried to use the HOST header but it fails.. would you be so kind to let me know if it is even possible what i'm trying to achieve? I want to monitor de SSL certificate on a Windows RDS server. So it should check the certificate at an endpoint on port 3389.

Thanks

**Comment by CommanderStorm** [comment]
I don't know what `Windows RDS Server` is and how it works.
If not supported, and you know how it should work, I would suggest you to use the push monitor instead or propose a monitor via the contribution guide above.

**Comment by d3xt3r01** [comment]
I don't think the app protocol is of any importance in this case as the expected check is at a different layer. TLS is TLS. It's the layer that handles the encryption. It just wraps the protocol in encryption. The monitor many of us want is just the tls part. To make sure the certificate is installed correctly and not expired. We're not trying to validate the application/protocol in any way.
That's why `openssl s_client -connect fqdn:port` should work with anything, no matter the app protocol.
In any case, a tcp check in this case usually causes tls errors on the other end since the connection is started on a tls port but tls negotiation doesn't finish and we get tons of `SSL_accept(): Internal OpenSSL error or protocol error: : unexpected eof while reading`

**Pull request closed without merging**
