### PR TITLE
Fix: Correct Maintenance Start/End Time Input to Use Explicitly Specified Timezone

### LINKED ISSUE #4066: Maintenance start/end time input incorrectly uses system timezone
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

image
image
I set the Chinese time, but after exiting, the time displayed was 1 hour later than the set time, but the actual execution time was correct.

### 👟 Reproduction steps

Select the time zone as Shanghai and set up planned maintenance

### 👀 Expected behavior

Time display leading to status page errors

### 😓 Actual Behavior

Status page error time display

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

edge

### 🐋 Docker Version

Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Ritik0102**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4066

Correct Maintenance Start/End Time Input to Consider Daylight Saving Time (DST)
## Type of change
Timezone bug fix
Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by louislam** [comment]
Will try to rebase to `1.23.X`.

I always think `dayjs.tz(...)` is very confusing, because this single function is used for converting, displaying and parsing at the same time. My brain cannot follow this.

Would you mind to explain a bit, why adding `true` could resolve the issue?

**Comment by Ritik0102** [comment]
Thank you for considering my fix. The addition of `true` as a parameter in `dayjs.tz(...)` is crucial for correct timezone handling, especially in scenarios involving **Daylight Saving Time (DST)**.
On passing a second parameter as true, only the timezone (and offset) is updated, keeping the local time the same. This ensures accurate representation and prevents issues where the output was consistently one hour off due to DST not being taken into account.
For more detailed information, you can refer to the [](https://day.js.org/docs/en/timezone/converting-to-zone)

**Comment by louislam** [comment]
To be honest, I am still confusing how it is related to DST, because of https://github.com/louislam/uptime-kuma/issues/4066#issuecomment-1832236176. China and Japan are the places without DST.

**Comment by Ritik0102** [comment]
I appreciate your feedback. I understand the confusion, and I want to clarify that the addition of `true` in `dayjs.tz(...)` is not directly related to Daylight Saving Time (DST) itself but rather serves to ensure accurate timezone conversion.

Even though China and Japan do not observe **DST**, the true parameter helps in consistent handling of timezones across various regions. It guarantees that the timezone (and offset) is updated appropriately during conversion, preventing any unintended discrepancies in representation.

**Comment by chakflying** [comment]
Really don't appreciate the GPT-style comments :)

**Comment by Ritik0102** [comment]
Thank you for your feedback. I will surely work on that :)

**Pull request merged**
