### PR TITLE
Moving the server

### PR DESCRIPTION
**Pull request by louislam**
From: Linode (Tokyo, Japan / 2 Cores / 4GB RAM / $24 per month)
To: OVH (Frankfurt, Germany / 4 Cores / 4GB RAM / $11 per month)

Linode increased the price this year, which makes it a bit expensive. 

And the old server is CentOS 7, which will reach EOL soon. It is also a chance to switch to a up-to-date OS (Debian Bookworm)

Also it seems that putting the server in EU is a better choice of location.

Checklist:
- [x] Move https://status.kuma.pet
- [x] Dockerize https://demo.uptime.kuma.pet
- [x] https://demo.uptime.kuma.pet => https://demo.kuma.pet/start-demo (As sub-sub-domain cert is not supported on Cloudflare)
- [x] Move Weblate
- [x] Dockerize and move https://uptime.kuma.pet (https://github.com/louislam/uptime-kuma-website/pull/2)
- [x] Move https://dockge.kuma.pet

### CODE REVIEW

**Comment by Zaid-maker** [comment]
That's a great news 👍

**Comment by louislam** [comment]
Just dockerized uptime-kuma-website. And I did not notice that before, the `/version` endpoint requests is about 1-2 requests per second, which makes me wondering how many Uptime Kuma instances are running all over the world. Considering the endpoint only be called 1 time per 48 hrs.

image

**Comment by Zaid-maker** [comment]
> Just dockerized uptime-kuma-website. And I did not notice that before, the `/version` endpoint requests is about 1-2 requests per second, which makes me wondering how many Uptime Kuma instances are running all over the world. Considering the endpoint only be called 1 time per 48 hrs.
> 
> image

Is there any way to track how many instances of uptime kuma is running all over the world maybe we can use Umami

**Comment by mabed-fr** [comment]
> From: Linode (Tokyo, Japan / 2 Cores / 4GB RAM / $24 per month) To: OVH (Frankfurt, Germany / 4 Cores / 4GB RAM / $11 per month)
> 
> Linode increased the price this year, which makes it a bit expensive.
> 
> And the old server is CentOS 7, which will reach EOL soon. It is also a chance to switch to a up-to-date OS (Debian Bookworm)
> 
> Also it seems that putting the server in EU is a better choice of location.
> 
> Checklist:
> 
> * [x]  Move https://status.kuma.pet
> * [ ]  Dockerize https://demo.uptime.kuma.pet
> * [ ]  https://demo.uptime.kuma.pet => https://demo-uptime.kuma.pet (As sub-sub-domain cert is not supported on Cloudflare)
> * [x]  Move Weblate
> * [x]  Dockerize and move https://uptime.kuma.pet ([Dockerize uptime-kuma-website#2](https://github.com/louislam/uptime-kuma-website/pull/2))
> * [x]  Move https://dockge.kuma.pet

Try contabo.com

At 4,50 €
/ Mois
4 cœurs de processeur virtuel
8 Go de RAM
NVMe de 50 Go
ou 200 Go SSD
1 instantané
Trafic de 32 To*

**Comment by louislam** [comment]
I actually had ordered Hetzner/Netcup/Contabo before OVH.

But they rejected/refunded my orders maybe due to the document proof issue. And they didn't explain what I was missing and immediately closed my account. (which to me, they are like a scam, because I provided my sensitive data and credit card number and got banned)

Anyway, I am so far happy with OVH, hope their data center don't catch fire again.

**Pull request merged**
