### PR TITLE
Discourage usage of local Docker cache

### PR DESCRIPTION
**Pull request by gaby**
# Description

Potential fix for #1556 which my guess is that when 1.15.0 was released, the local build used an old copy of the `base` image from @louislam development environment.

Ideally every time that `npm run build-docker` is executed we also rebuild the base images, that way base dependencies and `cloudflared` will get updated to their latest version.

This PR mainly adds the two commands for building the base images to `npm run build docker`, it also adds the `--no-cache` flag to each `docker build` command which discourages Docker Daemon from using local cache. 

More info about the flag here: https://docs.docker.com/engine/reference/commandline/buildx_build/

### CODE REVIEW

**Comment by gaby** [comment]
@louislam Just a note, these changes will make the release process of `Docker Images` slower, since everything will be rebuild from scratch for each `Uptime-Kuma`, but it's the only way to be sure that latest versions of each base dependencies are installed.

**Review by Saibamen — APPROVED** [review]

**Comment by gaby** [comment]
@Saibamen i'm closing this, it probably wont get merged.

**Comment by Saibamen** [comment]
> it probably wont get merged.

Why?

**Comment by gaby** [comment]
@Saibamen Seems like nothing gets merged :-S unless it's a simple fix or a translation.

**Comment by Saibamen** [comment]
@louislam

**Pull request closed without merging**
