### PR TITLE
Create ja.js

### PR DESCRIPTION
**Pull request by kometchtech**
* Created a Japanese language file.

### CODE REVIEW

**Comment by kometchtech** [comment]
I have never translated language files in OSS before, so I am not confident about the quality.

**Comment by louislam** [comment]
Thank you so much, but there are more keys to be translated. I will generate for you later.

**Comment by louislam** [comment]
Added missing keys.

Here is a part of your translation:


ありがとう👍

**Comment by kometchtech** [comment]
I have also confirmed that the key has been added.
I will try to respond to this when I have time.

**Comment by kometchtech** [comment]
Performed translations for the added keys.
Some of them have not been translated because I could not find the right Japanese words for them.

**Comment by louislam** [comment]
> Performed translations for the added keys.
> Some of them have not been translated because I could not find the right Japanese words for them.

Thanks, it looks great.

**Pull request merged**
