### PR TITLE
Update es-ES.js

### PR DESCRIPTION
**Pull request by johnfelipe**
es-ES.js updated

### CODE REVIEW

**Review by Computroniks — CHANGES_REQUESTED** [review]

**Comment by chakflying** [comment]
Also it's difficult to see which lines you changed because you re-ordered a lot of the keys.

**Comment by johnfelipe** [comment]
Dear I translate with same order like English file

**Comment by louislam** [comment]
> Also it's difficult to see which lines you changed because you re-ordered a lot of the keys.

Agree, my suggestion would be keeping the order on this pr first.

If you need to re-order, make another pr after.

**Comment by louislam** [comment]
Close as don't pass the auto test and staled, free feel to reopen if fixed.

**Pull request closed without merging**
