### PR TITLE
Proposal: Generate RSS feed for Status Pages

### PR DESCRIPTION
**Pull request by Rhaal**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [X] I have read and understand the pull request rules.

# Description

This PR would introduce support for RSS rendering of Status Pages.

As pointed out in the discussion on https://github.com/louislam/uptime-kuma/issues/1673, the Uptime Kuma notification system operates on a strictly push logic, whereas RSS is meant to be a programmatic representation of the same data on a given Status Page, with clients being responsible for periodically pulling its content.

Therefore, I would propose adding a toggle option on the Status Page configuration UI, labeled _Support RSS_ or something of the like, in the highlighted region:
image

Ideally, if the option is enabled, an RSS feed generated via https://www.npmjs.com/package/feed or any other similar package would be served either on the same URL but with a GET query parameter (e.g. `http://localhost:3001/status/sample?rss`) or on a URI that forks from the status page one (e.g. `http://localhost:3001/status/sample/rss`)

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by louislam** [comment]
I think the difficulty of this pr would be what to show in the rss feed, because notification error messages could be detailed that you don't want to show them to the public.

**Comment by Computroniks** [comment]
> I think the difficulty of this pr would be what to show in the rss feed, because notification error messages could be detailed that you don't want to show them to the public.

I think that status.github.com could be something to look at in terms of what to include. I note that the rss feed does include stuff like details on incident response, something we don't have yet. But if we regard RSS as a notification system for end users, not system administrators then we should only use the data exposed to the public status page anyway.

**Comment by Rhaal** [comment]
I do agree that a full representation of the incident dynamics via RSS would be optimal, as would the ability to show what data should be displayed over RSS, but I do believe that a 1:1 mapping of the content displayed via HTML would be a good starting point, as RSS is by its very nature a format intended for secondary parsing by the consuming clients - if people just want to get every published uptime percentage they're free to do so, discarding all nodes superfluous to the task!

Of course @louislam I'll defer to your vision for the project - if you do believe an additional layer of configurability would be appropriate, by all means, feel free to indicate which parts should be tunable and I'll do my best to update the screens to provide a general outline of the implementation!

**Comment by Rhaal** [comment]
Hi @Computroniks ! Sorry, no progress, I was waiting for @louislam's reply - but do feel free to take over!

**Comment by CommanderStorm** [comment]
@Rhaal 
I am going to close this PR due to being stale for ~1y.

As long as an RSS feed does show the currently public information, this would be fine by us, as stated above.
We can reopen this PR if you'd like to continue this work.

**Pull request closed without merging**
