### PR TITLE
Restructure status page core implementation

### PR DESCRIPTION
**Pull request by louislam**
# Description

Since I was not aware of status page which could be multiple, this pr is going to restructure the status page core.

- [x] Status Page table
- [x] Migrate current status page, settings to the table
- [x] /status/:name
- ~[x] public/private field (no logic, just a field)~
- [x] password field (no logic, just a field)
- [x] Entry Page, default status page
- [x] incident change to many-to-many

Move to the next stage:
- [ ] CNAME alias, multiple for each status page
- [ ] search engine indexing base on each status page

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and test it
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

⚠️ If you want to create a pull request which is related to status page, I strongly recommend that you should wait until this pr get merged.

### CODE REVIEW

**Comment by mathiskir** [comment]
is this still used @louislam ?

**Comment by almereyda** [comment]
Is there any reference that one could check out to find information regarding the follow ups (CNAME, robots) that were outlined above?

**Comment by louislam** [comment]
> Is there any reference that one could check out to find information regarding the follow ups (CNAME, robots) that were outlined above?

https://github.com/louislam/uptime-kuma/wiki/Status-Page

**Comment by almereyda** [comment]
To give something back: Maybe on https://status.kuma.pet/ you want to change the typo `Webiste` to `Website`:

Before:

Screenshot 2022-12-14 at 15-51-18 Uptime Kuma Status

After:

Screenshot 2022-12-14 at 15-51-40 Uptime Kuma Status

**Pull request merged**
