### PR TITLE
Added JSDoc to ESLint

### PR DESCRIPTION
**Pull request by Computroniks**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

JSDoc has been added to the ESLint configuration and all errors have been corrected.

This is a follow up from the previous JSDoc PRs #2549 #1535 #1542 #1550  #1499. Hopefully adding JSDoc to ESLint should make this the last time anyone has to go through and fix JSDoc.

## Type of change

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Computroniks** [comment]
@louislam Given node 14 went EoL 3 months ago (https://endoflife.date/nodejs) it is probably worth updating the workflows. That would also fix the linter issue here as node 14 is no longer supported by eslint-plugin-jsdoc (https://github.com/gajus/eslint-plugin-jsdoc/pull/1034)

**Comment by louislam** [comment]
Other than `packjson.json`, `.eslintrc.js` and `auto-test.yml`, were the rest of the changes made by `eslint-plugin-jsdoc`?

**Comment by Computroniks** [comment]
> Other than `packjson.json`, `.eslintrc.js` and `auto-test.yml`, were the rest of the changes made by `eslint-plugin-jsdoc`? Since there are too many changes, I may be unable to review all files. If they were changed by tool, maybe I can trust directly.

No, there were some automatic fixes but most were just me going to the lines which were marked as errors and manually adding in the missing docs.

**Comment by Computroniks** [comment]
Most of them were just adding in an @returns void or the odd comment here or there

**Comment by chakflying** [comment]
Do you know how to get the JSDoc errors to show natively in VS Code?

**Comment by Computroniks** [comment]
> Do you know how to get the JSDoc errors to show natively in VS Code?

Cant remember the exact steps (it was so long ago when I did it) but I have a feeling just installing the eslint plugin should do that

**Comment by louislam** [comment]
> Do you know how to get the JSDoc errors to show natively in VS Code?

Checked on GitHub Codespace, it should work with the eslint plugin.

image


https://github.com/louislam/uptime-kuma/commit/db3a7d69fed106451e443f26865115487c009f5b

Fyi, unlikely other rules, since some jsdoc rules cannot be fixed automatically by eslint, I change some rules to `warn` instead of `error`. As my IDE keeps saying that my code is wrong during development. It is a bit uncomfortable and too aggressive.

**Pull request merged**
