### PR TITLE
Add #1209: logout button in navbar

### LINKED ISSUE #1209: Logout button in navbar
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The addition of a logout button to the navigation bar next to the settings button

### ✔️ Solution

This would provide an easy way for the user to log out of the interface without having to go into settings first. It is confusing for first time users of the interface that the logout button is located in the settings. With most other web apps, the logout button is located either in the nav bar it's self or in a profile dropdown accessible from the navbar (think GitHub). By placing it in the settings it is harder for a user to find as many probably wouldn't expect the logout button to be with the security settings. By placing it in the taskbar it allows the user to easily and quickly log out of the interface from any of the dashboard pages.

### ❓ Alternatives

Whilst it would be possible to just leave the logout button in the security section of the settings, this is hard to find for first time users and isn't very convinient as it takes 3 clicks to logout compared to only one if the button is also placed in the navbar.

### 📝 Additional Context

Perhaps something like this:
image

I would be willing to have a go at implementing this feature.

### PR DESCRIPTION
**Pull request by Computroniks**
# Description
This PR adds a button to the navigation bar that allows the user to log out of the application in only one click from any page. A button has also been added to the mobile nav bar for when the user is on a mobile device. When the Disable Auth option is enabled, the logout button does not show in the navbar.

Closes #1209 

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task) Not required

## Screenshots (if any)

Desktop navbar:
image

Mobile navbar:
image

### CODE REVIEW

**Review by Saibamen — APPROVED** [review]

**Review by mhkarimi1383 — APPROVED** [review]

**Comment by Computroniks** [comment]
Fixed merge conflicts

**Review by c0derMo — APPROVED** [review]

**Comment by louislam** [comment]
Showing logout button in the header is not so common in modern web design, but I agree the logout button is hard to find currently.

I plan to implement dropdown menu like this, so we could put the logout button there.

image

**Comment by Computroniks** [comment]
Yes, I know what you mean about it not being so common as it would normally be in a drop-down like you showed. Let me know if you need any help implementing that.

**Comment by louislam** [comment]
Suddenly interested in doing some css, I put this pr to 1.15.0 milestone.

TODO:

- [ ] Display real username
- [ ] Get the first letter of username and uppercase


image

**Pull request merged**
