### PR TITLE
Follow-up work of migrating to weblate

### PR DESCRIPTION
**Pull request by YehowahLiu**
- [x] I have read and understand the pull request rules.

# Description

## Type of change

Please delete any options that are not relevant.

- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by YehowahLiu** [comment]
#2663 Push from weblate seems ok. If we can confirm weblate can recive changes from webhook, then everything is done.

**Comment by louislam** [comment]
It seems that the email registration or verification cannot be disabled, I am going to set the smtp for that.

**Comment by louislam** [comment]
Thank you so much again!

**Comment by YehowahLiu** [comment]
I forget something:
script `update-language-files` (in package.json and extra/update-language-files) is not functional, need fix or removal

**Pull request merged**
