### PR TITLE
Add support for markdown on status page

### LINKED ISSUE #2365: Status page: Custom Links in Footer and Description
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would like to link to an imprint / legal notices in the status page footer. Currently, the footer is text-only.

### ✔️ Solution

It would be nice to be able to include an imprint using Markdown or html:

```markdown
[Imprint](https://example.org/imprint)
```

```html
<a href="https://example.org/imprint">Imprint</a>
```

### ❓ Alternatives

An alternative would be to add custom fields for links with imprint and privacy policies:

Mockup of the config sidebar:

grafik

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Computroniks**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Markdown support has been added using the [marked](https://github.com/markedjs/marked) module to the status page. To secure against XSS attacks that can come from using `v-html`, [DOMPurify](https://github.com/cure53/DOMPurify) is used to sanitize the generated HTML before it is loaded on the page with v-html.

The elements that will support markdown are:
* Footer text
* Incident notice
* Maintenance notice

Fixes #2365

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Computroniks** [comment]
This should now be ready for review

**Comment by louislam** [comment]
Link color inside a incident may need to be handled.

**Comment by Computroniks** [comment]
This should now be fixed.
image

**Comment by nicobleiler** [comment]
Could we also have the description support Markdown? Would be nice to have the ability to link to other resources.

**Comment by Computroniks** [comment]
> Could we also have the description support Markdown? Would be nice to have the ability to link to other resources.

Sounds good. I will add it to my backlog unless someone else wants to have a go.

**Comment by fabbaum** [comment]
Thanks for adding the markdown in the footer. I would also appreciate it if the markdown could be added in the description.

**Comment by andreasbrett** [comment]
> > Could we also have the description support Markdown? Would be nice to have the ability to link to other resources.
> 
> Sounds good. I will add it to my backlog unless someone else wants to have a go.

I just raised a PR for this

**Comment by andreasbrett** [comment]
> Could we also have the description support Markdown? Would be nice to have the ability to link to other resources.

> Thanks for adding the markdown in the footer. I would also appreciate it if the markdown could be added in the description.

Your and my wish are my command... (https://github.com/louislam/uptime-kuma/pull/2806)

**Pull request merged**
