### PR TITLE
Removed redundant title in Pushover notification

### LINKED ISSUE #2542: Remove "Uptime Kuma Alert" string from notifications which support `Title` field
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Many of the notification providers support sending a `Title` field, allowing the user to specify a specific title that they'd like to see on the alert. Uptime Kuma leverages these where possible.

However even though the `Title` field is customizable, and Uptime Kuma provides ability for the user to modify this, it still sticks the "Uptime Kuma Alert" string in the text. In my opinion, this is redundant and only takes up space.

See example for Pushover: 

https://github.com/louislam/uptime-kuma/blob/775d1696fa22a129cda78998940eb3d938e2b3fb/server/notification-providers/pushover.js#L13

### ✔️ Solution

Remove the  "Uptime Kuma Alert" string from any notification agent which supports (and has implemented) a `Title` field.

### ❓ Alternatives

N/A - there is no current way to modify the message contents.

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SlothCroissant**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [ ] I have read and understand the pull request rules.

# Description

Fixes #2542

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I ran ESLint and other linters for modified files
- [X] I have performed a self-review of my own code and tested it
- [X] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [X] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

Old:

### CODE REVIEW

**Comment by louislam** [comment]
I agree the change. Press `Ready for review` if it is ready.

**Comment by SlothCroissant** [comment]
> I agree the change. Press `Ready for review` if it is ready.

Once I figure out how I can build a docker image from a local git branch, I'll confirm this works as expected :) If you have any tips, please let me know

**Comment by Computroniks** [comment]
You could try using the new docker pr testing feature described in the wiki https://github.com/louislam/uptime-kuma-wiki/blob/master/Test-Pull-Requests.md

**Comment by SlothCroissant** [comment]
> You could try using the new docker pr testing feature described in the wiki https://github.com/louislam/uptime-kuma-wiki/blob/master/Test-Pull-Requests.md

This was super helpful - didn't know this existed 😄

Should be all set, confirmed it looks great:

image

**Comment by SlothCroissant** [comment]
image

**Review by Computroniks — APPROVED** [review]

**Pull request merged**
