### PR TITLE
[2.0.X] Drop support for Alpine docker image

### PR DESCRIPTION
**Pull request by louislam**
# Description

As title, for 2.0.X only.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Translation update
- Other
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by 0x1a8510f2** [comment]
Why not just switch to the alpine image? Alpine tends to be the go-to choice for containers because it's small.

**Comment by mhkarimi1383** [comment]
Why? Alpine and NodeJS are good together
I think lots of users are using alpine images since it's more minimal and fast to deploy

**Comment by louislam** [comment]
Please search "Alpine" in the repo. There are a lot of  issues related to the Alpine base previously.

Also try to sesrch "alpine dns issue" in Google. You will find that it is almost a known issue.

Uptime Kuma was switched to debian-slim, it is more stable and small too.

**Comment by mhkarimi1383** [comment]
Oh I See
I thing that's because of Alpine is not GNU/Linux

**Comment by mhkarimi1383** [comment]
after marge of `2.0.X` I should have some changes in `ansible` branch

**Pull request merged**
