### PR TITLE
[Monitor Type] Real Browser with Keyword & Iframe Support

### LINKED ISSUE #4068: Allow keyword lookup in HTTP(s) - Browser Engine
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We have multiple angular sites, we can monitor with status codes, but it would be better to check for certain keywords. The normal keyword monitor is of no use - couse the whole page is rendered by javascript.
The Browser Engine Monitor-Typ shows a screenshot which is a good conformation, but doesnt get auto triggered if the page is not rendered at all or with an error.

### ✔️ Solution

Allow Keyword lookup in rendered dom tree.

### ❓ Alternatives

nothing comes to mind - if you have an alternative idea, please let me know.

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bthurlow**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Fixes #4068

Adds a real browser keyword monitoring type that has the ability to examine the content of iframes while looking for the keyword.

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)
image
image
image

### CODE REVIEW

**Comment by chakflying** [comment]
Formatting changes unrelated to a PR makes it impossible to review.

**Comment by chakflying** [comment]
Note that this conflicts with #3919.

**Comment by MarcAroni81** [comment]
Hi @bthurlow, any chance you can get into discussion with Louis ? I would really like to see that feature in Uptime Kuma.

BR and thanks for your efforts 
Marcus

**Comment by bthurlow** [comment]
@louislam If it suits you, once I can get back on this code base, I'll see about consolidating all the keyword code into a single method to make management and reuse much better.

cc: @MarcAroni81

**Comment by deckardstp** [comment]
Hi, As @MarcAroni81 stated, I would also really like to see that feature in a future version of Uptime Kuma.
Thanks for your work and best regards,
Seb

**Comment by CommanderStorm** [comment]
Extracting keyword and other checks is tracked in https://github.com/louislam/uptime-kuma/pull/3919
I think closing this PR is better. @chakflying do you agree?

**Comment by CommanderStorm** [comment]
> If it suits you, once I can get back on this code base, I'll see about consolidating all the keyword code into a single method to make management and reuse much better.

@bthurlow thanks for your work.
I am going to close the PR, as in the current state it is just not maintainable.
If you consolidate this into one monitor, we can reopen the PR or start of fresh in a new PR ^

**Pull request closed without merging**
