### PR TITLE
integrated the ego sms gateway for notifications, here in uganda

### PR DESCRIPTION
**Pull request by xankiiza**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [ ] I have read and understand the pull request rules.

# Description

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Review by xankiiza — COMMENTED** [review]
i have designed and added a new notification provider, egosms based here in uganda. the rest of the changes are unintended, and may be safely ignored

**Review by CommanderStorm — CHANGES_REQUESTED** [review]
Hi, thanks for the PR.
For me to be able to review this, two changes need to be mande.
Currently, this PR is not in a state in which I can effectively do this.

- > the rest of the changes are unintended, and may be safely ignored
  
  Please revert the changes which are uninteded.
  Reviewing 400+ changed files is not possible for me, even if they were intended.
  The changes seem like they are caused by an editor misconfiguration.
- Please include the screenshots that we ask in the contribution guide. https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#:~:text=new%20notification%20provider

**Comment by CommanderStorm** [comment]
I have changed this to a draft. Please change this back to a PR once you are ready.
If you have any problems or questions, feel free to reach out.

**Comment by kristianinc** [comment]
This was an issue with my editor. I deleted the project and resolved it. let me try doing this again.

**Pull request closed without merging**
