### PR TITLE
[ru-RU.js] nudge nodemailer strings; translate new ones

### PR DESCRIPTION
**Pull request by DX37**
# Description
Translate Nodemailer strings and translate new.

## Type of change
- Translation update

## Checklist

- [x] I ran ESLint and other linters for modified files
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by louislam** [comment]
Found some conflict keys with #1452. 

Should I merge @sovushik's pull request first, then merge your pull request?

**Comment by DX37** [comment]
> Found some conflict keys with #1452.
> 
> Should I merge @sovushik's pull request first, then merge your pull request?

I translated same new strings plus old one. But you can do that, I guess.

**Comment by louislam** [comment]
This pull request has been merged, but cannot show here.

Because I am learning the characteristics of git rebase, I rebased this pull request locally and merged into the master. 

You can see your commit in the master branch: https://github.com/louislam/uptime-kuma/commit/fd8cba1dad83912284d56f7524815f7946e88940

**Comment by DX37** [comment]
Ok, thanks.

**Pull request closed without merging**
