### PR TITLE
✨ add duplicate monitor button

### LINKED ISSUE #565: Possibility to copy a monitor
**Describe the solution you'd like**
Be able to open a Monitor in dashboard, and have a boton Copy in the same row as the Edit and Delete buttons. It would copy the whole configuracion, and maybe rename it adding a " - Copy" suffix

### PR DESCRIPTION
**Pull request by thomasleveil**
# Description

Fixes #565

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and test it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots 
Selection_411

### CODE REVIEW

**Comment by codeagencybe** [comment]
@louislam 
Is this feature already in the latest release? 
I just pulled latest Docker image but I don't have the duplicate button. 
I need to add roughly 80 tests and duplicating them makes it a lot easier and faster to process. 

Thanks!

**Comment by chakflying** [comment]
While this should work, I'm not sure using the querystring to pass around data is a good way of doing this. Seems to add a bit of duplicated logic and make the editMonitor code more complicated in the future. The data should already be in vue storage, so maybe we can copy it from there, or alternatively we can handle this server-side.

**Comment by louislam** [comment]
> While this should work, I'm not sure using the querystring to pass around data is a good way of doing this. Seems to add a bit of duplicated logic and make the editMonitor code more complicated in the future. The data should already be in vue storage, so maybe we can copy it from there, or alternatively we can handle this server-side.

image

Agree, just tested and the url is so long. I believe the query string approach is not a good way.

**Comment by adrianrudnik** [comment]
Maybe dump it into a "template" localeStorage and show the UI button if it is available, maybe include a title what the copy was made from?

**Comment by gaby** [comment]
@thomasleveil Any updates on this?

**Comment by thomasleveil** [comment]
@gaby I submitted this PR as a quick hack for my needs. But as stated above, the implementation does not fit current code base standards. Unfortunately I don't have any more time to put in this feature. 
I'm closing this so it does not clutter the PR list

**Pull request closed without merging**
