### PR TITLE
Added support for Gitpod.io and gpgkey for git

### PR DESCRIPTION
**Pull request by strausmann**
# Description

With the integration of Gitpod.io you can start a complete VSCode development environment in the browser. In addition, there is the possibility to sign the commits with a GPG key.

This makes development possible at any time and in any place with a browser.

- Added git commit with gpg signature support
- Added gitpod.io integration - allows to start a development environment in a few minutes

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I ran ESLint and other linters for modified files
- [X] I have performed a self-review of my own code and tested it
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

### CODE REVIEW

**Comment by louislam** [comment]
Nice pr, but there are similar issues with #1338. As `npm run setup` is for end user, it will download prebuilt files and dev tools will not be installed.

Please read my comment in https://github.com/louislam/uptime-kuma/pull/1338#issuecomment-1098628624 for more details.

**Comment by strausmann** [comment]
@louislam please check my merge request again, i hope now everything is to your satisfaction and nothing stands in the way of the merge.

**Comment by louislam** [comment]
Thanks! Just have a quick test. It seems that the frontend cannot connect to the backend server.

image

**Comment by strausmann** [comment]
Looks to me that it does not take the URL for the backend. With each port that is opened, Gitpod provides its own URL. But here it seems to expect a localhost address on port 3001.
Is it possible to pass the URLs for backend and frontend as Env variable?

**Comment by louislam** [comment]
> Looks to me that it does not take the URL for the backend. With each port that is opened, Gitpod provides its own URL. But here it seems to expect a localhost address on port 3001. Is it possible to pass the URLs for backend and frontend as Env variable?

Just checked, it is not possible currently. I think these functions below may have to handle Gitpod specially. 

image

**Comment by louislam** [comment]
Closed as I added support for GitHub Codespaces.

**Pull request closed without merging**
