### PR TITLE
Feat: Add SMTP DKIM settings

### LINKED ISSUE #1030: DKIM settings for SMTP notifications
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello,

Would it be possible to sign SMTP emails with DKIM?
This will increase the security of sending mail if the SPF and DMARC fields are correctly configured.
This also prevents emails from ending up in spam.

### ✔️ Solution

To make this possible, from an interface point of view in SMTP notifications, I see the addition of 3 fields:
- one for the domain,
- another for the DKIM key selector,
- and finally a field to be able to fill in the private key.

Technically modify the sending of emails in order to sign them with the information provided.

### ❓ Alternatives

_No response_

### 📝 Additional Context

Some sources on this technology :

https://wikipedia.org/wiki/DomainKeys_Identified_Mail

### PR DESCRIPTION
**Pull request by chakflying**
# Description

Closes #1030

This should just work as we just exposed the nodemailer's DKIM settings. I don't have a mailserver setup to test tho.

## Type of change

- User Interface
- New feature (non-breaking change which adds functionality)
- Translation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and test it
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

image

cc. @ilogus

### CODE REVIEW

**Comment by ilogus** [comment]
Hi @chakflying, I just tested your fork, everything is good on my side ! ✅

Here are some screens : 
dkim_test_01
dkim_test_02
dkim_test_03

If you want to test by yourself, and modify the options, contact me by email I could send you smtp credentials and a private key.

Thank you for this feature, in the hope that it will be fully validated !

**Comment by andreasbrett** [comment]
Awesome! Can't wait to see this in production.

**Comment by yeya** [comment]
@ilogus You should not post your private key or any part of it in public

**Comment by ilogus** [comment]
> @ilogus You should not post your private key or any part of it in public

Don't worry, this mailbox, the DNS record with the public key and the private key were only used for this test. In order to be able to take a picture of this for you

**Pull request merged**
