### PR TITLE
fix(ci): v2 Migration notice on ubuntu-latest label from `ubuntu-latest` to `ubuntu-24.04`

### PR DESCRIPTION
**Pull request by Zaid-maker**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

**BREAKING CHANGE**

Updating migration `ubuntu-latest` to `ubuntu-24.04` as per written in GitHub ***NOTICE***. These are affecting all runners from 5 Dec, 2024 to 17 Jan, 2025.

[Read the Blog here](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/)

## Type of change

Please delete any options that are not relevant.

- Breaking change (a fix or feature that would cause existing functionality to not work as expected)
- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by louislam** [comment]
I just read the blog. I think `ubuntu-latest` is not deprecated.

From my understanding, currently, `ubuntu-latest` is pointing `Ubuntu 22`, and will point to `Ubuntu 24` soon.

> Auto Test / auto-test (ubuntu-24.04, 18) (pull_request) Successful in 3m 

According to your test, our test is working fine on Ubuntu 24, so keep using `ubuntu-latest` should also be fine too.

**Comment by Zaid-maker** [comment]
My mis-understanding it's ***migration*** not ***deprecation***

> From my understanding, currently, ubuntu-latest is pointing to Ubuntu 22, and they will point to Ubuntu 24 soon.

No no, they are migrating the label of ubuntu-latest to just ubuntu-24.04

**Comment by Zaid-maker** [comment]
I think the status has some bugs on showing status of actions

image

But the jobs are looks fine...

image

**Comment by CommanderStorm** [comment]
> I think the status has some bugs on showing status of actions

Not a bug.
Louis has set the expected actions up as needed/expected for a merge.
Since the name has changed, they are no longer being run as far as github is concearned.

**Comment by louislam** [comment]
> No no, they are migrating the label of ubuntu-latest to just ubuntu-24.04 and ubuntu-22.04.

I just re-read the blog again, I still think my understanding is correct. 

> We will migrate the ubuntu-latest label to ubuntu 24 starting on December 5, 2024 

The sentence might be a bit confusing alone, but the word "migrate" here means that, migrate `22` to `24` for the `ubuntu-latest` tag, according to following paragraphs and content.


Also found more source: https://github.com/actions/runner-images/issues/10636

> Ubuntu-latest workflows will use Ubuntu-24.04 image

> Ubuntu 24.04 is ready to be the default version for the "ubuntu-latest" label in GitHub Actions and Azure DevOps.


So `ubuntu-latest` will still be available afterwards, pinning to 24.04 is not necessary.

**Comment by Zaid-maker** [comment]
This PR closed for now, and can be opened again in future. Thanks for clarification ♥️

**Pull request closed without merging**
