### PR TITLE
Issue/1138

### LINKED ISSUE #741: [K8s] Server fails to start in 1.9.0 (Solution in comment)
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Describe the bug**
First of thanks for your hard work. Really happy that there's someone on the community that understands the gap in today's open source, of not having a tool that reliably tracks uptime. I came from using statping and that was the closest I got to a good tool for uptime monitoring, barring performance issues.

Anyways on to the issue. I upgraded to 1.9.0 and realized that the pod no longer started. The logs below show the error it threw.

**To Reproduce**

1. Be running 1.8.0 before
2. Pull and run 1.9.0 with the same settings as before.

**Expected behavior**
Server starts

**Info**
Uptime Kuma Version:
Using Docker?: No but using Kubernetes
Docker version: NA
Node.js Version (Without Docker only):
OS: Linux 
Browser: NA

**Screenshots**

**Error Log**
It is easier for us to find out the problem.

```
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.9.0
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database no need to patch
Database Patch 2.0 Process
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1250:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1456:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

### LINKED ISSUE #845: [healthcheck error]: <Version 1.9.x onwards, the healthcheck.js script returns error status>
### 👟 Reproduction steps

running the command 'node extra/healthcheck.js' from inside the container returns 'Health Check ERROR' due to which the container is restarting with tcp connection refused error message.

I compared the script from version '1.8.0', its the same and returns 'Health Check OK' status

### 👍 Expected behavior

Health Check OK

### 👎 Actual Behavior

Health Check ERROR

### 🐻 Uptime-Kuma version

1.9.2

### 💻 Operating System

Linux

### 🌐 Browser

Chrome

### 🐋 Docker

_No response_

### 🏷️ Docker Image Tag

_No response_

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### LINKED ISSUE #895: ERR_SOCKET_BAD_PORT
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello,

I did run this on single node k3s cluster  , error as below and output from deployment . 
Same config works for me on microk8s cluster on raspberrypi 

kubectl logs uptime-kuma-8554c9f8-hj5pw -f
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.10.1
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
**Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1334:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1540:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues**

and here is deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2021-11-03T12:55:53Z"
  generation: 5
  name: uptime-kuma
  namespace: default
  resourceVersion: "2406351"
  uid: 6dd8fd45-8aa9-4b41-a3ec-80a299a72022
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-uptime-kuma
    spec:
      affinity: {}
      containers:
      - image: louislam/uptime-kuma:1
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 3001
          name: http-kuma
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/data
          name: kuma-pv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kuma-pv
        persistentVolumeClaim:
          claimName: kuma-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-03T12:55:53Z"
    lastUpdateTime: "2021-11-03T12:57:48Z"
    message: ReplicaSet "uptime-kuma-8554c9f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-08T18:12:08Z"
    lastUpdateTime: "2021-11-08T18:12:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

Best regards.

### 👟 Reproduction steps

deployment file provides in Description.
k3s cluster version
 kubectl get pods | grep kuma
uptime-kuma-8554c9f8-hj5pw   1/1     Running     0          5m52s
kubectl get nodes
NAME   STATUS   ROLES                  AGE     VERSION
okd    Ready    control-plane,master   7d22h   v1.21.5+k3s2

### 👀 Expected behavior

it works

### 😓 Actual Behavior

service start to listen on port 3001

**Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1334:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1540:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues**

### 🐻 Uptime-Kuma Version

image: louislam/uptime-kuma:1

### 💻 Operating System and Arch

ubuntu 20.04 k3s kubernetes

### 🌐 Browser

Firefox

### 🐋 Docker Version

K3S

### 🟩 NodeJS Version

None

### 📝 Relevant log output

```shell
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.10.1
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1334:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1540:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

### LINKED ISSUE #1040: after 4 months with no issues today: This site can’t be reached anymore ....
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My Uptime-Kuma is running in a rancher environment with no issues for 4 months. I shutdown the server for 2 weeks and on reboot yesterday, the container runs but I cannot access the web page, error message "ERR_CONNECTION_REFUSED".

Logs show the following:
Version: 1.11.1
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1336:12 {
  code: **'ERR_SOCKET_BAD_PORT**'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Chrome

### 🐋 Docker Version

Rancher 2.4-6254-head

### 🟩 NodeJS Version

No

### LINKED ISSUE #1118: ERR_SOCKET_BAD_PORT on Node.js
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello!
I installed it according to the instructions, but the application didn't open. In the logs:

> Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.11.1
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
at new NodeError (node:internal/errors:371:5)
at validatePort (node:internal/validators:216:11)
at Server.listen (node:net:1461:5)
at /home/lylab/swifty.support/monitor/server/server.js:1336:12 {
code: 'ERR_SOCKET_BAD_PORT'
}
at process.<anonymous> (/home/lylab/swifty.support/monitor/server/server.js:1542:13)
at process.emit (node:events:390:28)
at emit (node:internal/process/promises:136:22)
at processPromiseRejections (node:internal/process/promises:242:25)
at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues

I contacted support, they said that ports 3000 and 3001 are open.

What am I doing wrong, what could be the problem?
Thanks!

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Linux web772.default-host.net 3.10.0-962.3.2.lve1.5.63.el7.x86_64 #1 SMP Fri Oct 8 12:03:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### 🌐 Browser

Chrome, Version 96.0.4664.110 (Official Build) (64-bit)

### 🐋 Docker Version

_No response_

### 🟩 NodeJS Version

16.13.1 LTS

### LINKED ISSUE #1138: Introduction of new environment variables for HOST and PORT add non-overridable regression to kubernetes deployments
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The introduction of UPTIME_KUMA_PORT introduces a regression in kubernetes deployments, if the deployment is called "uptime-kuma" kubernetes will auto-generate the environment variable UPTIME_KUMA_PORT with a non-parsable value for parseInt()

image

The commit that introduces environment variable parsing is here:
https://github.com/louislam/uptime-kuma/commit/f75c9e4f0ca4f7417ea0c7f2184be4dd1332be05#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R75

Similar issue reported here:

- https://github.com/louislam/uptime-kuma/issues/741
- https://github.com/louislam/uptime-kuma/issues/1040
- https://github.com/louislam/uptime-kuma/issues/1118 (no real / feasible resolution in ticket)

Similar issue in helm repository:
https://github.com/dirsigler/uptime-kuma-helm/issues/26 (has the name of the deployment set to "uptime-kuma", see `kubelet                  Created container uptime-kuma`)

Similar issue with redis:
https://github.com/kubernetes/kubernetes/issues/60099#issuecomment-384767701

JavaScript will only "skip" the values, if they are not set with the current implementation, but produces a NaN value, if one of the values inside the else-shorthand is set.

image

As a proposal, please either change the order in which the parameters are parsed (so it can be overridden in the deployment manifest in kubernetes) or implement it with validation, e.g. like this:

    const port = [process.env.UPTIME_KUMA_PORT, process.env.PORT, args.port, 3001].map(el => parseInt(el)).find(el => !isNaN(el));

image

### 👟 Reproduction steps

- Create an environment variable named UPTIME_KUMA_PORT with a non-integer value
- Start server

### 👀 Expected behavior

Uptime Kuma will fall back to the next parsable integer value in the priority list
(UPTIME_KUMA_PORT -> PORT -> ARGS.PORT -> 3001)

### 😓 Actual Behavior

Uptime Kuma crashes with the port being NaN

### 🐻 Uptime-Kuma Version

1.11.1-alpine

### 💻 Operating System and Arch

node:14-alpine3.12

### 🌐 Browser

none

### 🐋 Docker Version

k8s

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

```shell
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1336:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Shutdown requested
Called signal: SIGTERM
Stopping all monitors
Trace: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (internal/errors.js:322:7)
    at Server.close (net.js:1624:12)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Closing the database
SQLite closed
Graceful shutdown successful!
```

### PR DESCRIPTION
**Pull request by marcules**
# Description

Fixes #1138, fixes #1118, fixes #1040, fixes #895, fixes #845, fixes #741
Fixes dirsigler/uptime-kuma-helm#26

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and test it
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by marcules** [comment]
@louislam @chakflying I also changed the argument order / parsing order, so "most specific" (passed command line arguments) wins for host, port and ssl-stuff instead of env-vars winning over passed arguments.

Hope that is fine with you too.

**Comment by chakflying** [comment]
The `UPTIME_KUMA_` ones are added to override any default env generate by other systems, so they should be in front. But I agree `args` should have a higher priority.

**Comment by marcules** [comment]
@chakflying I changed it to the suggested priority now

`args` -> `UPTIME_KUMA_`-env -> generic-env -> fallback value where applicable

**Comment by marcules** [comment]
@chakflying @louislam any thoughts on this?

**Comment by louislam** [comment]
For changing the priority. It might be a breaking change for someone who set both arg and env var with different values.

I guess it should be not common, will remark it the changelog.

**Pull request merged**
