### PR TITLE
Remove template comment in SECURITY.md

### PR DESCRIPTION
**Pull request by SIMULATAN**
# Description
This PR removes a leftover comment from the security template in the `SECURITY.md` file

## Type of change
- Wiki/Docs-Update

## Screenshots
screenshot of the leftover line

### CODE REVIEW

**Review by Computroniks — APPROVED** [review]
`npm run lint` passes. There seems to be an issue with the github actions and an external service returning 503 so it is failing. Nothing to to with your PR though.

**Comment by louislam** [comment]
> `npm run lint` passes. There seems to be an issue with the github actions and an external service returning 503 so it is failing. Nothing to to with your PR though.

Yes, everyone suffer from the issue for more than 3 hours.
https://github.com/bahmutov/npm-install/issues/80

It is also the reason why I don't put the whole deployment process or write any complicated steps on GitHub Actions. If GitHub Actions goes wrong, then you cannot run those steps in other environments. It is a good time to say GitHub Actions is a bad thing.

**Comment by SIMULATAN** [comment]
According to the GitHub Statuspage, "GitHub Actions is experiencing degraded performance". Maybe this is related?

**Comment by Computroniks** [comment]
> According to the GitHub Statuspage, "GitHub Actions is experiencing degraded performance". Maybe this is related?

Yep. It is a cache issue that causes the 503 error

**Pull request merged**
