### PR TITLE
Added clean monitor table for smaller screens

### PR DESCRIPTION
**Pull request by Ponkhy**
I added a different and more clean table style for smaller mobile screens. 
Because on some devices it looked pretty compressed, see **Example 1**.
You can see the new table style in **Example 2**. It will only appear on a screen width smaller than 550px.

**Example 1:**
Example1

**Example 2:**
Example2

### CODE REVIEW

**Comment by Ponkhy** [comment]
This should be done now or are there any suggestions?

**Comment by louislam** [comment]
> This should be done now or are there any suggestions?

Overall is great. The row spacing in Details.vue maybe too big?

image

**Comment by Ponkhy** [comment]
Alright, i'll work on that tomorrow!

**Comment by Ponkhy** [comment]
Okay, i've reduced the row spacing while not making it look too compressed.
I also centered the badge, cause also the margin-top still applied on the Details page before.

**Comment by chakflying** [comment]
Just as an experiment, how do you feel about making the pill full width and making the title bold?

image

**Comment by Ponkhy** [comment]
I really like the idea making the title bolt.
I think making the badge full width looks a bit "overwhelming", so i got another idea, how about this?

Idea01

**Comment by chakflying** [comment]
@Ponkhy Nice! I'm ok with that too.

**Comment by Ponkhy** [comment]
@chakflying Alright, I added the commit [`a17c14e`](https://github.com/louislam/uptime-kuma/pull/236/commits/a17c14ea1c143f47f49f3385b3d8ce0e81a58c37) and also made the title bolt.

If you have a better approach on the change feel free to correct it!

**Comment by louislam** [comment]
Dimmed the color of border line, if it is ok, I will merge to master branch.

image

**Comment by Ponkhy** [comment]
@louislam For the dark mode i totaly agree!
Unfortunately it looks too dark on the light mode.
Are you adjusting it for the light one or should i?

LightModeBorder

**Comment by louislam** [comment]
> @louislam For the dark mode i totaly agree!
> Unfortunately it looks too dark on the light mode.
> Are you adjusting it for the light one or should i?
> 
> LightModeBorder

That is unexpected. I thought I added inside .dark....

**Comment by louislam** [comment]
image

Just recheck, it is ok in my side. Strange.

**Comment by Ponkhy** [comment]
Ohh i'm sorry it's my false, i didn't read and pull properly.
Yes we're good now, looks perfect!

**Pull request merged**
