### PR TITLE
Adding Reverse Proxy Examples: Requested in Issue #3

### PR DESCRIPTION
**Pull request by Stetsed**
Added reverse proxy examples for Caddy, Nginx with and without Certbot, And Apache.

### CODE REVIEW

**Comment by TheGuyDanish** [comment]
@louislam Maybe adding a wiki to the project would be good for this kind of documentation so we don't clutter the README, thoughts?

**Comment by Stetsed** [comment]
> @louislam Maybe adding a wiki to the project would be good for this kind of documentation so we don't clutter the README, thoughts?

I think this would be a better idear as you say to avoid clutter in the README.

**Comment by louislam** [comment]
> @louislam Maybe adding a wiki to the project would be good for this kind of documentation so we don't clutter the README, thoughts?

Agree with you, I just enable wiki in this repo, free feel to put in there

**Comment by 12nick12** [comment]
Add 'proxy_http_version    1.1;' to the nginx with SSL config example

**Pull request closed without merging**
