### PR TITLE
add: indonesian-translation

### PR DESCRIPTION
**Pull request by syofyanzuhad**
Can you please add a `hacktoberfest-accepted` label ?

### CODE REVIEW

**Comment by louislam** [comment]
Thanks, but isn't it already existing?

https://github.com/louislam/uptime-kuma/blob/9d364b28b1dbe0da887df8048e4d7760cde1331b/src/languages/id-ID.js

cc: @KangAlleW @januridp

**Comment by januridp** [comment]
Yup! And it's enough for Bahasa no need to added. Except there's some fixing and I'll review it. This can be closed. @louislam

**Comment by louislam** [comment]
Thanks for your work, but unfortunately it is duplicate.
Duplicate of #678 and #715

**Comment by syofyanzuhad** [comment]
> Thanks for your work, but unfortunately it is duplicate.
> Duplicate of #678 and #715 

Thanks bro, I thought when I was working on it there wasn't that file

**Pull request closed without merging**
