### PR TITLE
Link pm2 to /usr/bin in Local install option script

### PR DESCRIPTION
**Pull request by kiraitachi**
Under Oracle Linux or Red Hat Enterprise Linux release 9.0 (Plow) pm2 is not install globally even if installed with "npm i -g pm2". So when running "pm2 start server/server.js --name uptime-kuma" this will try to run pm2 with normal user and not have access to run it in /opt (as it needs root access), if run with sudo "sudo pm2" you will get "command not found" as its not installed globally so root has no access to pm2.

In order to fix this you will need to link the output of "whereis pm2" to /usr/bin.

This is the most probable cause for this issue https://github.com/louislam/uptime-kuma/issues/1041

More info here: https://stackoverflow.com/questions/38185590/pm2-command-not-found

Not a developer hopefully it somewhat follows the pull request procedure as its not any "impactful" code change.

Thanks for your time and efforts.

⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Translation update
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by Saibamen** [comment]
Please change PR title

**Comment by kiraitachi** [comment]
@Saibamen just did, hopefully this title is clearer? If not any suggestions?

**Comment by kiraitachi** [comment]
@Saibamen just did, hopefully this title is clearer? If not, can you be clear on what do you suggest changing the title to?

Cheers!

**Comment by louislam** [comment]
As the first line mentioned:
> # install.sh is generated by ./extra/install.batsh, do not modify it directly.

Also, I can't predict how will be happened if the `ln` command be executed on other Linux distros. I think it should be executed only if Oracle Linux or Red Hat Enterprise Linux.

**Pull request closed without merging**
