### PR TITLE
Fix: Make sure browser is connected before returning

### LINKED ISSUE #4373: Bug on Browser Engine: `browser.newContext: Target page, context or browser has been closed.`
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I get this error with the browser engine checks: 

```log
browser.newContext: Target page, context or browser has been closed. 
```

The Checks using the Browser Engine work great for an initial period of time and then all of the checks using the browser engine start to fail at the same time and never recover.

### 👟 Reproduction steps

Configure Browser Engine monitor

### 👀 Expected behavior

To continue to work

### 😓 Actual Behavior

return the error : 

```log
browser.newContext: Target page, context or browser has been closed
```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12.4

### 🌐 Browser

Brave v1.61.116

### 🐋 Docker Version

K8s 1.27.7

### 🟩 NodeJS Version

_No response_

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chakflying**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

Maybe Fixes #4373, but haven't tried to reproduce it.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [ ] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by CommanderStorm** [comment]
From glancing at it, it seems you found the bug of a missing await in #4418
=> is this not more likely?
are there cases where we can be not connected anyhow?

**Comment by chakflying** [comment]
Remote browser should not be available in `1.23.X` if I remember correctly.

**Comment by chakflying** [comment]
As to why it might be disconnected, I suppose there could be many reasons, like the OS killing the process because of OOM or it crashed because of some other reason. But I'm also not sure if the connected status would accurately reflect these situations.

**Comment by louislam** [comment]
I believe so, hope `isConnected()` is trustworthy.

**Pull request merged**
