### PR TITLE
Fix: clear important beats after deleteMonitor

### LINKED ISSUE #433: Dashboard log shows no name for deleted items.
image

Deleted monitors should be handled better. Either remove them from the log completely (probably?, though audit trail?), or show them in the log.

### PR DESCRIPTION
**Pull request by chakflying**
Closes #433

So uhhh... apparently foreign keys have not been turned on this whole time 😂
Might be why some people are seeing bigger database file than expected.

### CODE REVIEW

**Comment by louislam** [comment]
I believe foreign key is enabled by default.

If not, I may need to review all patch sql files. It may have a chance that it turned foreign key off and not turn it back on.

**Comment by chakflying** [comment]
Did a quick search and the old patch files looks fine. I guess I'll check again later with a clean database to make sure I didn't somehow break the config before.

**Comment by chakflying** [comment]
Okay tested FK delete cascade works on a clean database. I must have broke it during development. Do you think it's safer to just leave that line in anyway?

**Comment by louislam** [comment]
> To minimize future problems, applications should set the foreign key enforcement flag as required by the application and not depend on the default setting.

https://www.sqlite.org/pragma.html#pragma_foreign_key_check

Just read the official doc, they actually suggest that it should not depend on the default setting, so it is good to keep.

**Pull request merged**
