### PR TITLE
Slack notification block not working

### PR DESCRIPTION
**Pull request by pruekk**
# Description

This PR creates for solving the slack notification as the block is not working. I screenshot some images below.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Before change
image_before

After change
image_after

### CODE REVIEW

**Comment by pruekk** [comment]
Hi @louislam - Could you please take a look at this PR?

**Review by Computroniks — APPROVED** [review]

**Comment by Computroniks** [comment]
I think the problem is here. https://github.com/louislam/uptime-kuma/blob/73fa6a1dee397f03a4d664f54624de93e909bda2/server/notification-providers/slack.js#L83-L96

This hasn't been updated to handle the new structure of `data`

**Comment by pruekk** [comment]
@louislam Can you provide me the step to reproduce your issue? I will investigate it.

**Comment by louislam** [comment]
1. A simple slack notification
2. Down a HTTPS monitor

image

**Comment by pruekk** [comment]
@Computroniks @louislam  Thanks for your cooperation.

**Comment by louislam** [comment]
> TypeError: Cannot read properties of undefined (reading 'push')

Still not working. please be sure to test UP / DOWN notifications first.

**Comment by pruekk** [comment]
@louislam I have tested both UP / DOWN. I realize that I forgot to loop through the attachment. In this case, We can do 2 ways
- loop through attachments (I pick this one)
- fix attachments[0] and push blocks inside

**Pull request merged**
