### PR TITLE
refactor: removed fs-rmsync extra func used for node <14

### PR DESCRIPTION
**Pull request by tanmay4u02**
Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

A todo task:
Removed the ```extra/fs-rmSync``` function since it is not required once Node 14 and 16 support is dropped
And replaced its calls by ```fs.rmSync``` calls

As mentioned in the Todo comment in line no. 7 of the function itself https://github.com/louislam/uptime-kuma/blob/da168fc22082a4bdeae313ba90e0596366ecf87b/extra/fs-rmSync.js#L7

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

@louislam

### CODE REVIEW

**Comment by tanmay4u02** [comment]
@louislam @CommanderStorm 

Should I remove this script command as well in this PR?

https://github.com/louislam/uptime-kuma/blob/da168fc22082a4bdeae313ba90e0596366ecf87b/package.json#L72

**Comment by CommanderStorm** [comment]
> Should I remove this script command as well in this PR?

That would be appreciated 👍 
Otherwise, the PR looks good to me

**Comment by tanmay4u02** [comment]
> > Should I remove this script command as well in this PR?
> 
> That would be appreciated 👍 Otherwise, the PR looks good to me

Thank you @thomasleveil

removed it and marking the PR as ready for review

https://github.com/louislam/uptime-kuma/pull/3747

**Review by CommanderStorm — APPROVED** [review]
Thanks for the enhancement ♥️

**Pull request merged**
