### PR TITLE
Add axios error message

### PR DESCRIPTION
**Pull request by ericchanky**
# Description

add more detailed message on axios error

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and test it
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here and it will be uploaded automatically.

### CODE REVIEW

**Comment by Saibamen** [comment]
Please add example of before/after messages

**Comment by Saibamen** [comment]
Should we include both `error.message` and `JSON.stringify(error.response.data)` if `axios.isAxiosError(error)` is true?

**Comment by ericchanky** [comment]
yes, I also think about that. Do you have any suggestion on the format? maybe like this

before
```
Request failed with status code 500
```
```
connect ECONNREFUSED 127.0.0.1:3000
```

after
```
Request failed with status code 500, {"error": "application error message"}
```

**Comment by Saibamen** [comment]
`Message: ${error.message}. Response: ${JSON.stringify(error.response.data)}`?
`Error message: ${error.message}. Response: ${JSON.stringify(error.response.data)}`?

**Review by Saibamen — APPROVED** [review]

**Review by chakflying — APPROVED** [review]

**Comment by louislam** [comment]
I think it quickly increases the database size if websites go down.

Saving a whole response content into the database is not recommended.

**Comment by Saibamen** [comment]
OK, but IMO we should log full exception (console.error() or log file) and send it by notifications

**Review by lucalves — APPROVED** [review]

**Comment by louislam** [comment]
> I think it quickly increases the database size if websites go down.
> 
> Saving a whole response content into the database is not recommended.

Close because of it and seems staled.

**Pull request closed without merging**
