### PR TITLE
"Test" button when configuring a monitor

### LINKED ISSUE #2725: "Test" button when configuring a monitor
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When configuring a new monitor, I sometimes find myself wanting a more "precise" (for example, HTTPs + Keyword instead of HTTPs) uptime detection for a host that is known to be up when the monitor is configured. It would be nice to be able to test that without having to save to see the result.

### ✔️ Solution

There should be a "Test" button in the monitor Add/Edit page to test if it's considered up or down with the current settings.

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by gitstart**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #2725 
Implemented the test button functionality based on previous logic.

## Type of change

Please delete any options that are not relevant.
- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings

## Screenshots (if any)
https://user-images.githubusercontent.com/1501599/221173846-dc8778f0-998b-4a4b-8755-53d6f12e046d.mp4

### CODE REVIEW

**Comment by chakflying** [comment]
Doing it this way is terrible for maintainability. It would also lead to weird bugs if future changes to the monitor forgot to modify either part of the code.

**Comment by gitstart** [comment]
@chakflying  We know that it is duplication of code and is hard to maintain. That is why we started it as a Draft because this was the most straightforward way to avoid modification of already implemented methods and just add new code.
To avoid duplication maybe there could two possible ways:
1. To extract the beat function and use the same function in both start() and test() methods. Using this way, we should pass a flag to indicate whether we are testing a monitor or starting it. Starting a monitor change some values in the database but for testing it is not needed. So ,the flag will be used for this purpose.
2. The second way is to extract the whole logic from Monitor and put it within a function. The function will take monitor as its param then return the monitor status.

**Comment by louislam** [comment]
Regardless of code duplication, the UI/UX is correct.

My sudden idea on how to be "less scary" and without moving large part of existing code:

```js

class Monitor extends BeanModel {

   ...

    test(io) {
         this.start(io, true)
    }

    start(io, dryRun = false) {
        ....

        // If dryRun, do not create a interval, do not insert into database
       
        // For example:
       if (!dryRun) {
            await R.store(bean);
        }

        ...
    }

    ...
}

```


By adding a `dryRun` parameter in `start`, we can determine which operations should be used for Test button inside `start()`.

In this way, I think it won't touch too many things and it won't have a large code conflict with other pull requests.

**Comment by gitstart** [comment]
There shouldn't be these much file changes, that's weird. 🧐

**Comment by louislam** [comment]
Well... I think you used git square merge from my master branch to your branch.

If you didn't write new code in 2nd/3rd commits here. Hard reset your head back to your 1st commit here and do a rebase merge instead of square merge.

**Comment by mabed-fr** [comment]
RED for fail and green for OK ? not ?

**Comment by louislam** [comment]
> Well... I think you used git square merge from my master branch to your branch.
> 
> If you didn't write new code in 2nd/3rd commits here. Hard reset your head back to your 1st commit here and do a rebase merge instead of square merge.

It looks like the branch was messed up, feel free to re-create a new pull request for that.

**Pull request closed without merging**
