### PR TITLE
Feat: Improve Certificate Info Display

### PR DESCRIPTION
**Pull request by chakflying**
In response to #514, improve the certificate info display such that the full chain is shown. Hopefully can help with debugging similar situations in the future.

Unfortunately the Certificate Icon is a premium icon in Font Awesome.

|light|dark|
|----|----|
|image|image|

### CODE REVIEW

**Comment by Neer171** [comment]
@chakflying  here is font awesone SSL icon

`<i class="fab fa-expeditedssl"></i>`


https://fontawesome.com/v5.15/icons/expeditedssl?style=brands

**Comment by louislam** [comment]
Am I doing it right?😂

https://jsfiddle.net/or5yp30L/10/

image

**Comment by chakflying** [comment]
Damn that totally works! Icon updated.

**Comment by Neer171** [comment]
https://jsfiddle.net/NomadNick/7u8seLgy/1/

**Comment by chakflying** [comment]
Appreciate the effort, but I think the current one is fine.

**Comment by louislam** [comment]
Fixed a bug related to this pr: cac0a46

If the cert is still the old format, it throws error.

Might have to ensure `.certInfo` in the object, or clearing the old json?

**Comment by chakflying** [comment]
Thanks! Is it okay now, or do you want me to add a db patch with `DELETE FROM monitor_tls_info`?

**Pull request merged**
