### PR TITLE
Lint some files and update languages/fr-FR.js

### PR DESCRIPTION
**Pull request by Limerio**
# Description

Fixes #(issue)
(title of my pull request)

## Type of change

- Translation update
- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Review by Computroniks — CHANGES_REQUESTED** [review]
Please don't just copy over the english translations into the other languages. It makes no difference to the application as it will fallback to english if no other option is found and only leads to merge conflicts with other translation PRs as well as making PRs harder to review.

**Comment by Limerio** [comment]
I go to patch that sorry I don't understand why there is this problem

**Comment by Limerio** [comment]
I had run `npm run update-language-files` I think this script add this lines

**Comment by Computroniks** [comment]
Yep, that the one

**Comment by Limerio** [comment]
okay i understand now anyway i'm patching this

**Comment by Limerio** [comment]
I think it's good now

**Comment by Limerio** [comment]
I'm french too 
And if you translate "monitor" in French "sonde" it's not the great word so for me "moniteur" and if you use a online dictionary or a translate tool you can see there is a great word

**Comment by louislam** [comment]
There are too many changes, I am afraid that I don't have time to check it.
I suggest this pr should just update fr-FR.js only and leave other files unchanged.

**Comment by Limerio** [comment]
If you want, it's ur project ^^

**Comment by louislam** [comment]
> There are too many changes, I am afraid that I don't have time to check it. I suggest this pr should just update fr-FR.js only and leave other files unchanged.

Close as this reason.

**Pull request closed without merging**
