### PR TITLE
Feat: Badges generator

### PR DESCRIPTION
**Pull request by jensneuber**
# Description

As mentioned in https://github.com/louislam/uptime-kuma/pull/1119 a generator for monitor badges would be nice to have.

A first draft of what this might look like ( with a little inspiration from my side, see screenshot) should be open for discussion in this PR.

### Open questions:

* Where should the generator be located? 
	Initial idea was the edit panel.
	https://github.com/louislam/uptime-kuma/pull/1712#issuecomment-1144589799
* Should (parts of) it be collapsible? 
	When all form fields are visible the generator takes up a lot of space.
* Should selected values be saved?
	Right now all changes are lost on reload. This might be on purpose

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)
image

### CODE REVIEW

**Comment by chakflying** [comment]
> Where should the generator be located?

I'd prefer adding a button in `Details.vue` to a separate page to not complicate the EditMonitor page any further than necessary.

**Comment by CommanderStorm** [comment]
@jensneuber Just checking in:

What is needed to get this PR ready for review? (apart from a pretty brutal rebase)
Is there something I can help with?

Asking the hard questions:
Given the huge number of changes to this repository: Is this PR still salvageable?

**Comment by jensneuber** [comment]
I am still willing to finish this ( thanks @louislam for un-staling it ), but my current situation leaves little room for side tasks. 
This will change and i will continue an this.

**Comment by CommanderStorm** [comment]
@jensneuber given that #2915 is [nearing the merge](https://github.com/louislam/uptime-kuma/milestone/31), would you consider closing this PR?

**Comment by jensneuber** [comment]
#2915 Looks fantastic!
No need to add sth from this ancient PR.

**Comment by jensneuber** [comment]
> @jensneuber I'm sorry for duplicate PR. I don't know that you have already done it.

No hard feelings on my side! I am sorry to not have finished up on what I started and feel glad that someone else was willing to do it.

So thanks @kiznick ❤️

**Pull request closed without merging**
