### PR TITLE
Added option for notification provider ntfy to use access tokens

### PR DESCRIPTION
**Pull request by Sharknoon**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

The Notification Provider `ntfy` can accept two ways of authorization: `Basic` and `Bearer` ([Docs](https://docs.ntfy.sh/publish/#access-tokens)).

Uptime Kuma had only support for the `Basic` Authorization with Username and Password. I have added the `Bearer` Authorization with a Access Token.

I have tested the `Bearer` Authorization on my self-hosted `ntfy` instance and it works fine.

## Type of change

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Authentication method selection:
Screenshot_1

Fields when Access Token method is selected:
Screenshot_2

Fields when Username and Password method is selected:
Screenshot_3

### CODE REVIEW

**Comment by Sharknoon** [comment]
@louislam Do you have any questions regarding this PR? Is there anything I can help you with?

**Comment by chakflying** [comment]
Would it be more clear if there is a select drop-down for `authentication method`, and hide/show the corresponding input fields?

**Comment by Sharknoon** [comment]
Yes, good idea, I am working on it

**Comment by Sharknoon** [comment]
I have finished the dropdown for selecting the `authentication method`. I hope this change corresponds to your ideas. Please let me know, if you have any further change requests. Thank you :)

**Review by chakflying — APPROVED** [review]
Tested working okay.

**Comment by Sharknoon** [comment]
I have updated the screenshots in order to reflect the recent changes.

**Comment by ksurl** [comment]
it looks like 1.21.3 should have included this PR since it's been merged but I don't get the dropdown option for ntfy when adding a new notifier type.

**Comment by louislam** [comment]
This pr merged to the 1.22.0 branch, so it is not available yet.

**Pull request merged**
