### PR TITLE
Vietnamese translation update

### PR DESCRIPTION
**Pull request by mrphuongbn**
Translation update for the new features and making some smoothly.
Fix Syntax error.

### CODE REVIEW

**Comment by louislam** [comment]
I just realized that GitHub's "File changed" feature is not reliable at all.

I think it is the same as https://github.com/louislam/uptime-kuma/pull/853?

**Comment by mrphuongbn** [comment]
> I just realized that GitHub's "Files changed" feature is not reliable at all.
> 
> I think it is the same as #853?

Yay. Just "Files changed" ^^
I update a lot of things, bro. Not the same.

**Comment by mrphuongbn** [comment]
> I just realized that GitHub's "Files changed" feature is not reliable at all.
> 
> I think it is the same as #853?

Yay. "Files changed" ^^
I updated a lot of things, bro. Not the same.

**Comment by chakflying** [comment]
Then you might have pulled the wrong branch, since this file is exactly the same as the one on master.

**Comment by louislam** [comment]
> this file is exactly the same as the one on master

Yes, so I close it.

**Pull request closed without merging**
