### PR TITLE
Translations update from Uptime Kuma Weblate

### PR DESCRIPTION
**Pull request by UptimeKumaBot**
Translations update from [Uptime Kuma Weblate](https://weblate.kuma.pet) for [Uptime Kuma/Uptime Kuma](https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Not Completed Still Working <3

**Comment by Zaid-maker** [comment]
its 38% done! when the bot gonna pull new changes?

**Comment by Zaid-maker** [comment]
@louislam when u gonna merge this?

**Comment by louislam** [comment]
> @louislam when u gonna merge this?

I usually merge these before release. For this, I probably will merge before `1.21.0-beta.0` will be released.

**Comment by IAmADev78** [comment]
> > @louislam when u gonna merge this?
> 
> I usually merge these before release. For this, I probably will merge before `1.21.0-beta.0` will be released.

ok thanks for the information i will complete  the translation before it <3

**Comment by Zaid-maker** [comment]
> > @louislam when u gonna merge this?
> 
> I usually merge these before release. For this, I probably will merge before `1.21.0-beta.0` will be released.

ok thank u so mucb <3
i will complete the translation before the beta release

**Pull request merged**
