### PR TITLE
basic darkmode

### PR DESCRIPTION
**Pull request by philippdormann**
mostly based on css variables

### CODE REVIEW

**Comment by philippdormann** [comment]
don't be shocked by the amount of commits, needed to cherry pick because i have some more changes lying around ^^
the changed files are correct

**Comment by louislam** [comment]
> don't be shocked by the amount of commits, needed to cherry pick because i have some more changes lying around ^^
> the changed files are correct

Thank you! I also read your other commits and find out that changing to node:alpine can reduce the container size!

**Comment by louislam** [comment]
I just tested it. Unfortunately, it breaks the light theme. And I prefer that users can choose light/dark theme in the settings. I will improve it later. Thank you for your pull request.

**Comment by philippdormann** [comment]
ouhh, that's a bummer.... sorry for the inconveniences 😬 will check the light mode later today and send a new PR.

maybe we can do a quick voting in an issue on how the darkmode toggle should work (application settings vs system preferences)

imho it should be based on system settings via `prefers-color-scheme` media query

**Pull request merged**
