### PR TITLE
Prepare for using Weblate

### LINKED ISSUE #1034: Easier translation process
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Nowadays, translations often lack of translated lines. Checking the English language file for additional lines is not an optimal solution. It would be handy if translation could be done by https://localazy.com/ or https://www.transifex.com/open-source/

Also, that would eliminate potential translation/code breakage if a contributor forgets to add a comma at the end of a line.

### ✔️ Solution

Use TMS platform to streamline translation process. Transifex for open-source projects is free, there is also a localazy.

### ❓ Alternatives

Switch up to standard .po and .mo files, that would enable translation by poedit and similar software.

### 📝 Additional Context

_No response_

### LINKED ISSUE #1873: javascript language file to json for translate correctly to es, fr and it
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Can u share me json file of en.js language?

### ✔️ Solution

https://www.convertsimple.com/convert-javascript-to-json/
but is not correctly formatted

### ❓ Alternatives

share en.js to en.json

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by YehowahLiu**
- [x] I have read and understand the pull request rules.

# Description
As mentioned in #1591 , we decided to try weblate as translation platform.
I have converted the translation file to json format, and it works with `vue-i18n`. 

Following tasks:
- [ ] Set up translation workflow on [Weblate](https://weblate.kuma.pet/)
- [x] Edit docs to refuse further translation pr (should use weblate then)
- [ ] Clean up the code, remove previous js translation file, and my convert script, etc

close #1034
close #1873

## Type of change

- Translation update
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by YehowahLiu** [comment]
To setup in weblate, you should give me some permission( [Here](https://weblate.kuma.pet/user/YehowahLiu/) is me).
I'll try to setup a demo project with my branch to avoid potential side effects.

**Comment by louislam** [comment]
> To setup in weblate, you should give me some permission( [Here](https://weblate.kuma.pet/user/YehowahLiu/) is me). I'll try to setup a demo project with my branch to avoid potential side effects.

I checked this option, see if it is ok. 

image

**Comment by YehowahLiu** [comment]
> I checked this option, see if it is ok.
 
It seems ok, will try to setup a demo project later.

**Comment by YehowahLiu** [comment]
I need your help to continue.
My demo project stuck [here](https://weblate.kuma.pet/progress/demo-project/demo-component) with no log.
image

I have tested my project/compone settings with weblate docker container on my laptop, which will log the process of updating component, then success to load languages.
image

I have checked the settings of `weblate.kuma.pet` to locate the problem, only find out that Celery is not configured. Maybe that's the reason.
Also you can check the log to get detailed error message.

**Comment by louislam** [comment]
How to config Celery? 

Here is the docker-compose
```yaml
version: '3.8'
services:
  weblate:
    image: weblate/weblate
    tmpfs:
    - /app/cache
    volumes:
    - weblate-data:/app/data
    restart: always
    depends_on:
    - database
    - cache
    deploy:
      placement:
        constraints: [node.hostname == panel6]
    environment:
    - WEBLATE_SITE_DOMAIN=weblate.kuma.pet
    - WEBLATE_DEBUG=1
    - WEBLATE_LOGLEVEL=DEBUG
    - WEBLATE_SITE_TITLE=Uptime Kuma Weblate
    - WEBLATE_ADMIN_NAME=Louis Lam
    - WEBLATE_ADMIN_EMAIL=<MASKED>
    - WEBLATE_ADMIN_PASSWORD=<MASKED>
    - WEBLATE_SERVER_EMAIL=<MASKED>
    - WEBLATE_DEFAULT_FROM_EMAIL=<MASKED>
    - WEBLATE_ALLOWED_HOSTS=*
    - WEBLATE_REGISTRATION_OPEN=1
    - WEBLATE_EMAIL_HOST=127.0.0.1
    - WEBLATE_SOCIAL_AUTH_GITHUB_KEY=<MASKED>
    - WEBLATE_SOCIAL_AUTH_GITHUB_SECRET=<MASKED>
    - WEBLATE_SOCIAL_AUTH_GITHUB_SCOPE = ["user:email"]
    - WEBLATE_ENABLE_HTTPS=1

    - WEBLATE_REGISTRATION_ALLOW_BACKENDS = ["github"]
    - POSTGRES_PASSWORD=<MASKED>
    - POSTGRES_USER=<MASKED>
    - POSTGRES_DATABASE=weblate
    - POSTGRES_HOST=database
    - POSTGRES_PORT=
    - REDIS_HOST=cache
    - REDIS_PORT=6379
  database:
    image: postgres:14-alpine
    environment:
    - POSTGRES_PASSWORD=<MASKED>
    - POSTGRES_USER=<MASKED>
    - POSTGRES_DATABASE=weblate
    - POSTGRES_HOST=database
    - POSTGRES_PORT=
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == <MASKED>]
  cache:
    image: redis:6-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    deploy:
      placement:
        constraints: [node.hostname == <MASKED>]
    volumes:
    - redis-data:/data
    environment:
    - REDIS_HOST=cache
    - REDIS_PORT=6379
  cloudflared-tunnel:
    image: cloudflare/cloudflared
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == <MASKED>]
    command: tunnel run
    environment:
    - TUNNEL_TOKEN=<MASKED>
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

**Comment by YehowahLiu** [comment]
My config:
docker-compose.yml
```yml
version: '3'
services:
  weblate:
    image: weblate/weblate
    tmpfs:
    - /app/cache
    volumes:
    - weblate-data:/app/data
    env_file:
    - ./environment
    restart: always
    depends_on:
    - database
    - cache
  database:
    image: postgres:15-alpine
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```
docker-compose.override.yml
```yml
version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_SITE_DOMAIN: weblate.example.com
      WEBLATE_ADMIN_PASSWORD: password
      WEBLATE_ADMIN_EMAIL: admin@4o1.to
```
[Performance page](https://weblate.kuma.pet/manage/performance) shows that celery is not running.
No idea why Celery works with my config, as there is no line in my config that contains Celery. Maybe it's that you defined the redis host and port? I will have a try with your config.

**Comment by YehowahLiu** [comment]
Seems noting wrong with your docker-compose.yml, it works on my laptop(just remove github related environments and cloudflare-tunnel service). Celery could start up, and no stuck when adding component.
Just restart or try to destroy old containers?

**Comment by louislam** [comment]
Seems ok now, after I set `WEBLATE_DEBUG` to 0

**Comment by YehowahLiu** [comment]
Yes, it works now. And push from weblate to github also works. [See here](https://github.com/YehowahLiu/uptime-kuma/tree/weblate-depoly)
Currently, translation changes would directly push to github at configured interval. For this push method, you should add its ssh key in github with write permssion (repo settings -> depoly keys), and use SSH url for push.
SSH key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBH7ZOiUmwH0SMOma5DEm9xaFCGg2m4CJJ/uicANp3uVx+wWrPfdvX/dmDV3t89GPKolVpC+b+sDelkXWHcOs7WV2BTMHwe5pUKszSFedBD4NtzFJ98jT4wR8LC3DeB8gp58mlpCzPEhDoWqcFgbqLb6O6XL9k3yMHWupDv/RqWTaI3ce7sQsSN+1ur5oYy3JViiKpHsHiVqKjKCNEiRsAMRARuS+uFEj6dgsyFGFWaYnloCbOhSDkvwquwbyBU214+fGSSzBxiCS2pG5NdOZ2OtDcvZGgJdxa4ZWc2Rz2mOPf4ts7uEkLaWvdQgFqcAaQhC7sPkmqyIHkvZwkog8poDJPmBSzsjFBdJk38TbwPxo8Hu4RSIIPi8jUXJzXEBaOVs2SW5BtJgt1q1zKnBwKqVkq6xKAgEzpYKf2Lh38PgZZ2GH4a5C00XZUNdM/44lpeh85H0aqVt2dN4Xx/uN4KdNLO1ZUWcBS79kfR1n7AH158pByMuP0ryWyCZlUnwHBaGV/WC58fvBsS8f7KnBn3+rMp80zhOxfA3f8FUQF3WeEUBTUU8yTaGHEkFCzlVguiLDkv6t5/xnLiKvSI8M5Ya4kv/wN5HM4LQaIM5/8FeniyHiGr+vvSuaqFdhvUWHYF9fxc7tYqUNf7SEisSvC+KzyTCCplBA8vXbFsq1z7w== Uptime Kuma Weblate
```
Weblate also support create pull request on github, but need config [`GITHUB-USERNAME`](https://docs.weblate.org/en/weblate-4.15/admin/config.html#std-setting-GITHUB_USERNAME) [`GITHUB_TOKEN`](https://docs.weblate.org/en/weblate-4.15/admin/config.html#std-setting-GITHUB_TOKEN)
All available push method [here](https://docs.weblate.org/en/weblate-4.15/admin/continuous.html#pushing-changes-from-weblate)
I'll setup project with no push method first, and please let me know what push method you want to use.

**Comment by YehowahLiu** [comment]
Also, to automatically receiving changes from GitHub, webhook is required.

[Settings about continuous](https://docs.weblate.org/en/weblate-4.15/admin/continuous.htm)

**Comment by YehowahLiu** [comment]
I think we need a merge to push things forword, as json file is required in this repo to continue. Docs update and code clean up can be done in another pr.
Or should I just do these commits here?

**Comment by louislam** [comment]
It will be the highest priority pr in 1.20.0. But I am now focusing on 1.19.5 first.

**Comment by louislam** [comment]
Other contributors have submitted new language pull requests, should I merge them first?

**Comment by YehowahLiu** [comment]
You can merge them, and I 'll update my pr later.
Current translation workflow is allowed until you decide to focus on this pr.

**Comment by louislam** [comment]
> 



> Yes, it works now. And push from weblate to github also works. [See here](https://github.com/YehowahLiu/uptime-kuma/tree/weblate-depoly) Currently, translation changes would directly push to github at configured interval. For this push method, you should add its ssh key in github with write permssion (repo settings -> depoly keys), and use SSH url for push. SSH key:
> 
> ```
> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBH7ZOiUmwH0SMOma5DEm9xaFCGg2m4CJJ/uicANp3uVx+wWrPfdvX/dmDV3t89GPKolVpC+b+sDelkXWHcOs7WV2BTMHwe5pUKszSFedBD4NtzFJ98jT4wR8LC3DeB8gp58mlpCzPEhDoWqcFgbqLb6O6XL9k3yMHWupDv/RqWTaI3ce7sQsSN+1ur5oYy3JViiKpHsHiVqKjKCNEiRsAMRARuS+uFEj6dgsyFGFWaYnloCbOhSDkvwquwbyBU214+fGSSzBxiCS2pG5NdOZ2OtDcvZGgJdxa4ZWc2Rz2mOPf4ts7uEkLaWvdQgFqcAaQhC7sPkmqyIHkvZwkog8poDJPmBSzsjFBdJk38TbwPxo8Hu4RSIIPi8jUXJzXEBaOVs2SW5BtJgt1q1zKnBwKqVkq6xKAgEzpYKf2Lh38PgZZ2GH4a5C00XZUNdM/44lpeh85H0aqVt2dN4Xx/uN4KdNLO1ZUWcBS79kfR1n7AH158pByMuP0ryWyCZlUnwHBaGV/WC58fvBsS8f7KnBn3+rMp80zhOxfA3f8FUQF3WeEUBTUU8yTaGHEkFCzlVguiLDkv6t5/xnLiKvSI8M5Ya4kv/wN5HM4LQaIM5/8FeniyHiGr+vvSuaqFdhvUWHYF9fxc7tYqUNf7SEisSvC+KzyTCCplBA8vXbFsq1z7w== Uptime Kuma Weblate
> ```
> 
> Weblate also support create pull request on github, but need config [`GITHUB-USERNAME`](https://docs.weblate.org/en/weblate-4.15/admin/config.html#std-setting-GITHUB_USERNAME) [`GITHUB_TOKEN`](https://docs.weblate.org/en/weblate-4.15/admin/config.html#std-setting-GITHUB_TOKEN) All available push method [here](https://docs.weblate.org/en/weblate-4.15/admin/continuous.html#pushing-changes-from-weblate) ~I'll setup project with no push method first~ Merge required for that, and please let me know what push method you want to use.

I would like to use the pull request method.

**Comment by louislam** [comment]
Also have set up GITHUB_USERNAME, GITHUB_TOKEN. I will merge it once #2634 #2638 are merged.

**Comment by YehowahLiu** [comment]
> Also have set up GITHUB_USERNAME, GITHUB_TOKEN. 

Sorry to bother you again, but I can't see `Github` in version control system selections, which is required for pr push method, and should apper after set up `GITHUB_USERNAME` and `GITHUB_TOKEN`.

I checked the documents again, and figured out that using  `GITHUB_USERNAME` and `GITHUB_TOKEN` is deprecated since version 4.14.2. Now they recommand to use [`GITHUB_CREDENTIALS`](https://docs.weblate.org/en/weblate-4.15.1/admin/config.html#github-credentials).

Anyway, it's my fault that I didn't read their documents carefully.

> I will merge it once #2634 #2638 are merged.

After you merge them, I will commit to sync their language file changes. you can wait a bit before merge my pr.

**Comment by louislam** [comment]
I have added GITHUB_CREDENTIALS, but the GitHub option is still not available in the list. I double checked that it should be already set inside the container. Do you have any idea?

docker-compose.yml
image

Inside the container:
image


Plain text:
```
    - |
      GITHUB_CREDENTIALS = {
        "api.github.com": {
          "username": "louislam",
          "token": "gh<MASKED>F9"
        }
      }
```

**Comment by YehowahLiu** [comment]
> I have added GITHUB_CREDENTIALS, but the GitHub option is still not available in the list. I double checked that it should be already set inside the container. Do you have any idea?

No idea about that, can't see `github` option on my local deployment either, I will try to locate the problem.

**Comment by YehowahLiu** [comment]
After dive into weblate code, I figured out that its docker image use `WEBLATE_GITHUB_USERNAME` and `WEBLATE_GITHUB_TOKEN`, and the Github option would appear.

https://github.com/WeblateOrg/weblate/blob/main/weblate/settings_docker.py#L212-L214
https://github.com/WeblateOrg/weblate/blob/main/weblate/utils/environment.py#L63-L73

**Comment by louislam** [comment]
Lol, it is so confusing. Thank you for your help.
That's why I always don't like environment variables as settings. 

I see the GitHub option now.

**Comment by YehowahLiu** [comment]
Ok, It works! YehowahLiu/uptime-kuma#1

**Comment by louislam** [comment]
> Ok, It works! [YehowahLiu#1](https://github.com/YehowahLiu/uptime-kuma/pull/1)

Want to test one more thing, try to use `weblate` as the GITHUB_USERNAME

**Comment by YehowahLiu** [comment]
> Want to test one more thing, try to use `weblate` as the GITHUB_USERNAME

It won't work, as it should match the github token.
ref: https://github.com/WeblateOrg/weblate/discussions/6765

**Comment by louislam** [comment]
> > Want to test one more thing, try to use `weblate` as the GITHUB_USERNAME
> 
> It won't work, as it should match the github token. ref: [WeblateOrg/weblate#6765](https://github.com/WeblateOrg/weblate/discussions/6765)

Oh, maybe I open a new github account for that.

**Comment by YehowahLiu** [comment]
> Oh, maybe I open a new github account for that.

With a new github account, you should add the ssh key of weblate platform to it's ssh keys (https://github.com/settings/keys), and the pr would be open from fork.
Otherwise, we need a new branch for dirct push, and add ssh key to depoly key with write permission, and pr would be open from that branch.

A webhook to fetch github changes is required, url is `https://weblate.kuma.pet/hooks/github`.

I'll start without push method firstly.

**Comment by louislam** [comment]
I cannot add it. It said `Key is already in use`.

**Comment by YehowahLiu** [comment]
Deleted from my repo deploy key, you can try again. Or consider create a new one on weblate.

**Comment by louislam** [comment]
Ok now, added.

**Comment by YehowahLiu** [comment]
Focus on #2662

**Pull request merged**
