### PR TITLE
feat(monitor condition): Remove the empty default condition creation

### LINKED ISSUE #5303: Beta build: DNS monitor auto add a condition
### 📑 I have found these related issues/pull requests

It's a very small UI bug:

When you create, edit or clone a DNS monitor, it auto-add a condition.

To solve this, I recommend to not add an empty condition automatically or accept the monitor to save an empty one, ignoring it.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

New, edit or cloned DNS monitor auto-add condition:

image

### 👟 Reproduction steps

Create a new monitor and select "DNS" type, or edit an existent, or clone it.
It will not allow you to save before deleting the generated condition field.

### 👀 Expected behavior

Do not block saving process

### 😓 Actual Behavior

It blocks saving process

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu 24.04

### 🌐 Browser

Chrome 130.0.6723.92

### 🖥️ Deployment Environment

- Database: external mariadb
- number of monitors: 16

### 📝 Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Ionys320**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

The first PR related to monitors conditions were adding an empty condition. This has been removed since an empty condition disallow monitor saving. Please note this merge may be unwanted the default condition were a feature (but maybe unwished after all?). 

E2E has been updated to avoid considering we have a default condition (all `conditions` count has been reduced by 1, etc).

Fixes #5303 

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- User interface (UI)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by CommanderStorm** [comment]
My concearn in https://github.com/louislam/uptime-kuma/pull/5048#discussion_r1730428445 was that 

> Currently, I think a good percentage of people would not find this functionality and would be then somewhat confused..

=> we need to find a better way to add this only for new monitors. Sadly, I have not had the time to debug how to differentiated the 1.0 and 2.0 DNS monitors and if they are different.

**Comment by CommanderStorm** [comment]
Likely extending the dns monitor instead to include an "Record Exists" functionality or setting a wildcard as the default would be better.

**Comment by Ionys320** [comment]
Regarding DNS, adding a default condition may be done during the migration from v1 to v2, no?

**Comment by CommanderStorm** [comment]
Yes, that is a possibility

**Comment by Ionys320** [comment]
> Likely extending the dns monitor instead to include an "Record Exists" functionality or setting a wildcard as the default would be better.

I prefer the default wildcard. Using defaut values allows us to keep the conditions system for future monitors without needing too much work.

**Comment by Ionys320** [comment]
After trying to add a default condition with a wildcard, I realized the wildcard was handled by the conditions system as a standard character, so the condition can't be true (`records` wouldn't be `equals` to `*`). Therefore, I wonder about what can we do.

Another solution I thought about with another project would be to make a pulsing incidator next to "Conditions" title.

image
image

https://github.com/user-attachments/assets/e0199a82-a988-43c7-8abd-2eb761bef08f

**Pull request merged**
