### PR TITLE
Added a fix for mikrotik RouterOS container comptabiltiy

### PR DESCRIPTION
**Pull request by elico**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [X] I have read and understand the pull request rules.

# Description

Fixes Mikrotik volume issue which prevents it from applying cleanly a chwon on /app/data.
In Mikrotik forums there was a post about how to "resolve" the issue:
https://forum.mikrotik.com/viewtopic.php?p=976750#p975199

And this specific change gives clarity with the `set -x` and the `rm -fv` of this .type file prevents later on to `chown` of the `/app/data/.type`  which to my understanding is unique for Mikrotik container  mount points.

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code and tested it
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by elico** [comment]
I am willing to accept a better fix that will not erase the .type file that mikorik put in the folder.

**Comment by louislam** [comment]
I usually don't touch this entrypoint.sh, as touching this usually causes unpredictable issues to current working instances.

I would recommend that your community should maintain your special build first and wait for #2086 which the `entrypoint.sh` will be fully dropped and it will not chown anymore.

**Comment by elico** [comment]
@louislam it's the most basic bash script ever.
If you are in any doubts about this change I made please stay on point.
It's basically just excluding the file name ".type" from the /app/data chown path and files list.
I will wait for #2086 but is there any specific time for this release?

**Comment by k3rnelpan1c-dev** [comment]
If you are looking for a community maintained container image without entry point I can offer the one I maintain for [OpenShift over here](https://github.com/k3rnelpan1c-dev/uptime-kuma-helm/).

On a different note, louislam, would you be interested in me up-streaming changes similar to what I have there for your 2.x target?
I would tag along the GitHub Action based build process.
(asking cause I saw other PRs in regards to GitHub Actions getting dismissed :confused:)

**Comment by iNaiks** [comment]
> @louislam it's the most basic bash script ever.
> If you are in any doubts about this change I made please stay on point.
> It's basically just excluding the file name ".type" from the /app/data chown path and files list.
> I will wait for #2086 but is there any specific time for this release?

Any news for a easy install on mikrotik?

**Comment by elico** [comment]
@iNaiks Mikrotik fixed this issue in their latest 7.8 release and it should work without this workaround.

**Comment by iNaiks** [comment]
> @iNaiks Mikrotik fixed this issue in their latest 7.8 release and it should work without this workaround.

Fantastic 🤩. Very Thanks. 

What is the good space to install? Because I’ve some hAP ac 3, and I want to try. But it’s only 128mb of disk.

**Comment by elico** [comment]
external usb disk or flash.

בתאריך יום ד׳, 29 במרץ 2023, 19:43, מאת iNaiks ***@***.***>:

**Comment by CommanderStorm** [comment]
> Mikrotik fixed this issue in their latest 7.8 release and it should work without this workaround.

@elico 
I think that this PR is not needed anymore.
How do you think about this? Can you close this PR if it is no longer relevant?

**Pull request closed without merging**
