### PR TITLE
Update `pl.js`

### PR DESCRIPTION
**Pull request by Saibamen**
# Description

`pl.js` translation update

## Type of change

Please delete options that are not relevant.

- Translation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and test it
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by Saibamen** [comment]
CC: @kry008, @zsxeee, @atlochowski, @NixNotCastey, @Misly16

**Comment by Misly16** [comment]
lgtm

**Review by NixNotCastey — APPROVED** [review]
Looks good

**Comment by Saibamen** [comment]
I added some more fixes. IMO PR is ready for final Code Review

**Review by NixNotCastey — APPROVED** [review]

**Pull request merged**
