### PR TITLE
fix: Both `Add` and `Home` being shown as selected on the homescreen

### PR DESCRIPTION
**Pull request by CommanderStorm**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Noticed by @DevItq in #3244
Fixes
image

## Type of change

Please delete any options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

| site | previous | now |
|--------|--------|--------|
| `/add` | image | image  |
| `/edit/:monitorid` | image | image |
| `/clone/:monitorid`  | image| image|

### CODE REVIEW

**Comment by louislam** [comment]
As I remembered, it is hard to handle both desktop and mobile. Vue router somehow is complicated and hard to test, I would not  recommend making changes to it.

For example:
After this pr, `[404] Fail` won't be highlighted in the list anymore in the monitor list while entered the edit page. 

image

**Comment by CommanderStorm** [comment]
I have fixed the issue the change to the nesting of `edit:id`:
image

Current implementation:
- it fixes `Home`+`Add` being shown for adding+cloning
- keeps the edit-activation as is
- **But**: removes the outline from 
  image

Do you think this is a good tradeoff?

**Comment by CommanderStorm** [comment]
@louislam do you think reviewing this in `2.1`/`1.23.12` would be possible?
(a "no, removing the desktop outline from cloned monitors is not ok" and closing this PR would also be a fine choice..)

**Comment by CommanderStorm** [comment]
I know this is merging my own PR, but I don't think there is more to review and the tradeoff is likely better than existing..

**Pull request merged**
