### PR TITLE
Windows Executable File - uptime-kuma.exe

### PR DESCRIPTION
**Pull request by louislam**
# Description

- Standalone 
- Portable
- C# Project
- .NET Framework 4.7.2

## TODO

- [ ] Start on system startup
- [ ] Show/Hide Debug console at runtime
- [ ] `config.json`, and then convert it to arguments and pass to Node.js 
- [ ] A script that builds a release into `uptime-kuma-win64-1.8.3.zip`
- [x] Auto download missing files (node and uptime-kuma)

image

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Review by Rayhubi — APPROVED** [review]

**Comment by finnie2006** [comment]
This is very cool!

**Comment by WTCVCC** [comment]
Is this the Windows version of your app?  I'm trying to install on a Windows Server.  Thanks for this, it looks like a very nice program.

**Review by Ronica6801 — APPROVED** [review]

**Review by Ronica6801 — APPROVED** [review]

**Comment by louislam** [comment]
Will be released along with 1.21.0. 

You can try now, but due to the bug of `download-dist` in `1.20.0` on Node.js 18, the command prompt do not closed after done. You have to restart uptime-kuma.exe again, it will be fine.

Download:
[uptime-kuma-1.0.0-preview.zip](https://github.com/louislam/uptime-kuma/files/10787262/uptime-kuma-1.0.0-preview.zip)

I will also try to publish to `winget`, it can be installed by `winget install uptime-kuma`

image

**Comment by Saibamen** [comment]
@louislam: Why old .NET Framework instead of .NET 6 (LTS) or 7?

**Pull request merged**
