### PR TITLE
Built-in Caddy to support Let's encrypt 🐻🍬

### PR DESCRIPTION
**Pull request by louislam**
# Description

- [ ] Rename `Settings > Reverse Proxy` to `Settings > Network`
- [ ] Add a Caddy section under it.
- [ ] A toggle button for start/stop Caddy
- [ ] A domain list (Add/Remove) to specify which domains need SSL cert.
- [ ] HTTPS Port field (Default 443)
- [ ] Environment variables and arguments. If both values specified, it will start along with caddy: 
  - `UPTIME_KUMA_CADDY_DOMAIN_LIST=domain1.com,domain2.com`
  - `UPTIME_KUMA_CADDY_PORT=443`
- [ ] Checkbox - Enable HTTP Redirect and Port 80

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by chakflying** [comment]
Maybe Caddy should control `80,443` within the container if enabled. The user can remap them outside the container if needed.

**Comment by louislam** [comment]
> Maybe Caddy should control `80,443` within the container if enabled. The user can remap them outside the container if needed.

Good point, as it also won't affect non-Docker user.

**Comment by Subnet-Masked** [comment]
Would this automatically support domain names for status pages, including ssl certificate creation for them?

I am using an NGINX reverse proxy outside of the docker container right now to add SSL and this would be a fantastic change to make that unnecessary so that I don't need to update the NGINX config when setting domains for status pages :)

**Comment by trogper** [comment]
Why is another webserver needed? Express.js by itself [can handle multiple SSL certificates](https://levelup.gitconnected.com/multi-domain-ssl-in-node-js-with-certbot-8f0df5331d47) (for different domains).

**Comment by GrantBirki** [comment]
@louislam You may find this example useful..

Here is a repo I am a maintainer for where we are using uptime-kuma and a Caddy server to automatically provision TLS certificates and proxy all traffic: https://github.com/the-hideout/status

**Pull request closed without merging**
