### PR TITLE
Added Finnish language translation

### PR DESCRIPTION
**Pull request by JonneSaloranta**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Added a language translations (Finnish)

## Type of change

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [ ] I have performed a self-review of my own code and tested it
- [ ] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [ ] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by JonneSaloranta** [comment]
Now with 100% Finnish translations.
picture

**Comment by louislam** [comment]
Will be merged after #2770, thanks

**Comment by louislam** [comment]
Just realized that it had been merged previously, but it should be `fi` instead of `fi-FI`?

https://github.com/louislam/uptime-kuma/blob/master/src/lang/fi.json

**Comment by JonneSaloranta** [comment]
Interesting... did not think to check the lang file. How come some other languages are using xx-XX format and some are not?

**Pull request merged**
