### PR TITLE
tests: add testcase for the mqtt monitor with testcontainers

### PR DESCRIPTION
**Pull request by CommanderStorm**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]:
- [x] I have read and understand the pull request rules.

# Description

This issue is meant as a discussion.

I have thought a bunch about how our monitors can be tested and have come to the conclusion that for most monitors, [testcontainers](https://node.testcontainers.org/) seem like a good fit.
Testing this part would allow us to merged PRs like #4445 or #4393 without the risk or the level of manual verification required.

Things that we should discuss:
- should new monitors be tested like this
- does addition of these tests add additional value? How important/is this important? (=> "do we want this? if yes, which merge slot")

## Type of change

Please delete any options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Other
- This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generates no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

<- screenshot of testcases passing ->

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Pro tip: if u making empty PR use `--allow-empty` flag 😉

**Comment by Zaid-maker** [comment]
> This issue is meant as a discussion.

Louis should enable Discussions for this repo now for discussing this types of things

**Comment by louislam** [comment]
Interesting. It is able to run on GitHub Actions?

**Comment by Zaid-maker** [comment]
> Interesting. It is able to run on GitHub Actions?

Yes I guess so I tried it once

**Comment by CommanderStorm** [comment]
I don't see a reason why it cannot.
There might be some (minor) [CI adaptations](https://www.linkedin.com/pulse/how-run-testcontainers-nodejs-github-actions-habib-akinwale-wvawe), but I can make + test those.

**Comment by Zaid-maker** [comment]
> I don't see a reason why it cannot. There might be some (minor) [CI adaptations](https://www.linkedin.com/pulse/how-run-testcontainers-nodejs-github-actions-habib-akinwale-wvawe), but I can make + test those.

Cool idea 💡 let's try 😀

**Pull request merged**
