### PR TITLE
HU language typo

### PR DESCRIPTION
**Pull request by BCsabaEngine**
# Description
I have found some mistype and a few missing item in hungarian translation. Corrected.
Yout tests run with v14, v16 and v17 and works well. npm run setup shows engine error, because package.json. Corrected.

## Type of change

Please delete options that are not relevant.

- User Interface
- Translation update
- package.json

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and test it
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My code needed automated testing. I have added them (this is optional task)

### CODE REVIEW

**Comment by BCsabaEngine** [comment]
"Auto Test / auto-test (macos-latest, 14.x) (pull_request)" test has only timeout problem.

**Comment by Saibamen** [comment]
@BCsabaEngine Please run `npm run update-language-files` and translate the latest keys added in https://github.com/louislam/uptime-kuma/pull/902

**Comment by chakflying** [comment]
Please ignore the test fail for now.

**Comment by BCsabaEngine** [comment]
> @BCsabaEngine Please run `npm run update-language-files` and translate the latest keys added in #902

I have understand the method and completed. New PR created, waiting for checks. Thx!

**Comment by Saibamen** [comment]
New PR: https://github.com/louislam/uptime-kuma/pull/996

**Pull request merged**
