### PR TITLE
feat/#2331:When monitoring HTTP, add a User Agent.

### PR DESCRIPTION
**Pull request by yangs1202**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description
It is intended to verify that it is an internal check system through a user agent.

By default, you send "Uptime Kuma"
Allows the user to put the User Agent in the character set by the user.

UI: Allows the user to input a user agent to be used for monitoring.
Monitor: Check Health with User Agent input from UI.

Fixes #(issue)

## Type of change
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

## Screenshots (if any)
스크린샷 2022-11-18 20 10 18
image

### CODE REVIEW

**Comment by rezzorix** [comment]
You can already adjust the http headers - in that you can define the user-agent…

Wouldnt your PR and the existing option then collide e.g. when a user-agent is defined in http headers and your new option-field?

**Comment by louislam** [comment]
> You can already adjust the http headers - in that you can define the user-agent…
> 
> Wouldnt your PR and the existing option then collide e.g. when a user-agent is defined in http headers and your new option-field?

Good point. I think the custom headers could override the User Agent already.

Also this implementation is just appending a custom string in front of `Uptime-Kuma/1.19.3` which is a bit strange.

**Comment by yangs1202** [comment]
I didn't know it had a function.
I'll close the PR.

Thank you.

**Comment by yangs1202** [comment]
I didn't know it had a function.
I'll close the PR.

Thank you.

**Pull request closed without merging**
