### PR TITLE
#3370 - Add support for monitoring IBM DB2 databases

### LINKED ISSUE #3370: Add support for monitoring IBM DB2 databases
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

It would be great to also be able to monitor other DBs such as IBM DB2:

* https://www.ibm.com/products/db2

### ✔️ Solution

Replicate the setup for MS SQL server, but with different connection methods and parameters to connect and test DB2 instances.

### ❓ Alternatives

I'm currently using a TCP Port test, but this only checks if the port is open, not whether a DB is actually available on that port and properly functioning.

### 📝 Additional Context

One can easily run DB2 with Docker:
* https://www.ibm.com/docs/en/db2/11.5?topic=system-linux
* https://hub.docker.com/r/ibmcom/db2

Its seems there's an NPM library for interfacing with DB2: https://www.npmjs.com/package/ibm_db

### PR DESCRIPTION
**Pull request by jfcabral**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Resolves #3370 feature request

## Type of change

Please delete any options that are not relevant.

- User interface (UI)
- New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings

## Notes

* Heavily inspired in the `postgres` and `MySQL` implementations
* Just like for `postgres`, I've used a default query to make it easier to set up
* Uses https://www.npmjs.com/package/ibm_db to access db2
* I've used this connection string format for testing: `DATABASE=<dbname>;HOSTNAME=<myhost>;UID=db2user;PWD=password;PORT=<dbport>;PROTOCOL=TCPIP`
* I've used the official db2 docker container for testing purposes https://hub.docker.com/r/ibmcom/db2/

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

image

image

image

image

If you have any question, feedback or suggestion, please do not hesitate to say so :)

### CODE REVIEW

**Comment by louislam** [comment]
Thanks for the pr. Please note that `npm install` failed on arm64/armv7 due to the native build issue.

CONTRIBUTING.md
> Easy to install for non-Docker users, no native build dependency is needed (for x86_64/armv7/arm64)

**Comment by jfcabral** [comment]
> Thanks for the pr. 

You're very welcome 😉 

> Please note that `npm install` failed on arm64/armv7 due to the native build issue.

Yeah, I've noticed 😕 

Unfortunately, it seems that the only IBM DB2 node module that's available, is based on a native dependency: https://www.npmjs.com/package/ibm_db

After some research, it seems there's not a pure JS module to interface with DB2, and there probably won't ever be one, due to licensing questions...😞

> CONTRIBUTING.md
> 
> > Easy to install for non-Docker users, no native build dependency is needed (for x86_64/armv7/arm64)

I understand your point, after all, native dependencies are quite a fuss. Besides that, I don't think this `ibm_db` module even works on arm at all (at least I haven't been able to make it work on arm v8 x64). 😢

Yet, it works quite well on x64, and I was able to test it using the new Codespace Environment that you set up. without any change at all.

 IMHO, for ease of usage, Docker should be the way to go, yet, I agree that constraining the usage of non docker users seems

**Comment by jfcabral** [comment]
> Thanks for the pr. 

You're very welcome 😉 

> Please note that `npm install` failed on arm64/armv7 due to the native build issue.

Yeah, I've noticed 😕 

Unfortunately, it seems that the only IBM DB2 node module that's available, is based on a native build dependency: https://www.npmjs.com/package/ibm_db

After some research, it seems there's not a pure JS module to interface with DB2, and there probably won't ever be one, due to licensing questions...😞

> CONTRIBUTING.md
> 
> > Easy to install for non-Docker users, no native build dependency is needed (for x86_64/armv7/arm64)

I understand your point, after all, native dependencies are quite a fuss. Besides that, I don't think this `ibm_db` module even works on arm at all (at least I haven't been able to make it work on arm v8 x64). 😢

Yet, it works quite well on x64, and I was able to test it using the new Codespace Environment that you set up. without any change at all 😄 

IMHO, for ease of usage, Docker should be the way to go. Yet, I understand it's not really acceptable to constrain the usage of the app for non docker users...

I wonder if it would be possible to use this `ibm_db` as an optional dependency of sorts, and prepare the frontend/backend to somehow deal with it like it's described here:
```js
try {
  var foo = require('foo')
  var fooVersion = require('foo/package.json').version
} catch (er) {
  foo = null
}
if ( notGoodFooVersion(fooVersion) ) {
  foo = null
}
// .. then later in your program ..
if (foo) {
  foo.doFooThings()
}
```
This way, it would still be compatible with all the required versions, but this db2 monitor functionality would only be available for the compatible architectures. What do you think about this @louislam?

Thank you

**Comment by CommanderStorm** [comment]
Could you please change `Implements #3370` to `Resolves #3370` in the pr-description (this way merging this PR would close the linked issue)

**Comment by jfcabral** [comment]
@louislam, hi, could you please check my question about the next steps? https://github.com/louislam/uptime-kuma/pull/3439#issuecomment-1648754307
Thank you

**Comment by CommanderStorm** [comment]
I am going to close this PR as support for non-Docker (armv7/arm64) users without native dependencies is a hard requirement for monitors in uptime kuma.
If IBM changes their mind and offers a package which does not require this, we can reopen this issue.
We would like to have such a monitor, but are not willing to accept the current drawbacks this would incur.

As it stands, I don't see how keeping this issue open and hoping that IBM changes their mind will get anywhere.

We would like to encourage a second option, developing an agent:

`Uptime Kuma` <-> `Agent` <-> `Oracle DB`

`Agent` = An HTTP Server with an entry point that allows to make a request with a connection string and a query
`Uptime Kuma` = Make a http request to the `Agent`


If somebody develops an agent, we can include this in the [unofficial/experimental section of our installation guide](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#unofficial--experimental).

**Comment by jfcabral** [comment]
Hello @CommanderStorm, 

Thank you for your reply 😄 

So, from what I understand, you're not really keen on this approach either https://github.com/louislam/uptime-kuma/pull/3439#issuecomment-1648754307 right?

Regarding the `Agent` approach, it does seem to be an interesting idea 👍 
I have one question though, assuming the agent is created and running somewhere, how do you see this being configured in Kuma?

Because, in terms of **DB Monitor configuration**, I do like the existing setup where you can input the `Connection String` and `Query`. That said, would it be acceptable for me to create a new DB2 Monitor "external agent edition", that besides the `Connection String` and `Query`, would also receive the URL for the agent? What are your thoughts on that?

Thank you once again

**Comment by CommanderStorm** [comment]
Running on armv7/arm64 is a hard requirement, sorry
I don't see how https://github.com/louislam/uptime-kuma/pull/3439#issuecomment-1648754307 does support armv7/arm64.

As far as I read their docs, `npm install ibm_db` would just error out => hard-bricking armv7/arm64

Such code would be a mess to test, and I don't see us having the capacity currently to do that, sorry.
If we had tests such as discussed in https://github.com/louislam/uptime-kuma/pull/4451 this might not be such a big issue.

As stated above:
If [IBM changes their mind](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#-10-steps-to-install-ibm_db-on-macos-m1m2-chip-system-arm64-architecture) about supporting this platform, we can reopen this issue

**Pull request closed without merging**
